--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS241', 'I',  9, 1999, 12, 2008, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS256', 'D', 11, 1999,  9, 2004, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS272', 'H',  7, 2000,  5, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS312', 'C',  7, 2001,  9, 2004, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS340', 'J',  5, 2001, 12, 2008, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS344', 'G',  1, 2002, 10, 2009, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS361', 'D',  1, 2002,  8, 2004, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS368', 'G', 10, 2002,  3, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS380', 'F',  4, 2004,  3, 2022, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS383', 'E', 10, 2003, 12, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS396', 'D',  7, 2003, 11, 2016, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS439', 'F',  9, 2004,  8, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS455', 'D',  3, 2005,  4, 2007, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS491', 'I',  8, 2005, 12, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS504', 'G',  7, 2006,  8, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS508', 'K',  4, 2006,  5, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS518', 'E',  8, 2006,  8, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS541', 'M',  6, 2007,  3, 2022, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS545', 'C',  5, 2007,  3, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS547', 'I',  6, 2007, 12, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS554', 'I',  5, 2009,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS555', 'B',  6, 2012,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS556', 'A',  7, 2007,  8, 2007, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS566', 'G',  6, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS578', 'J', 11, 2007,  1, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS580', 'E', 10, 2008,  5, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS584', 'C', 10, 2008,  7, 2010, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS587', '' ,  2, 2008,  2, 2008, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS588', '' ,  2, 2008,  2, 2008, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS590', 'P',  3, 2009,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS614', 'D',  9, 2008,  5, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS616', '' ,  7, 2008,  7, 2008, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS619', 'R',  8, 2010,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS626', 'C', 10, 2008,  3, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS629', 'B',  3, 2009,  5, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS639', 'L',  7, 2011, 12, 2017, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS645', 'L',  7, 2009,  5, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS648', 'E',  4, 2009,  3, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS650', 'G',  5, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS655', 'H',  1, 2010,  5, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS673', '' ,  9, 2010,  9, 2010, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS675', '' , 10, 2009, 10, 2009, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS677', 'G',  9, 2010,  5, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS678', 'G',  8, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS694', 'J',  2, 2010,  2, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS695', 'I',  2, 2010,  2, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS697', 'E',  3, 2010, 11, 2016, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS700', 'E', 10, 2012,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS701', 'B', 11, 2010,  6, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS703', 'C',  4, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS704', 'G', 10, 2012,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS706', 'F',  7, 2011,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS713', '' ,  6, 2010,  6, 2010, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS718', 'H', 11, 2012,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS720', 'F',  8, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS721', 'F',  8, 2010,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS722', 'G', 12, 2010,  5, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS723', 'H', 12, 2010,  5, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS731', 'D', 12, 2011,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS734', 'G',  4, 2011,  4, 2016, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS735', 'J',  4, 2011,  5, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS753', 'E',  1, 2012,  2, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS768', 'E',  9, 2012,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS770', 'B', 11, 2011,  3, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS774', 'A',  7, 2011, 10, 2011, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS775', 'E',  8, 2011,  3, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS787', 'B', 11, 2011,  3, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS789', 'D',  6, 2014,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS797', 'C',  8, 2014,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS800', '' ,  3, 2013,  3, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS815', 'D', 11, 2012,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS824', '' , 12, 2013, 12, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS862', '' ,  6, 2012,  6, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS863', '' ,  8, 2012,  8, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS865', 'F', 10, 2014, 12, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS868', 'A',  6, 2012, 11, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS874', 'B',  5, 2015,  9, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS885', 'A',  8, 2012, 10, 2012, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS887', 'C',  9, 2014,  3, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS892', 'C',  3, 2013,  9, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS897', 'C',  9, 2013, 10, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS903', 'D',  5, 2013, 10, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS913', 'A',  7, 2013,  8, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS942', 'E', 11, 2015, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS954', '' , 12, 2013, 12, 2013, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS966', '' ,  3, 2014,  3, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS967', 'A',  1, 2014,  1, 2014, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS982', 'A',  5, 2014,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS983', 'A',  5, 2014,  9, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLAS998', 'A',  6, 2014, 10, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE23', 'E',  1, 2015,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE32', 'C',  8, 2014,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE33', 'C',  8, 2014,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE34', 'E',  5, 2014,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE35', 'C',  5, 2014, 12, 2017, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE45', 'E', 10, 2014, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE46', 'A',  2, 2015, 10, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE50', 'A',  2, 2015, 10, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE54', 'D',  3, 2016,  1, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE58', 'E',  2, 2016, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE59', 'F', 10, 2015, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE66', 'C',  4, 2015,  8, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASE78', 'E',  8, 2016,  6, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEB7', 'D',  6, 2017, 12, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEC3', 'A',  8, 2016,  8, 2016, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEC4', 'D',  5, 2018, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEC9', '' ,  4, 2017,  4, 2017, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEE4', 'C',  1, 2018, 12, 2019, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEE5', 'D',  1, 2018,  1, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEF5', 'B',  1, 2019, 12, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEK0', 'A', 12, 2017,  3, 2018, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEO5', 'D',  3, 2019,  9, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEO7', 'C',  3, 2019,  9, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEU5', 'A', 10, 2019,  2, 2021, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLASEV3', 'A',  3, 2020, 12, 2020, 'MASS IMPORT FROM TSV');
INSERT INTO datasheet (id, revision, issue_month, issue_year, rev_month, rev_year, comment) VALUES ('SLVSCN6', 'A', 11, 2014, 12, 2014, 'MASS IMPORT FROM TSV');

COMMIT TRANSACTION;
