--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO signalgroup (name) VALUES ('ADC_SAR');
INSERT INTO signalgroup (name) VALUES ('ADC_SD');
INSERT INTO signalgroup (name) VALUES ('BSL');
INSERT INTO signalgroup (name) VALUES ('CAPTIVATE');
INSERT INTO signalgroup (name) VALUES ('DMA');
INSERT INTO signalgroup (name) VALUES ('LCD');
INSERT INTO signalgroup (name) VALUES ('USCI_A');
INSERT INTO signalgroup (name) VALUES ('USCI_B');

INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A0'       ,        NULL, 'Analog input A0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A1'       ,        NULL, 'Analog input A1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A2'       ,        NULL, 'Analog input A2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A3'       ,        NULL, 'Analog input A3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A4'       ,        NULL, 'Analog input A4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A5'       ,        NULL, 'Analog input A5');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A6'       ,        NULL, 'Analog input A6');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'A7'       ,        NULL, 'Analog input A7');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ACLK'     ,        NULL, 'ACLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ADC10CLK' ,        NULL, 'ADC10, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ADC12CLK' ,        NULL, 'ADC12, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVCC'     ,        NULL, 'Analog power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVSS'     ,        NULL, 'Analog power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'BSL_RX'   ,        NULL, 'EXTRA SIGNAL: BSL UART receive');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'BSL_SCL'  ,        NULL, 'EXTRA SIGNAL: BSL I²C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'BSL_SDA'  ,        NULL, 'EXTRA SIGNAL: BSL I²C data transmit and receive');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'BSL_TX'   ,        NULL, 'EXTRA SIGNAL: BSL UART transmit');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA0'      ,        NULL, 'Comparator_A+, CA0 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA1'      ,        NULL, 'Comparator_A+, CA1 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA2'      ,        NULL, 'Comparator_A+, CA2 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA3'      ,        NULL, 'Comparator_A+, CA3 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA4'      ,        NULL, 'Comparator_A+, CA4 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA5'      ,        NULL, 'Comparator_A+, CA5 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA6'      ,        NULL, 'Comparator_A+, CA6 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA7'      ,        NULL, 'Comparator_A+, CA7 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAOUT'    ,        NULL, 'Comparator_A+, output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP0.0'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP0.1'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP0.2'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP0.3'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP1.0'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP1.1'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP1.2'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP1.3'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP2.0'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP2.1'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP2.2'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP2.3'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP3.0'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP3.1'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP3.2'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAP3.3'   ,        NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DNC'      ,        NULL, 'Do not connect');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVCC'     ,        NULL, 'Power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVSS'     ,        NULL, 'Power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'MCLK'     ,        NULL, 'MCLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'NC'       ,        NULL, 'Not connected');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'NMI'      ,        NULL, 'Nonmaskable interrupt input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P1.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P2.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P3.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P4.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P5.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.0'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.1'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.2'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.3'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.4'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.5'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.6'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'P6.7'     ,        NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RESERVED' ,        NULL, 'Reserved');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RSVD'     , 'RESERVED' , 'Reserved');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ROSC'     ,        NULL, 'Input for external resistor defining the DCO nominal frequency');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SBWTCK'   ,        NULL, 'Spy-Bi-Wire input clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SBWTDIO'  ,        NULL, 'Spy-Bi-Wire data input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SMCLK'    ,        NULL, 'SMCLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SYNC'     ,        NULL, 'CapTIvate synchronous trigger input for processing and conversion');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.0'    ,        NULL, 'Timer TA0 CCR0 capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0'      , 'TA0.0'    , 'Timer_A, capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.1'    ,        NULL, 'Timer TA0 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1'      , 'TA0.1'    , 'Timer_A, capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.2'    ,        NULL, 'Timer TA0 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2'      , 'TA0.2'    , 'Timer_A, capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0CLK'   ,        NULL, 'Timer clock input TACLK for TA0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TACLK'    , 'TA0CLK'   , 'Timer_A, clock signal TACLK input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TAINCLK'  , 'TA0CLK'   , 'Timer_A, clock signal at INCLK');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.0'    ,        NULL, 'Timer TA1 CCR0 capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.1'    ,        NULL, 'Timer TA1 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.2'    ,        NULL, 'Timer TA1 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1CLK'   ,        NULL, 'Timer clock input TACLK for TA1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0'      ,        NULL, 'Timer_B, capture: CCI0A or CCI0B input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1'      ,        NULL, 'Timer_B, capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2'      ,        NULL, 'Timer_B, capture: CCI2A or CCI2B input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3'      ,        NULL, 'Timer_B, capture: CCI3A or CCI3B input, compare: Out3 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB4'      ,        NULL, 'Timer_B, capture: CCI4A or CCI4B input, compare: Out4 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB5'      ,        NULL, 'Timer_B, capture: CCI5A or CCI5B input, compare: Out5 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB6'      ,        NULL, 'Timer_B, capture: CCI6A or CCI6B input, compare: Out6 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TBCLK'    ,        NULL, 'Timer_B, clock signal TBCLK input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TBOUTH'   ,        NULL, 'Switch all PWM digital output ports to high impedance for Timer_B');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TCK'      ,        NULL, 'Test clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TCLK'     ,        NULL, 'Test clock input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TDI'      ,        NULL, 'Test data input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TDO'      ,        NULL, 'Test data output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TEST'     ,        NULL, 'Test Mode pin');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TMS'      ,        NULL, 'Test mode select');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0CLK'  ,        NULL, 'eUSCI_A0 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCLK0'    , 'UCA0CLK'  , 'USART0 clock: external input in UART or SPI mode, output in SPI mode');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0RXD'  ,        NULL, 'eUSCI_A0 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'URXD0'    , 'UCA0RXD'  , 'USART0 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0SIMO' ,        NULL, 'eUSCI_A0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SIMO0'    , 'UCA0SIMO' , 'USAR0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0SOMI' ,        NULL, 'eUSCI_A0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SOMI0'    , 'UCA0SOMI' , 'USART0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0STE'  ,        NULL, 'eUSCI_A0 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'STE0'     , 'UCA0STE'  , 'USART0 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0TXD'  ,        NULL, 'eUSCI_A0 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UTXD0'    , 'UCA0TXD'  , 'USART0 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1CLK'  ,        NULL, 'eUSCI_A1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCLK1'    , 'UCA1CLK'  , 'USART1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1RXD'  ,        NULL, 'eUSCI_A1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'URXD1'    , 'UCA1RXD'  , 'USART1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1SIMO' ,        NULL, 'eUSCI_A1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SIMO1'    , 'UCA1SIMO' , 'USART1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1SOMI' ,        NULL, 'eUSCI_A1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SOMI1'    , 'UCA1SOMI' , 'USART1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1STE'  ,        NULL, 'eUSCI_A1 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'STE1'     , 'UCA1STE'  , 'USART1 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1TXD'  ,        NULL, 'eUSCI_A1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UTXD1'    , 'UCA1TXD'  , 'USART1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0CLK'  ,        NULL, 'eUSCI_B0 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SCL'  ,        NULL, 'eUSCI_B0 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SDA'  ,        NULL, 'eUSCI_B0 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SIMO' ,        NULL, 'eUSCI_B0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SOMI' ,        NULL, 'eUSCI_B0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0STE'  ,        NULL, 'eUSCI_B0 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VEREF+'   ,        NULL, 'ADC positive reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VEREF-'   ,        NULL, 'ADC negative reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREF+'    ,        NULL, 'Output of positive reference voltage with ground as reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREF-'    ,        NULL, 'Output of negative reference voltage with ground as reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREG'     ,        NULL, 'CapTIvate regulator external decoupling capacitor');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XIN'      ,        NULL, 'Input terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XOUT'     ,        NULL, 'Output terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XT2IN'    ,        NULL, 'Input terminal for crystal oscillator XT2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XT2OUT'   ,        NULL, 'Output terminal for crystal oscillator XT2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, '~RST'     ,        NULL, 'Active-low reset input');

COMMIT TRANSACTION;
