--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO signalgroup (name) VALUES ('ADC_SAR');
INSERT INTO signalgroup (name) VALUES ('ADC_SD');
INSERT INTO signalgroup (name) VALUES ('BSL');
INSERT INTO signalgroup (name) VALUES ('CAPTIVATE');
INSERT INTO signalgroup (name) VALUES ('DMA');
INSERT INTO signalgroup (name) VALUES ('GPIO');
INSERT INTO signalgroup (name) VALUES ('JTAG');
INSERT INTO signalgroup (name) VALUES ('LCD');
INSERT INTO signalgroup (name) VALUES ('USCI_A');
INSERT INTO signalgroup (name) VALUES ('USCI_B');
INSERT INTO signalgroup (name) VALUES ('WRONG');

INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ACLK'       ,          NULL, 'ACLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AGND'       ,          NULL, 'Analog ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVCC'       ,          NULL, 'Analog power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVCC1'      , 'AVCC'       , 'Analog power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVCC_RF'    ,          NULL, 'Radio analog power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVSS'       ,          NULL, 'Analog power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVSS1'      , 'AVSS'       , 'Analog power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVSS2'      , 'AVSS'       , 'Analog power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'AVSS3'      , 'AVSS'       , 'Analog power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C0'         ,          NULL, 'Comparator input channel C0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C1'         ,          NULL, 'Comparator input channel C1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C10'        ,          NULL, 'Comparator input channel C10');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C11'        ,          NULL, 'Comparator input channel C11');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C12'        ,          NULL, 'Comparator input channel C12');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C13'        ,          NULL, 'Comparator input channel C13');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C14'        ,          NULL, 'Comparator input channel C14');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C15'        ,          NULL, 'Comparator input channel C15');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C2'         ,          NULL, 'Comparator input channel C2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C3'         ,          NULL, 'Comparator input channel C3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C4'         ,          NULL, 'Comparator input channel C4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C5'         ,          NULL, 'Comparator input channel C5');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C6'         ,          NULL, 'Comparator input channel C6');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C7'         ,          NULL, 'Comparator input channel C7');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C8'         ,          NULL, 'Comparator input channel C8');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'C9'         ,          NULL, 'Comparator input channel C9');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA0'        ,          NULL, 'Comparator_A+, CA0 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA1'        ,          NULL, 'Comparator_A+, CA1 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA2'        ,          NULL, 'Comparator_A+, CA2 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA3'        ,          NULL, 'Comparator_A+, CA3 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA4'        ,          NULL, 'Comparator_A+, CA4 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA5'        ,          NULL, 'Comparator_A+, CA5 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA6'        ,          NULL, 'Comparator_A+, CA6 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CA7'        ,          NULL, 'Comparator_A+, CA7 input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CAOUT'      ,          NULL, 'Comparator_A+, output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB0'        ,          NULL, 'Comparator_B input CB0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB1'        ,          NULL, 'Comparator_B input CB1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB10'       ,          NULL, 'Comparator_B input CB10');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB11'       ,          NULL, 'Comparator_B input CB11');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB2'        ,          NULL, 'Comparator_B input CB2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB3'        ,          NULL, 'Comparator_B input CB3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB4'        ,          NULL, 'Comparator_B input CB4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB5'        ,          NULL, 'Comparator_B input CB5');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB6'        ,          NULL, 'Comparator_B input CB6');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB7'        ,          NULL, 'Comparator_B input CB7');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB8'        ,          NULL, 'Comparator_B input CB8');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CB9'        ,          NULL, 'Comparator_B input CB9');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'CBOUT'      ,          NULL, 'Comparator_B output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0.0'    ,          NULL, 'Enhanced comparator input channel C0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0.1'    ,          NULL, 'Enhanced comparator input channel C1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0.2'    ,          NULL, 'Enhanced comparator input channel C2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0.3'    ,          NULL, 'Enhanced comparator input channel C3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0.O'    ,          NULL, 'Comparator output channel COUT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0OUT'   ,          NULL, 'Enhanced comparator output channel COUT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0_0'    ,          NULL, 'Comparator input channel C0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP0_1'    ,          NULL, 'Comparator input channel C1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP1.0'    ,          NULL, 'Comparator input channel C0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP1.1'    ,          NULL, 'Comparator input channel C1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COMP1.O'    ,          NULL, 'Comparator output channel COUT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'COUT'       ,          NULL, 'Comparator output channel COUT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DAC0'       ,          NULL, 'DAC12.0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DAC1'       ,          NULL, 'DAC12.1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DGND'       ,          NULL, 'Digital ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DM'         ,          NULL, 'USB data terminal DM');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DMAE0'      ,          NULL, 'External DMA trigger');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DNC'        ,          NULL, 'Do not connect');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DP'         ,          NULL, 'USB data terminal DP');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVCC'       ,          NULL, 'Digital power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVCC1'      , 'DVCC'       , 'Digital power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVCC2'      , 'DVCC'       , 'Digital power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVCC3'      , 'DVCC'       , 'Digital power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVSS'       ,          NULL, 'Digital power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVSS1'      , 'DVSS'       , 'Digital power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVSS2'      , 'DVSS'       , 'Digital power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'DVSS3'      , 'DVSS'       , 'Digital power ground');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESIC1OUT'   ,          NULL, 'ESI Comparator 1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESIC2OUT'   ,          NULL, 'ESI Comparator 2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICH0'     ,          NULL, 'ESI channel 0 sensor excitation output and signal input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICH1'     ,          NULL, 'ESI channel 1 sensor excitation output and signal input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICH2'     ,          NULL, 'ESI channel 2 sensor excitation output and signal input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICH3'     ,          NULL, 'ESI channel 3 sensor excitation output and signal input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICI'      ,          NULL, 'ESI Scan IF input to Comparator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICI0'     ,          NULL, 'ESI channel 0 signal input to comparator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICI1'     ,          NULL, 'ESI channel 1 signal input to comparator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICI2'     ,          NULL, 'ESI channel 2 signal input to comparator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICI3'     ,          NULL, 'ESI channel 3 signal input to comparator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESICOM'     ,          NULL, 'ESI Common termination for');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESIDVCC'    ,          NULL, 'ESI power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESIDVSS'    ,          NULL, 'ESI ground supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESITEST0'   ,          NULL, 'ESI test signal 0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESITEST1'   ,          NULL, 'ESI test signal 1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESITEST2'   ,          NULL, 'ESI test signal 2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESITEST3'   ,          NULL, 'ESI test signal 3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ESITEST4'   ,          NULL, 'ESI test signal 4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'GUARD'      ,          NULL, 'Power supply connection for digital noise isolation');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'HFXIN'      ,          NULL, 'Input for high-frequency crystal oscillator HFXT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'HFXOUT'     ,          NULL, 'Output for high-frequency crystal oscillator HFXT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ISORXD'     ,          NULL, 'ISO receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ISOTXD'     ,          NULL, 'ISO transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'LFXIN'      ,          NULL, 'Input for low-frequency crystal oscillator LFXT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'LFXOUT'     ,          NULL, 'Output for low-frequency crystal oscillator LFXT');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'MCLK'       ,          NULL, 'MCLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'MFM.RX'     ,          NULL, 'Manchester function module receive');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'MFM.TX'     ,          NULL, 'Manchester function module transmit');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'NC'         ,          NULL, 'Not connected');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'NMI'        ,          NULL, 'Nonmaskable interrupt input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA0+'       ,          NULL, 'SAC0, OA positive input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA0-'       ,          NULL, 'SAC0, OA negative input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA0O'       ,          NULL, 'SAC0, OA output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA1+'       ,          NULL, 'SAC1, OA positive input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA1-'       ,          NULL, 'SAC1, OA negative input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA1O'       ,          NULL, 'SAC1, OA output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA2+'       ,          NULL, 'SAC2, OA positive input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA2-'       ,          NULL, 'SAC1, OA negative input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA2O'       ,          NULL, 'SAC1, OA output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA3+'       ,          NULL, 'SAC3, OA positive input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA3-'       ,          NULL, 'SAC3, OA negative input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'OA3O'       ,          NULL, 'SAC3, OA output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_ACLK'    ,          NULL, 'Default mapping: ACLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_ADC10CLK',          NULL, 'Default mapping: ADC10, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_ADC12CLK',          NULL, 'Default mapping: ADC12, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_CBOUT0'  ,          NULL, 'Comparator_B output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_CBOUT1'  ,          NULL, 'Comparator_B output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_DMAE0'   ,          NULL, 'Default mapping: External DMA trigger');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_NONE'    ,          NULL, 'Default mapping: no secondary function.');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_RFGDO0'  ,          NULL, 'Radio GDO0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_RFGDO1'  ,          NULL, 'Radio GDO1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_RFGDO2'  ,          NULL, 'Radio GDO2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_RTCCLK'  ,          NULL, 'Default mapping: RTC clock calibration output ');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_SMCLK'   ,          NULL, 'Default mapping: SMCLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_SVMOUT'  ,          NULL, 'Default mapping: SVM output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CCR0A',          NULL, 'Timer TA0 CCR0 capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CCR1A',          NULL, 'Timer TA0 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CCR2A',          NULL, 'Timer TA0 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CCR3A',          NULL, 'Timer TA0 CCR3 capture: CCI3A input, compare: Out3 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CCR4A',          NULL, 'Timer TA0 CCR4 capture: CCI4A input, compare: Out4 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA0CLK'  ,          NULL, 'Default mapping: Timer clock input TACLK for TA0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA1CCR0A',          NULL, 'Timer TA1 CCR0 capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA1CCR1A',          NULL, 'Timer TA1 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA1CCR2A',          NULL, 'Timer TA1 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_TA1CLK'  ,          NULL, 'Default mapping: Timer clock input TACLK for TA1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0CLK' ,          NULL, 'Default mapping: eUSCI_A0 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0RXD' ,          NULL, 'Default mapping: eUSCI_A0 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0SIMO',          NULL, 'Default mapping: eUSCI_A0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0SOMI',          NULL, 'Default mapping: eUSCI_A0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0STE' ,          NULL, 'Default mapping: eUSCI_A0 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA0TXD' ,          NULL, 'Default mapping: eUSCI_A0 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1CLK' ,          NULL, 'Default mapping: eUSCI_A1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1RXD' ,          NULL, 'Default mapping: eUSCI_A1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1SIMO',          NULL, 'Default mapping: eUSCI_A1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1SOMI',          NULL, 'Default mapping: eUSCI_A1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1STE' ,          NULL, 'Default mapping: eUSCI_A1 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCA1TXD' ,          NULL, 'Default mapping: eUSCI_A1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0CLK' ,          NULL, 'Default mapping: eUSCI_B0 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0SCL' ,          NULL, 'Default mapping: eUSCI_B0 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0SDA' ,          NULL, 'Default mapping: eUSCI_B0 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0SIMO',          NULL, 'Default mapping: eUSCI_B0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0SOMI',          NULL, 'Default mapping: eUSCI_B0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB0STE' ,          NULL, 'Default mapping: eUSCI_B0 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1CLK' ,          NULL, 'Default mapping: eUSCI_B1 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1SCL' ,          NULL, 'Default mapping: eUSCI_B1 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1SDA' ,          NULL, 'Default mapping: eUSCI_B1 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1SIMO',          NULL, 'Default mapping: eUSCI_B1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1SOMI',          NULL, 'Default mapping: eUSCI_B1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PM_UCB1STE' ,          NULL, 'Default mapping: eUSCI_B1 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PU.0'       ,          NULL, 'General-purpose digital I/O. Controlled by USB control register');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PU.1'       ,          NULL, 'General-purpose digital I/O. Controlled by USB control register');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'PUR'        ,          NULL, 'USB pullup resistor pin (open drain)');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RBIAS'      ,          NULL, 'External bias resistor for radio reference current');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RESERVED'   ,          NULL, 'Reserved');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RSVD'       , 'RESERVED'   , 'Reserved');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RF_N'       ,          NULL, 'Negative RF input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RF_P'       ,          NULL, 'Positive RF input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RF_XIN'     ,          NULL, 'Input terminal for RF crystal oscillator, or external clock input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RF_XOUT'    ,          NULL, 'Output terminal for RF crystal oscillator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'ROSC'       ,          NULL, 'Input for external resistor defining the DCO nominal frequency');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'RTCCLK'     ,          NULL, 'RTC clock calibration output ');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SBWTCK'     ,          NULL, 'Spy-Bi-Wire input clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SBWTDIO'    ,          NULL, 'Spy-Bi-Wire data input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SCL'        ,          NULL, 'I2C clock - USART0/I2C mode');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SDA'        ,          NULL, 'I2C data - USART0/I2C mode');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SIMO0'      ,          NULL, 'USAR0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SIMO1'      ,          NULL, 'USART1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SMCLK'      ,          NULL, 'SMCLK output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SOMI0'      ,          NULL, 'USART0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SOMI1'      ,          NULL, 'USART1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SRCPUOFF'   ,          NULL, 'Low-Power Debug: CPU Status Register Bit CPUOFF');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SROSCOFF'   ,          NULL, 'Low-Power Debug: CPU Status Register Bit OSCOFF');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SRSCG0'     ,          NULL, 'Low-Power Debug: CPU Status Register Bit SCG0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SRSCG1'     ,          NULL, 'Low-Power Debug: CPU Status Register Bit SCG1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'STE0'       ,          NULL, 'USART0 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'STE1'       ,          NULL, 'USART1 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SVMOUT'     ,          NULL, 'SVM output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SVSIN'      ,          NULL, 'SVS input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SVSOUT'     ,          NULL, 'SVS comparator output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'SYNC'       ,          NULL, 'CapTIvate synchronous trigger input for processing and conversion');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.0'      ,          NULL, 'Timer TA0 CCR0 capture: CCI0A or CCI0B input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0'        , 'TA0.0'      , 'Timer_A, capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.1'      ,          NULL, 'Timer TA0 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1'        , 'TA0.1'      , 'Timer_A, capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.2'      ,          NULL, 'Timer TA0 CCR2 capture: CCI2A or CCI2B input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2'        , 'TA0.2'      , 'Timer_A, capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.3'      ,          NULL, 'Timer TA0 CCR3 capture: CCI3A or CCI3B input, compare: Out3 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0.4'      ,          NULL, 'Timer TA0 CCR4 capture: CCI4A or CCI4B input, compare: Out4 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA0CLK'     ,          NULL, 'Timer clock input TACLK for TA0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TACLK'      , 'TA0CLK'     , 'Timer_A, clock signal TACLK input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TAINCLK'    , 'TA0CLK'     , 'Timer_A, clock signal at INCLK');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.0'      ,          NULL, 'Timer TA1 CCR0 capture: CCI0A or CCI0B input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.1'      ,          NULL, 'Timer TA1 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1.2'      ,          NULL, 'Timer TA1 CCR2 capture: CCI2A or CCI2B input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA1CLK'     ,          NULL, 'Timer clock input TACLK for TA1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2.0'      ,          NULL, 'Timer TA2 CCR0 capture: CCI0A or CCI0B input, compare: Out0 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2.1'      ,          NULL, 'Timer TA2 CCR1 capture: CCI1A or CCI1B input, compare: Out1 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2.2'      ,          NULL, 'Timer TA2 CCR2 capture: CCI2A or CCI2B input, compare: Out2 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA2CLK'     ,          NULL, 'Timer clock input TACLK for TA2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA3.0'      ,          NULL, 'Timer TA3 CCR0 capture: CCI0A or CCI0B input, compare: Out0 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA3.1'      ,          NULL, 'Timer TA3 CCR1 capture: CCI1A or CCI1B input, compare: Out1 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA3.2'      ,          NULL, 'Timer TA3 CCR2 capture: CCI2A or CCI2B input, compare: Out2 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA3CLK'     ,          NULL, 'Timer clock input TACLK for TA3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA4.0'      ,          NULL, 'Timer TA4 CCR0 capture: CCI0A or CCI0B input, compare: Out0 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA4.1'      ,          NULL, 'Timer TA4 CCR1 capture: CCI1A or CCI1B input, compare: Out1 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TA4CLK'     ,          NULL, 'Timer clock input TACLK for TA4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0'        ,          NULL, 'Timer_B, capture: CCI0A or CCI0B input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.0'      ,          NULL, 'Timer TB0 CCR0 capture: CCI0A or CCI0B input, compare: Out0 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.1'      ,          NULL, 'Timer TB0 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.2'      ,          NULL, 'Timer TB0 CCR2 capture: CCI2A or CCI2B input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.3'      ,          NULL, 'Timer TB0 CCR3 capture: CCI3A or CCI3B input, compare: Out3 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.4'      ,          NULL, 'Timer TB0 CCR4 capture: CCI4A or CCI4B input, compare: Out4 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.5'      ,          NULL, 'Timer TB0 CCR5 capture: CCI5A or CCI5B input, compare: Out5 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0.6'      ,          NULL, 'Timer TB0 CCR6 capture: CCI6A or CCI6B input, compare: Out6 outputs');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0CLK'     ,          NULL, 'Timer clock input TBCLK for TB0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0OUTH'    ,          NULL, 'Switch all PWM digital output ports to high impedance for TB0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB0TRG'     ,          NULL, 'TB0 external trigger input for TB0OUTH');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1'        ,          NULL, 'Timer_B, capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1.1'      ,          NULL, 'Timer TB1 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1.2'      ,          NULL, 'Timer TB1 CCR2 capture: CCI2A or CCI2B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1CLK'     ,          NULL, 'Timer clock input TBCLK for TB1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB1TRG'     ,          NULL, 'TB1 external trigger input for TB1OUTH');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2'        ,          NULL, 'Timer_B, capture: CCI2A or CCI2B input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2.1'      ,          NULL, 'Timer TB2 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2.2'      ,          NULL, 'Timer TB2 CCR2 capture: CCI2A or CCI2B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2CLK'     ,          NULL, 'Timer clock input TBCLK for TB2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB2TRG'     ,          NULL, 'TB2 external trigger input for TB2OUTH');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3'        ,          NULL, 'Timer_B, capture: CCI3A or CCI3B input, compare: Out3 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.1'      ,          NULL, 'Timer TB3 CCR1 capture: CCI1A or CCI1B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.2'      ,          NULL, 'Timer TB3 CCR2 capture: CCI2A or CCI2B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.3'      ,          NULL, 'Timer TB3 CCR3 capture: CCI3A or CCI3B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.4'      ,          NULL, 'Timer TB3 CCR4 capture: CCI4A or CCI4B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.5'      ,          NULL, 'Timer TB3 CCR5 capture: CCI5A or CCI5B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3.6'      ,          NULL, 'Timer TB3 CCR6 capture: CCI6A or CCI6B input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3CLK'     ,          NULL, 'Timer clock input TBCLK for TB3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB3TRG'     ,          NULL, 'TB3 external trigger input for TB3OUTH');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB4'        ,          NULL, 'Timer_B, capture: CCI4A or CCI4B input, compare: Out4 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB5'        ,          NULL, 'Timer_B, capture: CCI5A or CCI5B input, compare: Out5 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TB6'        ,          NULL, 'Timer_B, capture: CCI6A or CCI6B input, compare: Out6 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TBCLK'      ,          NULL, 'Timer_B, clock signal TBCLK input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TBOUTH'     ,          NULL, 'Switch all PWM digital output ports to high impedance for Timer_B');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TRI0+'      ,          NULL, 'TIA0 positive input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TRI0-'      ,          NULL, 'TIA0 negative input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'TRI0O'      ,          NULL, 'TIA0 output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0CLK'    ,          NULL, 'eUSCI_A0 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0RXD'    ,          NULL, 'eUSCI_A0 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0SIMO'   ,          NULL, 'eUSCI_A0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0SOMI'   ,          NULL, 'eUSCI_A0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0STE'    ,          NULL, 'eUSCI_A0 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA0TXD'    ,          NULL, 'eUSCI_A0 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1CLK'    ,          NULL, 'eUSCI_A1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1RXD'    ,          NULL, 'eUSCI_A1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1SIMO'   ,          NULL, 'eUSCI_A1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1SOMI'   ,          NULL, 'eUSCI_A1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1STE'    ,          NULL, 'eUSCI_A1 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA1TXD'    ,          NULL, 'eUSCI_A1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2CLK'    ,          NULL, 'USART2 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2RXD'    ,          NULL, 'eUSCI_A2 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2SIMO'   ,          NULL, 'eUSCI_A2 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2SOMI'   ,          NULL, 'eUSCI_A2 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2STE'    ,          NULL, 'eUSCI_A2 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA2TXD'    ,          NULL, 'eUSCI_A2 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3CLK'    ,          NULL, 'eUSCI_A3 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3RXD'    ,          NULL, 'eUSCI_A3 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3SIMO'   ,          NULL, 'eUSCI_A3 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3SOMI'   ,          NULL, 'eUSCI_A3 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3STE'    ,          NULL, 'eUSCI_A3 SPI slave');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCA3TXD'    ,          NULL, 'eUSCI_A3 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0CLK'    ,          NULL, 'eUSCI_B0 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SCL'    ,          NULL, 'eUSCI_B0 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SDA'    ,          NULL, 'eUSCI_B0 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SIMO'   ,          NULL, 'eUSCI_B0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0SOMI'   ,          NULL, 'eUSCI_B0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB0STE'    ,          NULL, 'eUSCI_B0 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1CLK'    ,          NULL, 'eUSCI_B1 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1SCL'    ,          NULL, 'eUSCI_B1 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1SDA'    ,          NULL, 'eUSCI_B1 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1SIMO'   ,          NULL, 'eUSCI_B1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1SOMI'   ,          NULL, 'eUSCI_B1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB1STE'    ,          NULL, 'eUSCI_B1 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2CLK'    ,          NULL, 'eUSCI_B2 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2SCL'    ,          NULL, 'eUSCI_B2 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2SDA'    ,          NULL, 'eUSCI_B2 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2SIMO'   ,          NULL, 'eUSCI_B2 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2SOMI'   ,          NULL, 'eUSCI_B2 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB2STE'    ,          NULL, 'eUSCI_B2 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3CLK'    ,          NULL, 'eUSCI_B3 clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3SCL'    ,          NULL, 'eUSCI_B3 I2C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3SDA'    ,          NULL, 'eUSCI_B3 I2C data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3SIMO'   ,          NULL, 'eUSCI_B3 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3SOMI'   ,          NULL, 'eUSCI_B3 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCB3STE'    ,          NULL, 'eUSCI_B3 slave transmit enable');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCLK0'      ,          NULL, 'USART0 clock: external input in UART or SPI mode, output in SPI mode');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UCLK1'      ,          NULL, 'USART1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'URXD0'      ,          NULL, 'USART0 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'URXD1'      ,          NULL, 'USART1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UTXD0'      ,          NULL, 'USART0 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'UTXD1'      ,          NULL, 'USART1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'V18'        ,          NULL, 'USB regulated power');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VBUS'       ,          NULL, 'USB LDO input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VCORE'      ,          NULL, 'Regulated core power supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VEREF+'     ,          NULL, 'ADC positive reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VEREF-'     ,          NULL, 'ADC negative reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREF+'      ,          NULL, 'Output of positive reference voltage with ground as reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREF-'      ,          NULL, 'Output of negative reference voltage with ground as reference');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VREG'       ,          NULL, 'CapTIvate regulator external decoupling capacitor');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VSSU'       ,          NULL, 'USB PHY ground supply');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'VUSB'       ,          NULL, 'USB LDO output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XIN'        ,          NULL, 'Input terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XOUT'       ,          NULL, 'Output terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XT2IN'      ,          NULL, 'Input terminal for crystal oscillator XT2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, 'XT2OUT'     ,          NULL, 'Output terminal for crystal oscillator XT2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, '~RST'       ,          NULL, 'Active-low reset input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, '~UCA1RXD'   ,          NULL, 'Active-low eUSCI_A1 UART receive data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES (       NULL, '~UCA1TXD'   ,          NULL, 'Active-low eUSCI_A1 UART transmit data');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A0'         ,          NULL, 'Analog input A0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A1'         ,          NULL, 'Analog input A1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A10'        ,          NULL, 'Analog input A10');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A11'        ,          NULL, 'Analog input A11');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A12'        ,          NULL, 'Analog input A12');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A13'        ,          NULL, 'Analog input A13');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A14'        ,          NULL, 'Analog input A14');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A15'        ,          NULL, 'Analog input A15');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A16'        ,          NULL, 'Analog input A16');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A17'        ,          NULL, 'Analog input A17');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A18'        ,          NULL, 'Analog input A18');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A19'        ,          NULL, 'Analog input A19');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A2'         ,          NULL, 'Analog input A2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A3'         ,          NULL, 'Analog input A3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A4'         ,          NULL, 'Analog input A4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A5'         ,          NULL, 'Analog input A5');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A6'         ,          NULL, 'Analog input A6');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A7'         ,          NULL, 'Analog input A7');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A8'         ,          NULL, 'Analog input A8');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'A9'         ,          NULL, 'Analog input A9');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'ADC10CLK'   ,          NULL, 'ADC10, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('ADC_SAR'  , 'ADC12CLK'   ,          NULL, 'ADC12, conversion clock output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('BSL'      , 'BSLRX'      ,          NULL, 'EXTRA SIGNAL: BSL UART receive');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('BSL'      , 'BSLSCL'     ,          NULL, 'EXTRA SIGNAL: BSL I²C clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('BSL'      , 'BSLSDA'     ,          NULL, 'EXTRA SIGNAL: BSL I²C data transmit and receive');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('BSL'      , 'BSLTX'      ,          NULL, 'EXTRA SIGNAL: BSL UART transmit');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP0.0'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP0.1'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP0.2'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP0.3'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP1.0'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP1.1'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP1.2'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP1.3'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP2.0'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP2.1'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP2.2'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP2.3'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP3.0'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP3.1'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP3.2'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('CAPTIVATE', 'CAP3.3'     ,          NULL, 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P1.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.0'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.1'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.2'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.3'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.4'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.5'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.6'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P10.7'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.0'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.1'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.2'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.3'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.4'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.5'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.6'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P11.7'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.0'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.1'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.2'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.3'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.4'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.5'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.6'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P12.7'      ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P2.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P3.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P4.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P5.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P6.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P7.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P8.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'P9.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.0'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.1'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.2'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.3'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.4'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.5'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.6'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('GPIO'     , 'PJ.7'       ,          NULL, 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TCK'        ,          NULL, 'Test clock');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TCLK'       ,          NULL, 'Test clock input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TDI'        ,          NULL, 'Test data input');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TDO'        ,          NULL, 'Test data output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TEST'       ,          NULL, 'Test Mode pin');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('JTAG'     , 'TMS'        ,          NULL, 'Test mode select');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM0'       ,          NULL, 'LCD common output COM0 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM1'       ,          NULL, 'LCD common output COM1 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM2'       ,          NULL, 'LCD common output COM2 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM3'       ,          NULL, 'LCD common output COM3 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM4'       ,          NULL, 'LCD common output COM4 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM5'       ,          NULL, 'LCD common output COM5 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM6'       ,          NULL, 'LCD common output COM6 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'COM7'       ,          NULL, 'LCD common output COM7 for LCD backplane');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L0'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L1'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L10'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L11'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L12'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L13'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L14'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L15'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L16'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L17'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L18'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L19'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L2'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L20'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L21'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L22'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L23'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L24'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L25'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L26'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L27'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L28'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L29'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L3'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L30'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L31'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L32'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L33'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L34'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L35'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L36'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L37'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L38'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L39'        ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L4'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L5'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L6'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L7'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L8'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'L9'         ,          NULL, 'LCD drive pin; either segment or common output');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'LCDCAP'     ,          NULL, 'LCD capacitor connection');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'LCDCAP0'    ,          NULL, 'LCD charge pump external port connecting to LCDCAP0 pin');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'LCDCAP1'    ,          NULL, 'LCD charge pump external port connecting to LCDCAP1 pin');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'LCDREF'     ,          NULL, 'External reference voltage input for regulated LCD voltage');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'R03'        ,          NULL, 'Input/output port of lowest analog LCD voltage (V5)');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'R13'        ,          NULL, 'Input/output port of third most positive analog LCD voltage (V3 or V4)');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'R23'        ,          NULL, 'Input/output port of second most positive analog LCD voltage (V2)');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'R33'        ,          NULL, 'Input/output port of most positive analog LCD voltage (V1)');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S0'         ,          NULL, 'LCD segment output S0');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S1'         ,          NULL, 'LCD segment output S1');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S10'        ,          NULL, 'LCD segment output S10');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S11'        ,          NULL, 'LCD segment output S11');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S12'        ,          NULL, 'LCD segment output S12');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S13'        ,          NULL, 'LCD segment output S13');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S14'        ,          NULL, 'LCD segment output S14');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S15'        ,          NULL, 'LCD segment output S15');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S16'        ,          NULL, 'LCD segment output S16');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S17'        ,          NULL, 'LCD segment output S17');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S18'        ,          NULL, 'LCD segment output S18');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S19'        ,          NULL, 'LCD segment output S19');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S2'         ,          NULL, 'LCD segment output S2');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S20'        ,          NULL, 'LCD segment output S20');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S21'        ,          NULL, 'LCD segment output S21');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S22'        ,          NULL, 'LCD segment output S22');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S23'        ,          NULL, 'LCD segment output S23');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S24'        ,          NULL, 'LCD segment output S24');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S25'        ,          NULL, 'LCD segment output S25');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S26'        ,          NULL, 'LCD segment output S26');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S27'        ,          NULL, 'LCD segment output S27');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S28'        ,          NULL, 'LCD segment output S28');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S29'        ,          NULL, 'LCD segment output S29');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S3'         ,          NULL, 'LCD segment output S3');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S30'        ,          NULL, 'LCD segment output S30');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S31'        ,          NULL, 'LCD segment output S31');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S32'        ,          NULL, 'LCD segment output S32');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S33'        ,          NULL, 'LCD segment output S33');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S34'        ,          NULL, 'LCD segment output S34');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S35'        ,          NULL, 'LCD segment output S35');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S36'        ,          NULL, 'LCD segment output S36');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S37'        ,          NULL, 'LCD segment output S37');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S38'        ,          NULL, 'LCD segment output S38');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S39'        ,          NULL, 'LCD segment output S39');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S4'         ,          NULL, 'LCD segment output S4');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S40'        ,          NULL, 'LCD segment output S40');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S41'        ,          NULL, 'LCD segment output S41');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S42'        ,          NULL, 'LCD segment output S42');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S43'        ,          NULL, 'LCD segment output S43');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S5'         ,          NULL, 'LCD segment output S5');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S6'         ,          NULL, 'LCD segment output S6');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S7'         ,          NULL, 'LCD segment output S7');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S8'         ,          NULL, 'LCD segment output S8');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('LCD'      , 'S9'         ,          NULL, 'LCD segment output S9');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('WRONG'    , 'VREF+/VEREF+',          NULL, 'WRONG use VREF+ and VEREF+');
INSERT INTO signal (signalgroup, id, alias_for, desc) VALUES ('WRONG'    , 'VREF-/VEREF-',          NULL, 'WRONG use VREF- and VEREF-');

COMMIT TRANSACTION;
