--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153', 'SLASEC4', 24, 16384, 2048, 44, 2, 0, 2, 4, 2, 4, -40, 105, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155', 'SLASEC4', 24, 32768, 4096, 44, 2, 0, 2, 4, 2, 4, -40, 105, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353', 'SLASEC4', 24, 16384, 2048, 44, 2, 0, 2, 4, 2, 4, -40, 105, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355', 'SLASEC4', 24, 32768, 4096, 44, 2, 0, 2, 4, 2, 4, -40, 105, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2153', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2153', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2153', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2155', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2155', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2155', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2353', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2353', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2353', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2353', 'SAC_DAC'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2355', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2355', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2355', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2355', 'SAC_DAC'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TDBT' , 'MSP430FR2153', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TDBTR', 'MSP430FR2153', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TPT'  , 'MSP430FR2153', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TPTR' , 'MSP430FR2153', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TRHAR', 'MSP430FR2153', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TRHAT', 'MSP430FR2153', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TRSMR', 'MSP430FR2153', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2153TRSMT', 'MSP430FR2153', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TDBT' , 'MSP430FR2155', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TDBTR', 'MSP430FR2155', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TPT'  , 'MSP430FR2155', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TPTR' , 'MSP430FR2155', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TRHAR', 'MSP430FR2155', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TRHAT', 'MSP430FR2155', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TRSMR', 'MSP430FR2155', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2155TRSMT', 'MSP430FR2155', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TDBT' , 'MSP430FR2353', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TDBTR', 'MSP430FR2353', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TPT'  , 'MSP430FR2353', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TPTR' , 'MSP430FR2353', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TRHAR', 'MSP430FR2353', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TRHAT', 'MSP430FR2353', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TRSMR', 'MSP430FR2353', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2353TRSMT', 'MSP430FR2353', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TDBT' , 'MSP430FR2355', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TDBTR', 'MSP430FR2355', 'DBT', 38, 'ACTIVE', 2, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TPT'  , 'MSP430FR2355', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TPTR' , 'MSP430FR2355', 'PT' , 48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TRHAR', 'MSP430FR2355', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TRHAT', 'MSP430FR2355', 'RHA', 40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TRSMR', 'MSP430FR2355', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2355TRSMT', 'MSP430FR2355', 'RSM', 32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (19, NULL, 38, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (20, NULL, 48, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (21, NULL, 40, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (22, NULL, 32, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (23,   19, 12, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (24,   20, 12, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (25,   21, 12, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (26,   22, 12, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (27,   19,  2, 2, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (28,   20,  2, 2, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (29,   21,  2, 2, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (30,   23,  2, 3, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (31,   24,  2, 3, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (32,   25,  2, 3, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (214, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (262,  214,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (215, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (263,  215,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (216, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (217, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (218, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (219, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (220, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (221, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (222, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (223, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (224, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (225, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (264,  225, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (276,  264, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (226, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (265,  226, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (277,  265, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (227, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (228, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (229, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (230, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (231, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (232, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (233, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (234, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (235, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (236, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (237, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (238, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (239, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (240, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (241, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (242, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (243, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (244, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (266,  244, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (245, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (267,  245, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (246, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (268,  246, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (247, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (248, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (269,  248, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (249, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (270,  249, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (250, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (271,  250, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (251, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (252, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (253, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (254, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (255, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (256, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (257, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (272,  257, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (258, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (273,  258, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (259, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (274,  259, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (260, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (261, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (275,  261, 47);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 214, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 214, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 214, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 214, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 262, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 262, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 262, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 262, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 215, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 215, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 215, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 215, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 263, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 263, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 263, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 263, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 216, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 216, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 216, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 216, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 217, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 217, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 217, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 217, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 218, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 218, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 218, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 218, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 219, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 219, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 219, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 219, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 220, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 220, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 220, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 220, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 221, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 221, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 221, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 221, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 222, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 222, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 222, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 222, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 223, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 223, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 223, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 223, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 224, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 224, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 224, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 224, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 225, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 225, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 225, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 225, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (27, 264, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (28, 264, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (29, 264, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (30, 276, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (31, 276, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (32, 276, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 226, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 226, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 226, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 226, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (27, 265, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (28, 265, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (29, 265, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (30, 277, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (31, 277, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (32, 277, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 227, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 227, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 227, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 228, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 228, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 228, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 229, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 230, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 231, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 232, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 233, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 234, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 234, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 235, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 235, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 236, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 236, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 236, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 236, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 237, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 237, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 237, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 237, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 238, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 238, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 238, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 238, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 239, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 239, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 239, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 239, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 240, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 240, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 240, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 241, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 241, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 241, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 242, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 242, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 242, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 242, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 243, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 243, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 243, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 243, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 244, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 244, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 244, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 244, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 266, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 266, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 266, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 266, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 245, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 245, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 245, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 245, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 267, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 267, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 267, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 267, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 246, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 246, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 246, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 246, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 268, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 268, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 268, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 268, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 247, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 247, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 247, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 247, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 248, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 248, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 248, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 248, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 269, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 269, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 269, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 269, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 249, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 249, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 249, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 249, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 270, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 270, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 270, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 270, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 250, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 250, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 250, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 250, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 271, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 271, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 271, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 271, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 251, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 251, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 251, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 251, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 252, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 253, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 254, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 255, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 255, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 255, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 256, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 256, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 256, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 257, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 257, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 257, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 257, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 272, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 272, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 272, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 272, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 258, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 258, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 258, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 258, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 273, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 273, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 273, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 273, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 259, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 259, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 259, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 259, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 274, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 274, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 274, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 274, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 260, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 260, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 260, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 260, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (19, 261, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (20, 261, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (21, 261, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (22, 261, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (23, 275, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (24, 275, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (25, 275, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (26, 275, NULL, 31);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 3, 'TB0TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (262, 4, 'OA0-'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 5, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 6, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (214, 7, 'BSLSDA'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (215, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (215, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (215, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (263, 3, 'OA0O'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (215, 4, 'COMP0_1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (215, 5, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 3, 'COMP0_0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (216, 5, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (217, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (217, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (218, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (218, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (218, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (219, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (220, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (221, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (221, 1, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (221, 2, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (222, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (222, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (222, 2, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (223, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (223, 1, 'COMP1.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (224, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (224, 1, 'COMP1.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (225, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (264, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (276, 2, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (225, 3, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (226, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (265, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (277, 2, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (226, 3, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (227, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (227, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (228, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (228, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (229, 0, 'P6.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (229, 1, 'TB3CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (230, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (230, 1, 'TB3.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (231, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (231, 1, 'TB3.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (232, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (232, 1, 'TB3.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (233, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (233, 1, 'TB3.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (234, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (234, 1, 'TB3.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (235, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (235, 1, 'TB3.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (236, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (236, 1, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (236, 2, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (236, 3, '~UCA1TXD'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (237, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (237, 1, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (237, 2, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (237, 3, '~UCA1RXD'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (238, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (238, 1, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (239, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (239, 1, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (239, 2, 'ISOTXD'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (239, 3, 'ISORXD'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (240, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (240, 1, 'TB1TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (241, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (241, 1, 'TB1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (242, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (242, 1, 'TB1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (242, 2, 'COMP1.O'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (243, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (243, 1, 'TB1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (243, 2, 'COMP0.O'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 3, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 4, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (266, 5, 'OA1+'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 6, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 7, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (244, 8, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 3, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 4, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 5, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (267, 6, 'OA1-'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 7, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (245, 8, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (246, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (246, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (246, 2, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (268, 3, 'OA1O'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (246, 4, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (247, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (247, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (247, 2, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (247, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (248, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (269, 1, 'OA3+'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (249, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (270, 1, 'OA3-'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (250, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (271, 1, 'OA3O'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (251, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (251, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (252, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (253, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (253, 1, 'TB2TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (253, 2, 'A11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (254, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (254, 1, 'TB2CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (254, 2, 'A10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (255, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (255, 1, 'TB2.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (255, 2, 'MFM.TX'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (255, 3, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (256, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (256, 1, 'TB2.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (256, 2, 'MFM.RX'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (256, 3, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (257, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (272, 1, 'OA2+'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (258, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (273, 1, 'OA2-'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (259, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (274, 1, 'OA2O'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (260, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (260, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (261, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (261, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (261, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (275, 3, 'OA0+'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (261, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (261, 5, 'BSLSCL'     );

UPDATE orderable SET pinset_id = 27 WHERE name = 'MSP430FR2153TDBT' ;
UPDATE orderable SET pinset_id = 27 WHERE name = 'MSP430FR2153TDBTR';
UPDATE orderable SET pinset_id = 27 WHERE name = 'MSP430FR2155TDBT' ;
UPDATE orderable SET pinset_id = 27 WHERE name = 'MSP430FR2155TDBTR';
UPDATE orderable SET pinset_id = 30 WHERE name = 'MSP430FR2353TDBT' ;
UPDATE orderable SET pinset_id = 30 WHERE name = 'MSP430FR2353TDBTR';
UPDATE orderable SET pinset_id = 30 WHERE name = 'MSP430FR2355TDBT' ;
UPDATE orderable SET pinset_id = 30 WHERE name = 'MSP430FR2355TDBTR';
UPDATE orderable SET pinset_id = 28 WHERE name = 'MSP430FR2153TPT'  ;
UPDATE orderable SET pinset_id = 28 WHERE name = 'MSP430FR2153TPTR' ;
UPDATE orderable SET pinset_id = 28 WHERE name = 'MSP430FR2155TPT'  ;
UPDATE orderable SET pinset_id = 28 WHERE name = 'MSP430FR2155TPTR' ;
UPDATE orderable SET pinset_id = 31 WHERE name = 'MSP430FR2353TPT'  ;
UPDATE orderable SET pinset_id = 31 WHERE name = 'MSP430FR2353TPTR' ;
UPDATE orderable SET pinset_id = 31 WHERE name = 'MSP430FR2355TPT'  ;
UPDATE orderable SET pinset_id = 31 WHERE name = 'MSP430FR2355TPTR' ;
UPDATE orderable SET pinset_id = 29 WHERE name = 'MSP430FR2153TRHAR';
UPDATE orderable SET pinset_id = 29 WHERE name = 'MSP430FR2153TRHAT';
UPDATE orderable SET pinset_id = 29 WHERE name = 'MSP430FR2155TRHAR';
UPDATE orderable SET pinset_id = 29 WHERE name = 'MSP430FR2155TRHAT';
UPDATE orderable SET pinset_id = 32 WHERE name = 'MSP430FR2353TRHAR';
UPDATE orderable SET pinset_id = 32 WHERE name = 'MSP430FR2353TRHAT';
UPDATE orderable SET pinset_id = 32 WHERE name = 'MSP430FR2355TRHAR';
UPDATE orderable SET pinset_id = 32 WHERE name = 'MSP430FR2355TRHAT';
UPDATE orderable SET pinset_id = 22 WHERE name = 'MSP430FR2153TRSMR';
UPDATE orderable SET pinset_id = 22 WHERE name = 'MSP430FR2153TRSMT';
UPDATE orderable SET pinset_id = 22 WHERE name = 'MSP430FR2155TRSMR';
UPDATE orderable SET pinset_id = 22 WHERE name = 'MSP430FR2155TRSMT';
UPDATE orderable SET pinset_id = 26 WHERE name = 'MSP430FR2353TRSMR';
UPDATE orderable SET pinset_id = 26 WHERE name = 'MSP430FR2353TRSMT';
UPDATE orderable SET pinset_id = 26 WHERE name = 'MSP430FR2355TRSMR';
UPDATE orderable SET pinset_id = 26 WHERE name = 'MSP430FR2355TRSMT';

COMMIT TRANSACTION;
