--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5947' , 'SLAS704', 16, 32768, 1024, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59471', 'SLAS704', 16, 32768, 1024, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5948' , 'SLAS704', 16, 49152, 2048, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5949' , 'SLAS704', 16, 65536, 2048, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5957' , 'SLAS704', 16, 32768, 1024, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5958' , 'SLAS704', 16, 49152, 2048, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5959' , 'SLAS704', 16, 65536, 2048, 33, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5967' , 'SLAS704', 16, 32768, 1024, 40, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5968' , 'SLAS704', 16, 49152, 2048, 40, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5969' , 'SLAS704', 16, 65536, 2048, 40, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59691', 'SLAS704', 16, 65536, 2048, 40, 2, 0, 1, 3, 16, 5, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5947' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5947' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5947' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59471', 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59471', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59471', 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5948' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5948' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5948' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5949' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5949' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5949' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5957' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5957' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5957' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5958' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5958' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5958' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5959' , 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5959' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5959' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5967' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5967' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5967' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5968' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5968' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5968' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5969' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5969' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5969' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59691', 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59691', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59691', 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59471IRHAR', 'MSP430FR59471', 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59471IRHAT', 'MSP430FR59471', 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5947IDA'   , 'MSP430FR5947' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5947IDAR'  , 'MSP430FR5947' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5947IRHAR' , 'MSP430FR5947' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5947IRHAT' , 'MSP430FR5947' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5948IDA'   , 'MSP430FR5948' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5948IDAR'  , 'MSP430FR5948' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5948IRHAR' , 'MSP430FR5948' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5948IRHAT' , 'MSP430FR5948' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5949IDA'   , 'MSP430FR5949' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5949IDAR'  , 'MSP430FR5949' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5949IRHAR' , 'MSP430FR5949' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5949IRHAT' , 'MSP430FR5949' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5957IDA'   , 'MSP430FR5957' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5957IDAR'  , 'MSP430FR5957' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5957IRHAR' , 'MSP430FR5957' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5957IRHAT' , 'MSP430FR5957' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5958IDA'   , 'MSP430FR5958' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5958IDAR'  , 'MSP430FR5958' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5958IRHAR' , 'MSP430FR5958' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5958IRHAT' , 'MSP430FR5958' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5959IDA'   , 'MSP430FR5959' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5959IDAR'  , 'MSP430FR5959' , 'DA' , 38, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5959IRHAR' , 'MSP430FR5959' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5959IRHAT' , 'MSP430FR5959' , 'RHA', 40, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5967IRGZR' , 'MSP430FR5967' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5967IRGZT' , 'MSP430FR5967' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5968IRGZR' , 'MSP430FR5968' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5968IRGZT' , 'MSP430FR5968' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59691IRGZR', 'MSP430FR59691', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59691IRGZT', 'MSP430FR59691', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5969IRGZR' , 'MSP430FR5969' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5969IRGZT' , 'MSP430FR5969' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (49, NULL, 0, 38, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (50, NULL, 0, 36, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (51, NULL, 0, 44, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (52,   51, 1,  3, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (53,   49, 2,  2, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (54,   50, 2,  2, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (55,   49, 1,  3, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (56,   50, 1,  3, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (508, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (556,  508,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (509, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (510, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (511, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (512, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (513, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (514, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (515, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (516, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (517, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (518, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (519, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (520, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (521, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (522, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (523, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (524, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (525, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (526, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (527, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (528, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (529, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (530, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (531, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (532, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (533, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (534, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (535, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (536, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (537, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (538, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (539, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (540, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (541, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (542, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (543, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (544, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (545, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (546, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (547, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (548, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (554, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (555, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (549, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (552, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (553, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (550, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (551, NULL, 47);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 508, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 508, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 508, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (52, 556, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (55, 556, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (56, 556, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 509, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 509, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 509, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 510, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 510, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 510, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 511, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 511, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 511, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 512, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 512, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 512, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 513, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 513, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 513, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 514, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 514, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 514, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 515, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 516, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 516, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 516, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 517, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 517, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 517, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 518, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 518, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 518, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 519, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 519, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 519, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 520, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 520, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 520, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 521, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 521, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 521, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 522, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 522, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 522, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 523, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 523, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 524, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 524, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 525, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 526, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 527, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 527, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 527, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 528, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 528, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 528, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 529, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 529, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 529, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 530, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 530, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 530, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 531, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 531, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 531, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 532, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 532, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 532, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 533, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 533, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 533, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 534, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 534, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 534, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 535, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 535, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 535, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 536, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 536, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 536, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 537, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 537, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 537, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 538, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 538, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 538, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 539, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 539, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 539, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 540, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 540, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 540, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 541, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 542, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 543, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 543, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 543, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 544, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 544, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 544, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 545, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 545, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 545, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 546, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 546, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 546, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 547, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 547, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 547, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 548, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 548, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 548, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (53, 554, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (54, 554, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (53, 555, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (54, 555, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 549, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (52, 552, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (55, 552, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (56, 552, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (52, 553, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (55, 553, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (56, 553, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 550, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 550, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 550, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (49, 551, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (50, 551, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (51, 551, NULL, 48);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 2, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (556, 3, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 5, 'C0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 6, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (508, 7, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 5, 'C1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 6, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (509, 7, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 2, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (510, 5, 'C2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (511, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (511, 1, 'A12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (511, 2, 'C12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (512, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (512, 1, 'A13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (512, 2, 'C13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (513, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (513, 1, 'A14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (513, 2, 'C14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (514, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (514, 1, 'A15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (514, 2, 'C15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (515, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (516, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (516, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (516, 2, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (516, 3, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (516, 4, 'C3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (517, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (517, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (517, 2, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (517, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (517, 4, 'C4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (518, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (518, 1, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (518, 2, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (518, 3, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (518, 4, 'C5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 2, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 3, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 4, 'SRSCG1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (519, 5, 'C6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 4, 'SRSCG0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (520, 5, 'C7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (521, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (521, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (521, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (521, 3, 'SROSCOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (521, 4, 'C8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (522, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (522, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (522, 2, 'SRCPUOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (522, 3, 'C9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (523, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (523, 1, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (524, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (524, 1, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (525, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (525, 1, 'A10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (526, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (526, 1, 'A11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (527, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (527, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (527, 2, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (527, 3, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (528, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (528, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (528, 2, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (528, 3, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (529, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (529, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (530, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (530, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (530, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 2, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 3, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 4, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (531, 5, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (532, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (532, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (532, 2, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (532, 3, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (533, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (533, 1, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (533, 2, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (534, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (534, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (534, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (535, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (535, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (535, 2, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (536, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (536, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (537, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (537, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (538, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (538, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (538, 2, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (538, 3, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (538, 4, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (539, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (539, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (539, 2, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (539, 3, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (539, 4, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (540, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (540, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (541, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (542, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (543, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (544, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (545, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (546, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (546, 1, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (546, 2, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (546, 3, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (546, 4, 'C10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (547, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (547, 1, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (547, 2, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (547, 3, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (547, 4, 'C11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (548, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (554, 0, 'PJ.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (554, 1, 'HFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (555, 0, 'PJ.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (555, 1, 'HFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (549, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (552, 0, 'PJ.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (552, 1, 'LFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (553, 0, 'PJ.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (553, 1, 'LFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (550, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (551, 0, 'AVCC'       );

UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5957IDA'   ;
UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5957IDAR'  ;
UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5958IDA'   ;
UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5958IDAR'  ;
UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5959IDA'   ;
UPDATE orderable SET pinset_id = 54 WHERE name = 'MSP430FR5959IDAR'  ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5947IDA'   ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5947IDAR'  ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5948IDA'   ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5948IDAR'  ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5949IDA'   ;
UPDATE orderable SET pinset_id = 56 WHERE name = 'MSP430FR5949IDAR'  ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5967IRGZR' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5967IRGZT' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5968IRGZR' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5968IRGZT' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5969IRGZR' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR5969IRGZT' ;
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR59691IRGZR';
UPDATE orderable SET pinset_id = 52 WHERE name = 'MSP430FR59691IRGZT';
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5957IRHAR' ;
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5957IRHAT' ;
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5958IRHAR' ;
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5958IRHAT' ;
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5959IRHAR' ;
UPDATE orderable SET pinset_id = 53 WHERE name = 'MSP430FR5959IRHAT' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5947IRHAR' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5947IRHAT' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR59471IRHAR';
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR59471IRHAT';
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5948IRHAR' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5948IRHAT' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5949IRHAR' ;
UPDATE orderable SET pinset_id = 55 WHERE name = 'MSP430FR5949IRHAT' ;

COMMIT TRANSACTION;
