--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5133', 'SLAS554', 20,  8192, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5135', 'SLAS554', 20, 16384, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5137', 'SLAS554', 20, 32768, 4096, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6125', 'SLAS554', 20, 16384, 2048, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6126', 'SLAS554', 20, 32768, 2048, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6127', 'SLAS554', 20, 32768, 4096, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6135', 'SLAS554', 20, 16384, 2048, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6137', 'SLAS554', 20, 32768, 4096, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5133', 'ADC_SAR12', '6' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5133', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5133', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5135', 'ADC_SAR12', '6' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5135', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5135', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5137', 'ADC_SAR12', '6' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5137', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5137', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6125', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6125', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6125', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6126', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6126', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6126', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6127', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6127', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6127', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6135', 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6135', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6135', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6137', 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6137', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6137', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5133IRGZ' , 'CC430F5133', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5133IRGZR', 'CC430F5133', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5133IRGZT', 'CC430F5133', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5135IRGZ' , 'CC430F5135', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5135IRGZR', 'CC430F5135', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5135IRGZT', 'CC430F5135', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5137IRGZ' , 'CC430F5137', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5137IRGZR', 'CC430F5137', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5137IRGZT', 'CC430F5137', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6125IRGCR', 'CC430F6125', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6126IRGCR', 'CC430F6126', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6127IRGCR', 'CC430F6127', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6127IRGCT', 'CC430F6127', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6135IRGCR', 'CC430F6135', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6137IRGCR', 'CC430F6137', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6137IRGCT', 'CC430F6137', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (33, NULL, 0, 48, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (34, NULL, 0, 64, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (35,   34, 1, 18, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (36,   35, 2,  8, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (37,   33, 3,  6, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (278, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (342,  278,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (279, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (343,  279,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (280, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (344,  280,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (281, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (282, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (283, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (284, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (285, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (286, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (287, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (288, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (289, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (345,  289, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (290, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (346,  290, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (291, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (347,  291, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (292, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (348,  292, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (293, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (349,  293, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (294, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (350,  294, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (295, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (351,  295, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (296, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (352,  296, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (297, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (353,  297, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (298, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (354,  298, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (299, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (355,  299, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (300, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (356,  300, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (301, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (357,  301, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (302, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (303, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (304, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (305, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (306, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (307, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (308, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (309, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (310, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (311, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (312, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (313, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (314, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (315, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (316, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (317, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (318, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (319, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (320, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (321, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (322, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (323, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (324, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (325, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (326, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (327, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (328, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (329, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (330, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (331, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (332, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (333, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (334, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (358,  334, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (366,  358, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (335, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (359,  335, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (367,  359, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (336, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (360,  336, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (368,  360, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (337, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (361,  337, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (369,  361, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (338, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (362,  338, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (370,  362, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (339, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (363,  339, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (371,  363, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (340, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (364,  340, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (372,  364, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (341, NULL, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (365,  341, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (373,  365, 63);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 278, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 278, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 342, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 279, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 279, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 343, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 280, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 280, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 344, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 281, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 282, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 283, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 284, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 285, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 286, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 287, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 287, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 288, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 288, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 289, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 289, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 345, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 290, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 290, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 346, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 291, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 291, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 347, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 292, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 292, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 348, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 293, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 293, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 349, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 294, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 294, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 350, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 295, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 295, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 351, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 296, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 296, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 352, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 297, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 297, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 353, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 298, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 298, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 354, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 299, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 299, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 355, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 300, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 300, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 356, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 301, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 301, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 357, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 302, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 302, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 303, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 304, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 305, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 306, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 307, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 308, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 309, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 310, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 311, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 312, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 313, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 313, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 314, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 314, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 315, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 315, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 316, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 316, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 317, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 317, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 318, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 318, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 319, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 319, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 320, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 320, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 321, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 321, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 322, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 322, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 323, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 323, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 324, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 324, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 325, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 325, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 326, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 326, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 327, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 327, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 328, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 328, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 329, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 329, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 330, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 330, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 331, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 331, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 332, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 332, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 333, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 333, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 334, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 334, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 358, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 366, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 335, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 335, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (35, 359, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 367, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 336, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 336, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 360, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 368, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 337, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 337, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 361, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 369, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 338, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 338, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 362, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 370, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 339, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 339, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 363, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 371, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 340, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 340, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 364, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 372, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (33, 341, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (34, 341, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (36, 365, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (37, 373, NULL,  3);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (278, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (278, 1, 'PM_UCA0CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (278, 2, 'PM_UCB0STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (342, 3, 'R03'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (279, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (279, 1, 'PM_UCA0TXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (279, 2, 'PM_UCA0SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (343, 3, 'R13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (343, 4, 'LCDREF'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (279, 5, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (280, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (280, 1, 'PM_UCA0RXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (280, 2, 'PM_UCA0SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (344, 3, 'R23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (280, 4, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (281, 0, 'LCDCAP'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (281, 1, 'R33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (282, 0, 'COM0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (283, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (283, 1, 'COM1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (283, 2, 'S26'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (284, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (284, 1, 'COM2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (284, 2, 'S25'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (285, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (285, 1, 'COM3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (285, 2, 'S24'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (286, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (286, 1, 'S23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (287, 0, 'VCORE'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (288, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (289, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (289, 1, 'PM_UCB0CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (289, 2, 'PM_UCA0STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (345, 3, 'S22'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (290, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (290, 1, 'PM_UCB0SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (290, 2, 'PM_UCB0SDA' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (346, 3, 'S21'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (291, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (291, 1, 'PM_UCB0SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (291, 2, 'PM_UCB0SCL' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (347, 3, 'S20'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (292, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (292, 1, 'PM_RFGDO2'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (348, 2, 'S19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (293, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (293, 1, 'PM_RFGDO0'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (349, 2, 'S18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (294, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (294, 1, 'PM_SMCLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (350, 2, 'S17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (295, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (295, 1, 'PM_RFGDO1'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (351, 2, 'S16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (296, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (296, 1, 'PM_TA0CCR4A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (352, 2, 'S15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (297, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (297, 1, 'PM_TA0CCR3A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (353, 2, 'S14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (298, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (298, 1, 'PM_TA0CCR2A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (354, 2, 'S13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (299, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (299, 1, 'PM_TA0CCR1A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (355, 2, 'S12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (300, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (300, 1, 'PM_TA0CCR0A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (356, 2, 'S11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (301, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (301, 1, 'PM_CBOUT0'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (301, 2, 'PM_TA0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (357, 3, 'S10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (302, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (303, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (303, 1, 'S9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (304, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (304, 1, 'S8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (305, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (305, 1, 'S7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (306, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (306, 1, 'S6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (307, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (307, 1, 'S5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (308, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (308, 1, 'S4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (309, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (309, 1, 'S3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (310, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (310, 1, 'S2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (311, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (311, 1, 'S1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (312, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (312, 1, 'S0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (313, 0, 'RF_XIN'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (314, 0, 'RF_XOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (315, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (316, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (317, 0, 'RF_P'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (318, 0, 'RF_N'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (319, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (320, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (321, 0, 'RBIAS'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (322, 0, 'GUARD'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (323, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (323, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (324, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (324, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (324, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (325, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (325, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (326, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (326, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (327, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (327, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (328, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (328, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (328, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (329, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (330, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (331, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (331, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (332, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (332, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (333, 0, 'AVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (334, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (334, 1, 'PM_ADC12CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (334, 2, 'PM_DMAE0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (358, 3, 'CB7'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (366, 4, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (335, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (335, 1, 'PM_ACLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (359, 2, 'CB6'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (367, 3, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (336, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (336, 1, 'PM_SVMOUT'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (336, 2, 'CB5'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (360, 3, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (360, 4, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (360, 5, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (368, 6, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (368, 7, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (368, 8, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (337, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (337, 1, 'PM_RTCCLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (337, 2, 'CB4'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (361, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (361, 4, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (361, 5, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (369, 6, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (369, 7, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (369, 8, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (338, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (338, 1, 'PM_TA1CCR2A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (338, 2, 'CB3'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (362, 3, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (370, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (339, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (339, 1, 'PM_TA1CCR1A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (339, 2, 'CB2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (363, 3, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (371, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (340, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (340, 1, 'PM_TA1CCR0A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (340, 2, 'CB1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (364, 3, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (372, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (341, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (341, 1, 'PM_CBOUT1'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (341, 2, 'PM_TA1CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (341, 3, 'CB0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (365, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (373, 5, 'A0'         );

UPDATE orderable SET pinset_id = 35 WHERE name = 'CC430F6125IRGCR';
UPDATE orderable SET pinset_id = 35 WHERE name = 'CC430F6126IRGCR';
UPDATE orderable SET pinset_id = 35 WHERE name = 'CC430F6127IRGCR';
UPDATE orderable SET pinset_id = 35 WHERE name = 'CC430F6127IRGCT';
UPDATE orderable SET pinset_id = 36 WHERE name = 'CC430F6135IRGCR';
UPDATE orderable SET pinset_id = 36 WHERE name = 'CC430F6137IRGCR';
UPDATE orderable SET pinset_id = 36 WHERE name = 'CC430F6137IRGCT';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5133IRGZ' ;
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5133IRGZR';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5133IRGZT';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5135IRGZ' ;
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5135IRGZR';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5135IRGZT';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5137IRGZ' ;
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5137IRGZR';
UPDATE orderable SET pinset_id = 37 WHERE name = 'CC430F5137IRGZT';

COMMIT TRANSACTION;
