--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5513', 'SLAS590', 25,  32768, 4096, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5514', 'SLAS590', 25,  65536, 4096, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5515', 'SLAS590', 25,  65536, 4096, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5517', 'SLAS590', 25,  98304, 6144, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5519', 'SLAS590', 25, 131072, 8192, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5521', 'SLAS590', 25,  32768, 6144, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5522', 'SLAS590', 25,  32768, 8192, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5524', 'SLAS590', 25,  65536, 4096, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5525', 'SLAS590', 25,  65536, 4096, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5526', 'SLAS590', 25,  98304, 6144, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5527', 'SLAS590', 25,  98304, 6144, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528', 'SLAS590', 25, 131072, 8192, 47, 2, 1, 2, 4,  8, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5529', 'SLAS590', 25, 131072, 8192, 63, 2, 1, 2, 4, 12, 4, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5513', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5513', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5514', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5514', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5515', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5515', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5517', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5517', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5519', 'ADC_SLOPE', '0' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5519', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5521', 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5521', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5522', 'ADC_SAR12', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5522', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5524', 'ADC_SAR12', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5524', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5525', 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5525', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5526', 'ADC_SAR12', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5526', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5527', 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5527', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5528', 'ADC_SAR12', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5528', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5529', 'ADC_SAR12', '14', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F5529', 'BSL_USB'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5513IRGCR', 'MSP430F5513', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5514IRGCR', 'MSP430F5514', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5514IRGCT', 'MSP430F5514', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5515IPN'  , 'MSP430F5515', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5515IPNR' , 'MSP430F5515', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5517IPN'  , 'MSP430F5517', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5517IPNR' , 'MSP430F5517', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5519IPN'  , 'MSP430F5519', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5519IPNR' , 'MSP430F5519', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5521IPN'  , 'MSP430F5521', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5521IPNR' , 'MSP430F5521', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5522IRGCR', 'MSP430F5522', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5522IRGCT', 'MSP430F5522', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5522IZXH' , 'MSP430F5522', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5522IZXHR', 'MSP430F5522', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5524IRGCR', 'MSP430F5524', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5524IRGCT', 'MSP430F5524', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5524IZXH' , 'MSP430F5524', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5524IZXHR', 'MSP430F5524', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5525IPN'  , 'MSP430F5525', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5525IPNR' , 'MSP430F5525', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5526IRGCR', 'MSP430F5526', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5526IRGCT', 'MSP430F5526', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5526IZXH' , 'MSP430F5526', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5526IZXHR', 'MSP430F5526', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5527IPN'  , 'MSP430F5527', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5527IPNR' , 'MSP430F5527', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528IRGCR', 'MSP430F5528', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528IRGCT', 'MSP430F5528', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528IYFFR', 'MSP430F5528', 'YFF', 64, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528IZXH' , 'MSP430F5528', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5528IZXHR', 'MSP430F5528', 'ZXH', 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5529IPN'  , 'MSP430F5529', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F5529IPNR' , 'MSP430F5529', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (62, NULL, 0, 64, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (63, NULL, 0, 80, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (64, NULL, 0, 80, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (65, NULL, 0, 64, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (66,   63, 1, 10, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (67,   62, 1,  6, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (68,   64, 1,  6, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (69,   65, 1,  6, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (646, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (742,  646,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (647, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (743,  647,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (648, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (744,  648,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (649, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (745,  649,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (650, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (746,  650,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (651, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (747,  651,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (652, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (748,  652,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (653, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (749,  653,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (654, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (750,  654,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (655, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (751,  655,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (656, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (657, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (658, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (659, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (660, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (661, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (662, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (663, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (664, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (665, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (666, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (667, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (668, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (669, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (670, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (671, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (672, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (673, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (674, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (675, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (676, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (677, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (678, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (679, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (680, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (681, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (682, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (683, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (684, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (685, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (686, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (687, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (688, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (689, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (690, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (691, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (692, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (693, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (694, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (695, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (696, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (697, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (698, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (699, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (700, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (701, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (702, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (703, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (704, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (705, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (706, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (707, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (708, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (709, NULL, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (710, NULL, 64);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (711, NULL, 65);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (712, NULL, 66);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (713, NULL, 67);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (714, NULL, 68);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (715, NULL, 69);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (716, NULL, 70);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (717, NULL, 71);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (718, NULL, 72);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (719, NULL, 73);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (720, NULL, 74);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (721, NULL, 75);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (722, NULL, 76);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (723, NULL, 77);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (724, NULL, 78);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (725, NULL, 79);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (726, NULL, 80);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (727, NULL, 81);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (728, NULL, 82);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (729, NULL, 83);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (730, NULL, 84);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (731, NULL, 85);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (732, NULL, 86);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (733, NULL, 87);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (734, NULL, 88);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (735, NULL, 89);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (736, NULL, 90);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (737, NULL, 91);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (738, NULL, 92);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (739, NULL, 93);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (740, NULL, 94);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (741, NULL, 95);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 646, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 646, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 646, 'C' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 646, 'B' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 742, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 742, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 742, 'C' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 742, 'B' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 647, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 647, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 647, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 647, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 743, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 743, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 743, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 743, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 648, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 648, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 648, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 648, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 744, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 744, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 744, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 744, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 649, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 649, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 649, 'D' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 649, 'C' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 745, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 745, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 745, 'D' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 745, 'C' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 650, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 746, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 651, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 747, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 652, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 748, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 653, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 749, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 654, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 654, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 654, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 654, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 750, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 750, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 750, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 750, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 655, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 655, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 655, 'E' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 655, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (66, 751, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (67, 751, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (68, 751, 'E' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (69, 751, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 656, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 656, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 656, 'F' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 656, 'A' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 657, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 657, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 657, 'F' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 657, 'A' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 658, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 658, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 658, 'G' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 658, 'A' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 659, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 659, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 659, 'G' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 659, 'A' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 660, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 661, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 662, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 663, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 663, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 663, 'H' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 663, 'A' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 664, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 664, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 664, 'J' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 664, 'A' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 665, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 665, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 665, 'J' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 665, 'B' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 666, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 666, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 666, 'H' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 666, 'B' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 667, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 667, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 667, 'H' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 667, 'B' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 668, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 668, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 668, 'J' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 668, 'C' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 669, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 669, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 669, 'G' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 669, 'C' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 670, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 670, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 670, 'H' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 670, 'C' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 671, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 671, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 671, 'J' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 671, 'D' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 672, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 672, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 672, 'G' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 672, 'D' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 673, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 673, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 673, 'H' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 673, 'D' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 674, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 674, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 674, 'J' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 674, 'E' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 675, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 675, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 675, 'G' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 675, 'E' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 676, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 676, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 676, 'J' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 676, 'E' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 677, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 677, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 677, 'H' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 677, 'E' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 678, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 678, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 678, 'J' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 678, 'F' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 679, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 679, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 679, 'J' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 679, 'F' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 680, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 680, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 680, 'J' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 680, 'F' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 681, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 681, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 681, 'H' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 681, 'H' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 682, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 682, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 682, 'H' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 682, 'G' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 683, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 683, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 683, 'H' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 683, 'H' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 684, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 684, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 684, 'G' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 684, 'G' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 685, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 685, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 685, 'G' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 685, 'G' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 686, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 686, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 686, 'G' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 686, 'G' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 687, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 688, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 689, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 690, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 690, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 690, 'E' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 690, 'F' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 691, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 691, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 691, 'E' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 691, 'H' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 692, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 692, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 692, 'D' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 692, 'G' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 693, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 693, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 693, 'D' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 693, 'F' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 694, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 694, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 694, 'F' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 694, 'H' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 695, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 695, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 695, 'E' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 695, 'H' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 696, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 696, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 696, 'D' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 696, 'H' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 697, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 697, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 697, 'C' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 697, 'G' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 698, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 698, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 698, 'C' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 698, 'F' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 699, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 699, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 699, 'C' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 699, 'E' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 700, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 701, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 702, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 703, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 704, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 705, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 706, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 706, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 706, 'B' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 706, 'H' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 707, 'B' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 708, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 708, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 708, 'A' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 708, 'H' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 709, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 709, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 709, 'B' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 709, 'G' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 710, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 710, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 710, 'A' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 710, 'G' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 711, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 711, NULL, 65);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 711, 'A' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 711, 'F' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 712, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 712, NULL, 66);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 712, 'A' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 712, 'F' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 713, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 713, NULL, 67);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 713, 'B' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 713, 'E' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 714, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 714, NULL, 68);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 714, 'A' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 714, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 715, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 715, NULL, 69);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 715, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 715, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 716, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 716, NULL, 70);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 716, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 716, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 717, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 717, NULL, 71);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 717, 'A' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 717, 'E' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 718, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 718, NULL, 72);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 718, 'C' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 718, 'D' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 719, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 719, NULL, 73);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 719, 'C' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 719, 'D' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 720, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 720, NULL, 74);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 720, 'A' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 720, 'C' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 721, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 721, NULL, 75);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 721, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 721, 'C' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 722, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 722, NULL, 76);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 722, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 722, 'D' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 723, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 723, NULL, 77);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 723, 'A' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 723, 'B' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 724, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 724, NULL, 78);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 724, 'B' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 724, 'C' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 725, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 725, NULL, 79);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 725, 'B' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 725, 'A' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (62, 726, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (63, 726, NULL, 80);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 726, 'C' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (65, 726, 'C' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 727, 'C' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 728, 'D' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 729, 'D' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 730, 'D' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 731, 'E' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 732, 'E' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 733, 'E' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 734, 'E' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 735, 'F' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 736, 'F' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 737, 'F' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 738, 'F' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 739, 'F' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 740, 'F' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (64, 741, 'G' ,  3);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (646, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (646, 1, 'CB4'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (742, 2, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (647, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (647, 1, 'CB5'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (743, 2, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (648, 0, 'P6.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (648, 1, 'CB6'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (744, 2, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (649, 0, 'P6.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (649, 1, 'CB7'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (745, 2, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (650, 0, 'P7.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (650, 1, 'CB8'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (746, 2, 'A12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (651, 0, 'P7.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (651, 1, 'CB9'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (747, 2, 'A13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (652, 0, 'P7.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (652, 1, 'CB10'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (748, 2, 'A14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (653, 0, 'P7.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (653, 1, 'CB11'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (749, 2, 'A15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (654, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (750, 1, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (750, 2, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (750, 3, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (655, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (751, 1, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (751, 2, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (751, 3, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (656, 0, 'AVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (657, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (657, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (658, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (658, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (659, 0, 'AVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (660, 0, 'P8.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (661, 0, 'P8.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (662, 0, 'P8.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (663, 0, 'DVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (664, 0, 'DVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (665, 0, 'VCORE'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (666, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (666, 1, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (666, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (667, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (667, 1, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (667, 2, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (668, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (668, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (668, 2, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (669, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (669, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (670, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (670, 1, 'TA0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (671, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (671, 1, 'TA0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (672, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (672, 1, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (672, 2, 'CBOUT'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (673, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (673, 1, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (674, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (674, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (675, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (675, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (676, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (676, 1, 'TA2CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (676, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (677, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (677, 1, 'TA2.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (678, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (678, 1, 'TA2.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (679, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (679, 1, 'TA2.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (680, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (680, 1, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (680, 2, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (681, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (681, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (681, 2, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (682, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (682, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (682, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (683, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (683, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (683, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (684, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (684, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (684, 2, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (685, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (685, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (685, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (686, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (686, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (686, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (687, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (687, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (688, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (688, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (689, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (689, 1, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (689, 2, 'SVMOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (690, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (690, 1, 'PM_UCB1STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (690, 2, 'PM_UCA1CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (691, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (691, 1, 'PM_UCB1SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (691, 2, 'PM_UCB1SDA' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (692, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (692, 1, 'PM_UCB1SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (692, 2, 'PM_UCB1SCL' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (693, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (693, 1, 'PM_UCB1CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (693, 2, 'PM_UCA1STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (694, 0, 'DVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (695, 0, 'DVCC2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (696, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (696, 1, 'PM_UCA1TXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (696, 2, 'PM_UCA1SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (697, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (697, 1, 'PM_UCA1RXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (697, 2, 'PM_UCA1SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (698, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (698, 1, 'PM_NONE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (699, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (699, 1, 'PM_NONE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (700, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (700, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (701, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (701, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (702, 0, 'P7.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (702, 1, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (703, 0, 'P7.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (703, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (704, 0, 'P7.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (704, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (705, 0, 'P7.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (705, 1, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (705, 2, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (706, 0, 'VSSU'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (707, 0, 'VSSU'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (708, 0, 'PU.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (708, 1, 'DP'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (709, 0, 'PUR'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (710, 0, 'PU.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (710, 1, 'DM'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (711, 0, 'VBUS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (712, 0, 'VUSB'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (713, 0, 'V18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (714, 0, 'AVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (715, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (715, 1, 'XT2IN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (716, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (716, 1, 'XT2OUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (717, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (717, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (718, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (718, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (719, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (719, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (719, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (720, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (720, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (721, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (721, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (722, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (722, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (722, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (723, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (723, 1, 'CB0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (723, 2, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (724, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (724, 1, 'CB1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (724, 2, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (725, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (725, 1, 'CB2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (725, 2, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (726, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (726, 1, 'CB3'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (726, 2, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (727, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (728, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (729, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (730, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (731, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (732, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (733, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (734, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (735, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (736, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (737, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (738, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (739, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (740, 0, 'RESERVED'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (741, 0, 'RESERVED'   );

UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5515IPN'  ;
UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5515IPNR' ;
UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5517IPN'  ;
UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5517IPNR' ;
UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5519IPN'  ;
UPDATE orderable SET pinset_id = 63 WHERE name = 'MSP430F5519IPNR' ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5521IPN'  ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5521IPNR' ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5525IPN'  ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5525IPNR' ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5527IPN'  ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5527IPNR' ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5529IPN'  ;
UPDATE orderable SET pinset_id = 66 WHERE name = 'MSP430F5529IPNR' ;
UPDATE orderable SET pinset_id = 62 WHERE name = 'MSP430F5513IRGCR';
UPDATE orderable SET pinset_id = 62 WHERE name = 'MSP430F5514IRGCR';
UPDATE orderable SET pinset_id = 62 WHERE name = 'MSP430F5514IRGCT';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5522IRGCR';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5522IRGCT';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5524IRGCR';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5524IRGCT';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5526IRGCR';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5526IRGCT';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5528IRGCR';
UPDATE orderable SET pinset_id = 67 WHERE name = 'MSP430F5528IRGCT';
UPDATE orderable SET pinset_id = 69 WHERE name = 'MSP430F5528IYFFR';
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5522IZXH' ;
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5522IZXHR';
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5524IZXH' ;
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5524IZXHR';
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5526IZXH' ;
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5526IZXHR';
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5528IZXH' ;
UPDATE orderable SET pinset_id = 68 WHERE name = 'MSP430F5528IZXHR';

COMMIT TRANSACTION;
