--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F155' , 'SLAS368', 8, 16384,   512, 48, 1, 0, 1, 1, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F156' , 'SLAS368', 8, 24576,  1024, 48, 1, 0, 1, 1, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F157' , 'SLAS368', 8, 32768,  1024, 48, 1, 0, 1, 1, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1610', 'SLAS368', 8, 32768,  5120, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1611', 'SLAS368', 8, 49152, 10240, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1612', 'SLAS368', 8, 56320,  5120, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F167' , 'SLAS368', 8, 32768,  1024, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F168' , 'SLAS368', 8, 49152,  2048, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F169' , 'SLAS368', 8, 61440,  2048, 48, 2, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F155' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F155' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F155' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F156' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F156' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F156' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F157' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F157' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F157' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1610', 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1610', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1610', 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1611', 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1611', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1611', 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1612', 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1612', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F1612', 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F167' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F167' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F167' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F168' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F168' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F168' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F169' , 'ADC_SAR12', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F169' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430F169' , 'BOD'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F155IPM'   , 'MSP430F155' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F155IPMR'  , 'MSP430F155' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F155IRTDR' , 'MSP430F155' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F155IRTDT' , 'MSP430F155' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F156IPM'   , 'MSP430F156' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F156IPMR'  , 'MSP430F156' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F156IRTDR' , 'MSP430F156' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F156IRTDT' , 'MSP430F156' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F157IPM'   , 'MSP430F157' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F157IPMR'  , 'MSP430F157' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F157IRTDT' , 'MSP430F157' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1610IPM'  , 'MSP430F1610', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1610IPMR' , 'MSP430F1610', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1610IRTDR', 'MSP430F1610', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1610IRTDT', 'MSP430F1610', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1611IPM'  , 'MSP430F1611', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1611IPMR' , 'MSP430F1611', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1611IRTDR', 'MSP430F1611', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1611IRTDT', 'MSP430F1611', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1612IPM'  , 'MSP430F1612', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1612IPMR' , 'MSP430F1612', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1612IRTDR', 'MSP430F1612', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1612IRTDT', 'MSP430F1612', 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F167IPM'   , 'MSP430F167' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F167IPMR'  , 'MSP430F167' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F167IRTDT' , 'MSP430F167' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F168IPM'   , 'MSP430F168' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F168IPMR'  , 'MSP430F168' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F168IRTDT' , 'MSP430F168' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F169IPM'   , 'MSP430F169' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F169IPMR'  , 'MSP430F169' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F169IRTDR' , 'MSP430F169' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F169IRTDT' , 'MSP430F169' , 'RTD', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (77, NULL, 0, 64, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (78,   77, 1, 10, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 937, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 938, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 939, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 940, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 941, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 942, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 943, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 944, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 945, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 946, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 947, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 948, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 949, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 950, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 951, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 952, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 953, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 954, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 955, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 956, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 957, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 958, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 959, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 960, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 961, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 962, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 963, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1001,  963, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 964, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1002,  964, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 965, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 966, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 967, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 968, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1003,  968, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 969, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1004,  969, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 970, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1005,  970, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 971, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1006,  971, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 972, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 973, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1007,  973, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 974, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1008,  974, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 975, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1009,  975, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 976, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1010,  976, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 977, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 978, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 979, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 980, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 981, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 982, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 983, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 984, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 985, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 986, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 987, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 988, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 989, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 990, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 991, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 992, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 993, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 994, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 995, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 996, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 997, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 998, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 999, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1000, NULL, 63);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  937, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  938, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  939, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  940, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  941, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  942, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  943, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  944, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  945, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  946, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  947, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  948, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  949, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  950, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  951, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  952, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  953, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  954, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  955, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  956, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  957, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  958, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  959, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  960, 'P' , 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  961, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  962, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  963, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1001, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  964, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1002, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  965, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  966, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  967, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  968, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1003, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  969, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1004, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  970, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1005, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  971, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1006, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  972, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  973, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1007, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  974, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1008, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  975, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1009, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  976, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (78, 1010, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  977, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  978, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  979, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  980, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  981, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  982, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  983, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  984, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  985, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  986, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  987, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  988, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  989, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  990, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  991, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  992, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  993, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  994, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  995, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  996, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  997, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  998, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77,  999, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 1000, NULL, 52);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 937, 0, 'AVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 938, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 939, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 940, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 941, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 941, 1, 'TACLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 942, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 942, 1, 'TA0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 943, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 943, 1, 'TA1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 944, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 944, 1, 'TA2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 945, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 945, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 946, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 946, 1, 'TA0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 947, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 947, 1, 'TA1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 948, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 948, 1, 'TA2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 949, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 949, 1, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 950, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 950, 1, 'TAINCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 951, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 951, 1, 'CAOUT'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 951, 2, 'TA0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 952, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 952, 1, 'CA0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 952, 2, 'TA1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 953, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 953, 1, 'CA1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 953, 2, 'TA2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 954, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 954, 1, 'ROSC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 955, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 955, 1, 'ADC12CLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 955, 2, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 956, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 956, 1, 'TA0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 957, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 957, 1, 'STE0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 958, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 958, 1, 'SIMO0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 958, 2, 'SDA'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 959, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 959, 1, 'SOMI0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 960, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 960, 1, 'UCLK0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 960, 2, 'SCL'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 961, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 961, 1, 'UTXD0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 962, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 962, 1, 'URXD0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 963, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1001, 1, 'UTXD1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 964, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1002, 1, 'URXD1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 965, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 965, 1, 'TB0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 966, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 966, 1, 'TB1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 967, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 967, 1, 'TB2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 968, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1003, 1, 'TB3'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 969, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1004, 1, 'TB4'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 970, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1005, 1, 'TB5'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 971, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1006, 1, 'TB6'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 972, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 972, 1, 'TBCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 973, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1007, 1, 'STE1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 974, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1008, 1, 'SIMO1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 975, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1009, 1, 'SOMI1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 976, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1010, 1, 'UCLK1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 977, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 977, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 978, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 978, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 979, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 979, 1, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 980, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 980, 1, 'TBOUTH'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 980, 2, 'SVSOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 981, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 981, 1, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 982, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 982, 1, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 983, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 983, 1, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 984, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 984, 1, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 985, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 985, 1, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 986, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 986, 1, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 987, 0, 'P6.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 987, 1, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 987, 2, 'DAC0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 988, 0, 'P6.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 988, 1, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 988, 2, 'DAC1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 988, 3, 'SVSIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 989, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 989, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 990, 0, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 991, 0, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 991, 1, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 992, 0, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 992, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 993, 0, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 994, 0, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 995, 0, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 996, 0, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 996, 1, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 997, 0, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 998, 0, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 999, 0, 'XT2IN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1000, 0, 'XT2OUT'     );

UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F155IPM'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F155IPMR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F156IPM'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F156IPMR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F157IPM'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F157IPMR'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1610IPM'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1610IPMR' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1611IPM'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1611IPMR' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1612IPM'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1612IPMR' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F167IPM'   ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F167IPMR'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F168IPM'   ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F168IPMR'  ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F169IPM'   ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F169IPMR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F155IRTDR' ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F155IRTDT' ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F156IRTDR' ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F156IRTDT' ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430F157IRTDT' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1610IRTDR';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1610IRTDT';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1611IRTDR';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1611IRTDT';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1612IRTDR';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F1612IRTDT';
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F167IRTDT' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F168IRTDT' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F169IRTDR' ;
UPDATE orderable SET pinset_id = 78 WHERE name = 'MSP430F169IRTDT' ;

COMMIT TRANSACTION;
