--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5962' , 'SLASE54', 16, 131072, 8192, 68, 4, 0, 4, 8, 16, 6, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5964' , 'SLASE54', 16, 262144, 8192, 68, 4, 0, 4, 8, 16, 6, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5992' , 'SLASE54', 16, 131072, 8192, 68, 4, 0, 4, 8, 16, 6, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994' , 'SLASE54', 16, 262144, 8192, 68, 4, 0, 4, 8, 16, 6, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941', 'SLASE54', 16, 262144, 8192, 68, 4, 0, 4, 8, 16, 6, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5962' , 'ADC_SAR12', '20', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5962' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5962' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5964' , 'ADC_SAR12', '20', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5964' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5964' , 'AES'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5992' , 'ADC_SAR12', '20', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5992' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5992' , 'DMA'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5994' , 'ADC_SAR12', '20', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5994' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5994' , 'DMA'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59941', 'ADC_SAR12', '20', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59941', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59941', 'DMA'      , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5962IPMR'  , 'MSP430FR5962' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5962IPNR'  , 'MSP430FR5962' , 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5962IRGZR' , 'MSP430FR5962' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5962IZVWR' , 'MSP430FR5962' , 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5964IPMR'  , 'MSP430FR5964' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5964IPNR'  , 'MSP430FR5964' , 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5964IRGZR' , 'MSP430FR5964' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5964IZVWR' , 'MSP430FR5964' , 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5992IPMR'  , 'MSP430FR5992' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5992IPNR'  , 'MSP430FR5992' , 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5992IRGZR' , 'MSP430FR5992' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5992IZVWR' , 'MSP430FR5992' , 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IPM'  , 'MSP430FR59941', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IPMR' , 'MSP430FR59941', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IPN'  , 'MSP430FR59941', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IPNR' , 'MSP430FR59941', 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IRGZR', 'MSP430FR59941', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IRGZT', 'MSP430FR59941', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IZVW' , 'MSP430FR59941', 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59941IZVWR', 'MSP430FR59941', 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IPM'   , 'MSP430FR5994' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IPMR'  , 'MSP430FR5994' , 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IPN'   , 'MSP430FR5994' , 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IPNR'  , 'MSP430FR5994' , 'PN' , 80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IRGZR' , 'MSP430FR5994' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IRGZT' , 'MSP430FR5994' , 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IZVW'  , 'MSP430FR5994' , 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5994IZVWR' , 'MSP430FR5994' , 'ZVW', 87, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (58, NULL, 64, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (59, NULL, 80, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (60, NULL, 48, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (61, NULL, 87, 0, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (559, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (560, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (561, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (562, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (563, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (564, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (565, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (566, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (567, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (568, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (569, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (570, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (571, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (572, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (573, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (574, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (575, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (576, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (577, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (578, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (579, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (580, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (581, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (582, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (583, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (584, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (585, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (586, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (587, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (588, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (589, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (590, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (591, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (592, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (593, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (594, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (595, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (596, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (597, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (598, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (599, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (600, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (601, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (602, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (603, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (604, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (605, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (606, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (607, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (608, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (609, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (610, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (611, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (612, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (613, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (614, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (615, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (616, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (617, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (618, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (619, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (620, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (621, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (622, NULL, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (623, NULL, 64);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (624, NULL, 65);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (625, NULL, 66);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (626, NULL, 67);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (627, NULL, 68);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (628, NULL, 69);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (629, NULL, 70);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (630, NULL, 71);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (631, NULL, 72);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (632, NULL, 73);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (633, NULL, 74);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (634, NULL, 75);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (635, NULL, 76);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (636, NULL, 77);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (637, NULL, 78);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (638, NULL, 79);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (639, NULL, 80);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (640, NULL, 81);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (645, NULL, 82);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (641, NULL, 83);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (642, NULL, 84);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (643, NULL, 85);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (644, NULL, 86);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 559, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 559, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 559, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 559, 'A' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 560, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 560, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 560, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 560, 'A' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 561, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 561, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 561, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 561, 'B' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 562, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 562, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 562, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 562, 'A' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 563, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 563, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 563, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 563, 'B' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 564, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 564, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 564, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 564, 'B' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 565, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 565, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 565, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 565, 'A' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 566, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 566, 'D' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 567, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 567, 'D' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 568, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 568, 'A' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 569, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 569, 'B' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 570, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 570, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 570, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 570, 'D' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 571, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 571, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 571, 'A' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 572, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 572, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 572, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 573, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 573, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 573, 'D' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 574, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 574, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 574, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 574, 'A' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 575, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 575, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 575, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 575, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 576, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 576, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 576, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 576, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 577, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 577, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 577, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 578, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 578, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 578, 'A' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 579, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 579, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 579, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 579, 'B' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 580, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 580, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 580, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 580, 'C' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 581, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 581, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 581, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 581, 'C' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 582, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 582, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 582, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 582, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 583, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 583, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 583, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 584, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 584, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 584, 'D' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 585, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 585, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 585, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 586, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 586, 'E' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 587, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 587, 'E' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 588, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 588, 'F' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 589, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 589, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 589, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 589, 'F' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 590, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 590, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 590, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 590, 'F' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 591, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 591, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 591, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 591, 'G' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 592, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 592, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 592, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 592, 'G' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 593, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 593, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 593, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 593, 'G' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 594, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 594, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 594, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 594, 'H' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 595, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 595, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 595, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 595, 'H' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 596, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 596, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 596, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 596, 'J' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 597, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 597, 'J' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 598, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 598, 'K' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 599, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 599, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 599, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 599, 'L' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 600, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 600, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 600, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 600, 'L' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 601, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 601, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 601, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 601, 'K' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 602, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 602, 'L' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 603, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 603, 'K' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 604, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 604, 'H' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 605, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 605, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 605, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 605, 'K' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 606, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 606, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 606, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 606, 'L' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 607, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 607, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 607, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 607, 'H' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 608, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 608, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 608, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 608, 'H' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 609, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 609, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 609, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 609, 'L' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 610, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 610, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 610, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 610, 'K' ,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 611, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 611, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 611, 'L' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 612, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 612, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 612, 'K' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 613, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 613, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 613, 'K' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 614, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 614, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 614, 'L' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 615, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 615, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 615, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 615, 'H' ,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 616, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 616, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 616, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 616, 'H' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 617, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 617, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 617, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 617, 'K' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 618, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 618, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 618, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 618, 'L' ,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 619, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 619, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 619, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 619, 'L' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 620, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 620, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 620, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 620, 'F' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 621, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 621, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 621, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 621, 'J' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 622, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 622, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 622, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 622, 'K' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 623, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 623, NULL, 65);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 623, 'J' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 624, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 624, NULL, 66);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 624, 'H' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 625, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 625, NULL, 67);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 625, 'G' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 626, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 626, NULL, 68);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 626, 'G' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 627, NULL, 69);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 627, 'F' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 628, NULL, 70);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 628, 'F' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 629, NULL, 71);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 629, 'E' ,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 630, NULL, 72);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 630, 'C' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 631, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 631, NULL, 73);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 631, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 631, 'E' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 632, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 632, NULL, 74);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 632, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 632, 'H' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 633, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 633, NULL, 75);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 633, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 633, 'G' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 634, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 634, NULL, 76);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 634, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 634, 'D' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 635, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 635, NULL, 77);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 635, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 635, 'E' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 636, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 636, NULL, 78);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 636, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 636, 'D' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 637, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 637, NULL, 79);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 637, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 637, 'C' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (58, 638, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (59, 638, NULL, 80);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (60, 638, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 638, 'B' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 639, 'A' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 640, 'A' , 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 645, 'B' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 641, 'K' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 642, 'K' , 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 643, 'L' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (61, 644, 'L' , 11);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 2, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 3, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 5, 'C0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 6, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (559, 7, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 5, 'C1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 6, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (560, 7, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 2, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (561, 5, 'C2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (562, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (562, 1, 'A12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (562, 2, 'C12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (563, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (563, 1, 'A13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (563, 2, 'C13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (564, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (564, 1, 'A14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (564, 2, 'C14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (565, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (565, 1, 'A15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (565, 2, 'C15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (566, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (566, 1, 'UCA3TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (566, 2, 'UCA3SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (567, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (567, 1, 'UCA3RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (567, 2, 'UCA3SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (568, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (568, 1, 'UCA3CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (569, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (569, 1, 'UCA3STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (570, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (571, 0, 'P7.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (571, 1, 'UCB2SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (571, 2, 'UCB2SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (572, 0, 'P7.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (572, 1, 'UCB2SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (572, 2, 'UCB2SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (573, 0, 'P8.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (574, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (574, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (574, 2, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (574, 3, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (574, 4, 'C3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (575, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (575, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (575, 2, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (575, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (575, 4, 'C4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (576, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (576, 1, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (576, 2, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (576, 3, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (576, 4, 'C5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (577, 0, 'DVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (578, 0, 'DVCC2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 2, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 3, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 4, 'SRSCG1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (579, 5, 'C6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 4, 'SRSCG0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (580, 5, 'C7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (581, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (581, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (581, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (581, 3, 'SROSCOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (581, 4, 'C8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (582, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (582, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (582, 2, 'SRCPUOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (582, 3, 'C9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (583, 0, 'P7.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (583, 1, 'UCB2CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (584, 0, 'P7.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (584, 1, 'UCB2STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (584, 2, 'TA4.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (585, 0, 'P7.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (585, 1, 'TA4.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (585, 2, 'A16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (586, 0, 'P7.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (586, 1, 'A17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (587, 0, 'P7.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (587, 1, 'A18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (588, 0, 'P7.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (588, 1, 'A19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (589, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (589, 1, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (590, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (590, 1, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (591, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (591, 1, 'A10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (592, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (592, 1, 'A11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (593, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (593, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (593, 2, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (593, 3, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (594, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (594, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (594, 2, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (594, 3, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (595, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (595, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (596, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (596, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (596, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (597, 0, 'DVSS3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (598, 0, 'DVCC3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 2, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 3, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 4, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 5, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (599, 6, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (600, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (600, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (600, 2, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (600, 3, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (600, 4, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (601, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (601, 1, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (601, 2, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (602, 0, 'P8.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (603, 0, 'P8.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (604, 0, 'P8.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (605, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (605, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (605, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (606, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (606, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (606, 2, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (607, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (607, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (608, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (608, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 2, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 3, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 4, 'BSLSDA'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (609, 5, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 2, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 3, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 4, 'BSLSCL'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (610, 5, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (611, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (611, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (611, 2, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (612, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (612, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (612, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (613, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (613, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (613, 2, 'TA4CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (614, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (614, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (615, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (615, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (616, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (617, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (618, 0, 'DVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (619, 0, 'DVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (620, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (621, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (621, 1, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (621, 2, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (621, 3, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (621, 4, 'C10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (622, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (622, 1, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (622, 2, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (622, 3, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (622, 4, 'C11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (623, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (623, 1, 'UCA2TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (623, 2, 'UCA2SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (623, 3, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (624, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (624, 1, 'UCA2RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (624, 2, 'UCA2SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (624, 3, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (625, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (625, 1, 'UCA2CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (625, 2, 'TA4.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (625, 3, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (626, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (626, 1, 'UCA2STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (626, 2, 'TA4.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (626, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (627, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (627, 1, 'UCB3SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (627, 2, 'UCB3SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (628, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (628, 1, 'UCB3SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (628, 2, 'UCB3SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (629, 0, 'P6.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (629, 1, 'UCB3CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (630, 0, 'P6.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (630, 1, 'UCB3STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (631, 0, 'AVSS3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (632, 0, 'PJ.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (632, 1, 'HFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (633, 0, 'PJ.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (633, 1, 'HFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (634, 0, 'AVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (635, 0, 'PJ.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (635, 1, 'LFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (636, 0, 'PJ.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (636, 1, 'LFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (637, 0, 'AVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (638, 0, 'AVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (639, 0, 'DGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (640, 0, 'AGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (645, 0, 'AGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (641, 0, 'DGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (642, 0, 'DGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (643, 0, 'DGND'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (644, 0, 'DGND'       );

UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR5962IPMR'  ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR5964IPMR'  ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR5992IPMR'  ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR5994IPM'   ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR5994IPMR'  ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR59941IPM'  ;
UPDATE orderable SET pinset_id = 58 WHERE name = 'MSP430FR59941IPMR' ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR5962IPNR'  ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR5964IPNR'  ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR5992IPNR'  ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR5994IPN'   ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR5994IPNR'  ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR59941IPN'  ;
UPDATE orderable SET pinset_id = 59 WHERE name = 'MSP430FR59941IPNR' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR5962IRGZR' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR5964IRGZR' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR5992IRGZR' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR5994IRGZR' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR5994IRGZT' ;
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR59941IRGZR';
UPDATE orderable SET pinset_id = 60 WHERE name = 'MSP430FR59941IRGZT';
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR5962IZVWR' ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR5964IZVWR' ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR5992IZVWR' ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR5994IZVW'  ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR5994IZVWR' ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR59941IZVW' ;
UPDATE orderable SET pinset_id = 61 WHERE name = 'MSP430FR59941IZVWR';

COMMIT TRANSACTION;
