--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2433', 'SLASE59', 16, 16384, 4096, 19, 2, 0, 1, 2, 0, 4, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2433', 'ADC_SAR10', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2433', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2433', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2433IRGER', 'MSP430FR2433', 'RGE', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2433IRGET', 'MSP430FR2433', 'RGE', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2433IYQWR', 'MSP430FR2433', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2433IYQWT', 'MSP430FR2433', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (17, NULL, 24, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (18, NULL, 22, 0, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (189, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (190, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (191, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (192, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (193, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (194, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (195, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (196, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (197, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (198, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (199, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (200, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (201, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (202, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (203, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (204, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (205, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (206, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (207, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (208, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (209, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (210, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (211, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (212, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (213, NULL, 24);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 189, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 189, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 190, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 190, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 191, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 191, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 192, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 192, 'C' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 193, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 193, 'C' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 194, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 194, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 195, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 195, 'B' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 196, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 196, 'A' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 197, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 197, 'B' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 198, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 198, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 199, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 199, 'A' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 200, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 200, 'A' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 201, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 201, 'A' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 202, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 203, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 204, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 204, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 205, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 205, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 206, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 207, 'C' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 208, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 208, 'E' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 209, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 209, 'D' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 210, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 210, 'E' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 211, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 211, 'E' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 212, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 212, 'D' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (17, 213, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (18, 213, 'E' ,  2);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (189, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (189, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (189, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (190, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (190, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 3, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 4, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 5, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 6, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (191, 7, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 3, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 4, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 5, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (192, 6, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 3, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 4, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (193, 5, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (194, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (194, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (194, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (194, 3, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (194, 4, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (195, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (195, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (195, 2, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (195, 3, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (195, 4, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (196, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (196, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (196, 2, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (196, 3, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 3, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 5, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (197, 6, 'BSLSDA'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (198, 5, 'BSLSCL'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (199, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (199, 1, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (200, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (201, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (202, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (202, 1, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (203, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (203, 1, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (204, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (204, 1, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (204, 2, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (205, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (205, 1, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (205, 2, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (206, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (207, 0, 'NC'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (208, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (209, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (210, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (210, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (211, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (211, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (212, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (213, 0, 'DVCC'       );

UPDATE orderable SET pinset_id = 17 WHERE name = 'MSP430FR2433IRGER';
UPDATE orderable SET pinset_id = 17 WHERE name = 'MSP430FR2433IRGET';
UPDATE orderable SET pinset_id = 18 WHERE name = 'MSP430FR2433IYQWR';
UPDATE orderable SET pinset_id = 18 WHERE name = 'MSP430FR2433IYQWT';

COMMIT TRANSACTION;
