--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310', 'SLASE58', 16, 2048, 1024, 16, 1, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311', 'SLASE58', 16, 4096, 1024, 16, 1, 0, 1, 2, 2, 2, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2310', 'ADC_SAR10', '8', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2310', 'BSL_I2C', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2310', 'OP_AMP', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2311', 'ADC_SAR10', '8', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2311', 'BSL_I2C', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2311', 'OP_AMP', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IPW16' , 'MSP430FR2310', 'PW' ,  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IPW16R', 'MSP430FR2310', 'PW' ,  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IPW20' , 'MSP430FR2310', 'PW' ,  20, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IPW20R', 'MSP430FR2310', 'PW' ,  20, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IRGYR' , 'MSP430FR2310', 'RGY',  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2310IRGYT' , 'MSP430FR2310', 'RGY',  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IPW16' , 'MSP430FR2311', 'PW' ,  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IPW16R', 'MSP430FR2311', 'PW' ,  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IPW20' , 'MSP430FR2311', 'PW' ,  20, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IPW20R', 'MSP430FR2311', 'PW' ,  20, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IRGYR' , 'MSP430FR2311', 'RGY',  16, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2311IRGYT' , 'MSP430FR2311', 'RGY',  16, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  42, NULL,  16, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  43, NULL,  20, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  44, NULL,  16, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  45,   43,   1, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  46,   44,   1, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  438,  NULL,   0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  439,  NULL,   1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  440,  NULL,   2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  441,  NULL,   3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  442,  NULL,   4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  443,  NULL,   5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  444,  NULL,   6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  445,  NULL,   7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  446,  NULL,   8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  447,  NULL,   9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  448,  NULL,  10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  449,  NULL,  11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  450,  NULL,  12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  451,  NULL,  13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  452,  NULL,  14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  453,  NULL,  15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  459,   453,  15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  454,  NULL,  16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  455,  NULL,  17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  456,  NULL,  18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  457,  NULL,  19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  458,  NULL,  20);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   438, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   438, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   438, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   439, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   439, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   439, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   440, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   440, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   440, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   441, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   441, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   441, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   442, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   442, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   442, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   443, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   443, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   443, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   444, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   444, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   444, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   445, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   445, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   445, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   446, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   447, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   448, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   449, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   450, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   450, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   451, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   451, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   451, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   452, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   452, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   452, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   453, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   453, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   453, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  45,   459, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  46,   459, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   454, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   455, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   455, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   455, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   456, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   456, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   456, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   457, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   457, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   457, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  42,   458, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  43,   458, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  44,   458, NULL,  16);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  438, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  438, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  438, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  438, 3, 'C1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  438, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 3, 'C0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  439, 5, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  440, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  440, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  441, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  441, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  441, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  442, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  443, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  444, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  444, 1, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  444, 2, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  445, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  445, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  445, 2, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  446, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  446, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  446, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  447, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  447, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  447, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  448, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  448, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  448, 2, 'TB1TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  449, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  449, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  449, 2, 'TB1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  450, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  450, 1, 'TB1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  451, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  451, 1, 'TB1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  451, 2, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 3, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 4, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 5, 'TRI0+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 6, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  452, 7, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 3, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 4, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 5, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  459, 6, 'TRI0-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  453, 7, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  454, 0, 'TRI0-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  455, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  455, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  455, 2, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  455, 3, 'TRI0O'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  455, 4, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  456, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  456, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  456, 2, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  456, 3, 'OA0+'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  456, 4, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  457, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  457, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  457, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  457, 3, 'OA0O'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  457, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 3, 'TB0TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 4, 'OA0-'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 5, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  458, 6, 'VEREF-'     );

UPDATE orderable SET pinset_id =   42 WHERE name = 'MSP430FR2310IPW16';
UPDATE orderable SET pinset_id =   42 WHERE name = 'MSP430FR2310IPW16R';
UPDATE orderable SET pinset_id =   42 WHERE name = 'MSP430FR2311IPW16';
UPDATE orderable SET pinset_id =   42 WHERE name = 'MSP430FR2311IPW16R';
UPDATE orderable SET pinset_id =   45 WHERE name = 'MSP430FR2310IPW20';
UPDATE orderable SET pinset_id =   45 WHERE name = 'MSP430FR2310IPW20R';
UPDATE orderable SET pinset_id =   45 WHERE name = 'MSP430FR2311IPW20';
UPDATE orderable SET pinset_id =   45 WHERE name = 'MSP430FR2311IPW20R';
UPDATE orderable SET pinset_id =   46 WHERE name = 'MSP430FR2310IRGYR';
UPDATE orderable SET pinset_id =   46 WHERE name = 'MSP430FR2310IRGYT';
UPDATE orderable SET pinset_id =   46 WHERE name = 'MSP430FR2311IRGYR';
UPDATE orderable SET pinset_id =   46 WHERE name = 'MSP430FR2311IRGYT';

COMMIT TRANSACTION;
