--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5123', 'SLAS555', 20,  8192, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5125', 'SLAS555', 20, 16384, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5143', 'SLAS555', 20,  8192, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5145', 'SLAS555', 20, 16384, 2048, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F5147', 'SLAS555', 20, 32768, 4096, 30, 1, 0, 1, 1, 6, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6143', 'SLAS555', 20,  8192, 2048, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6145', 'SLAS555', 20, 16384, 2048, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('CC430F6147', 'SLAS555', 20, 32768, 4096, 44, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5123', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5123', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5125', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5125', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5143', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5143', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5145', 'ADC_SAR10', '6' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5145', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5145', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5147', 'ADC_SAR10', '6' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5147', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F5147', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6143', 'ADC_SAR10', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6143', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6143', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6145', 'ADC_SAR10', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6145', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6145', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6147', 'ADC_SAR10', '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6147', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('CC430F6147', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5123IRGZR', 'CC430F5123', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5123IRGZT', 'CC430F5123', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5125IRGZR', 'CC430F5125', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5125IRGZT', 'CC430F5125', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5143IRGZR', 'CC430F5143', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5143IRGZT', 'CC430F5143', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5145IRGZR', 'CC430F5145', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5145IRGZT', 'CC430F5145', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5147IRGZR', 'CC430F5147', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F5147IRGZT', 'CC430F5147', 'RGZ', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6147IRGCR', 'CC430F6147', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('CC430F6147IRGCT', 'CC430F6147', 'RGC', 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (79, NULL, 0, 48, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (80, NULL, 0, 64, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (81,   80, 1, 18, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (82,   81, 2,  8, NULL);
INSERT INTO pinset (id, parent_id, group_idx, pins, comment) VALUES (83,   79, 3,  6, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1011, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1075, 1011,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1012, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1076, 1012,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1013, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1077, 1013,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1014, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1015, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1016, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1017, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1018, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1019, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1020, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1021, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1022, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1078, 1022, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1023, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1079, 1023, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1024, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1080, 1024, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1025, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1081, 1025, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1026, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1082, 1026, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1027, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1083, 1027, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1028, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1084, 1028, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1029, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1085, 1029, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1030, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1086, 1030, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1031, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1087, 1031, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1032, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1088, 1032, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1033, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1089, 1033, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1034, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1090, 1034, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1035, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1036, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1037, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1038, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1039, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1040, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1041, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1042, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1043, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1044, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1045, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1046, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1047, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1048, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1049, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1050, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1051, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1052, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1053, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1054, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1055, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1056, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1057, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1058, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1059, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1060, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1061, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1062, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1063, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1064, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1065, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1066, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1067, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1091, 1067, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1099, 1091, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1068, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1092, 1068, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1100, 1092, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1069, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1093, 1069, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1101, 1093, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1070, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1094, 1070, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1102, 1094, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1071, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1095, 1071, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1103, 1095, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1072, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1096, 1072, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1104, 1096, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1073, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1097, 1073, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1105, 1097, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1074, NULL, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1098, 1074, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (1106, 1098, 63);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1011, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1011, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1075, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1012, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1012, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1076, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1013, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1013, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1077, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1014, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1015, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1016, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1017, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1018, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1019, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1020, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1020, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1021, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1021, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1022, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1022, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1078, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1023, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1023, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1079, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1024, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1024, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1080, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1025, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1025, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1081, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1026, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1026, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1082, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1027, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1027, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1083, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1028, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1028, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1084, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1029, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1029, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1085, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1030, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1030, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1086, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1031, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1031, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1087, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1032, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1032, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1088, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1033, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1033, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1089, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1034, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1034, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1090, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1035, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1035, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1036, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1037, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1038, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1039, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1040, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1041, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1042, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1043, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1044, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1045, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1046, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1046, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1047, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1047, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1048, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1048, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1049, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1049, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1050, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1050, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1051, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1051, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1052, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1052, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1053, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1053, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1054, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1054, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1055, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1055, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1056, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1056, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1057, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1057, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1058, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1058, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1059, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1059, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1060, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1060, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1061, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1061, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1062, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1062, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1063, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1063, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1064, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1064, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1065, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1065, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1066, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1066, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1067, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1067, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1091, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1099, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1068, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1068, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (81, 1092, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1100, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1069, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1069, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1093, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1101, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1070, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1070, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1094, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1102, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1071, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1071, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1095, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1103, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1072, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1072, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1096, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1104, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1073, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1073, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1097, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1105, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (79, 1074, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (80, 1074, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (82, 1098, NULL, 64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (83, 1106, NULL,  3);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1011, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1011, 1, 'PM_UCA0CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1011, 2, 'PM_UCB0STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1075, 3, 'R03'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1012, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1012, 1, 'PM_UCA0TXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1012, 2, 'PM_UCA0SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1076, 3, 'R13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1076, 4, 'LCDREF'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1012, 5, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1013, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1013, 1, 'PM_UCA0RXD' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1013, 2, 'PM_UCA0SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1077, 3, 'R23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1013, 4, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1014, 0, 'LCDCAP'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1014, 1, 'R33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1015, 0, 'COM0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1016, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1016, 1, 'COM1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1016, 2, 'S26'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1017, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1017, 1, 'COM2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1017, 2, 'S25'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1018, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1018, 1, 'COM3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1018, 2, 'S24'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1019, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1019, 1, 'S23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1020, 0, 'VCORE'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1021, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1022, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1022, 1, 'PM_UCB0CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1022, 2, 'PM_UCA0STE' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1078, 3, 'S22'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1023, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1023, 1, 'PM_UCB0SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1023, 2, 'PM_UCB0SDA' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1079, 3, 'S21'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1024, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1024, 1, 'PM_UCB0SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1024, 2, 'PM_UCB0SCL' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1080, 3, 'S20'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1025, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1025, 1, 'PM_RFGDO2'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1081, 2, 'S19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1026, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1026, 1, 'PM_RFGDO0'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1082, 2, 'S18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1027, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1027, 1, 'PM_SMCLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1083, 2, 'S17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1028, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1028, 1, 'PM_RFGDO1'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1084, 2, 'S16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1029, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1029, 1, 'PM_TA0CCR4A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1085, 2, 'S15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1030, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1030, 1, 'PM_TA0CCR3A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1086, 2, 'S14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1031, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1031, 1, 'PM_TA0CCR2A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1087, 2, 'S13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1032, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1032, 1, 'PM_TA0CCR1A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1088, 2, 'S12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1033, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1033, 1, 'PM_TA0CCR0A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1089, 2, 'S11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1034, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1034, 1, 'PM_CBOUT0'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1034, 2, 'PM_TA0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1090, 3, 'S10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1035, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1036, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1036, 1, 'S9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1037, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1037, 1, 'S8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1038, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1038, 1, 'S7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1039, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1039, 1, 'S6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1040, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1040, 1, 'S5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1041, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1041, 1, 'S4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1042, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1042, 1, 'S3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1043, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1043, 1, 'S2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1044, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1044, 1, 'S1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1045, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1045, 1, 'S0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1046, 0, 'RF_XIN'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1047, 0, 'RF_XOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1048, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1049, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1050, 0, 'RF_P'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1051, 0, 'RF_N'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1052, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1053, 0, 'AVCC_RF'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1054, 0, 'RBIAS'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1055, 0, 'GUARD'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1056, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1056, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1057, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1057, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1057, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1058, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1058, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1059, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1059, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1060, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1060, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1061, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1061, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1061, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1062, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1063, 0, 'AVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1064, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1064, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1065, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1065, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1066, 0, 'AVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1067, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1067, 1, 'PM_ADC10CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1067, 2, 'PM_DMAE0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1091, 3, 'CB7'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1099, 4, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1068, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1068, 1, 'PM_ACLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1092, 2, 'CB6'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1100, 3, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1069, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1069, 1, 'PM_SVMOUT'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1069, 2, 'CB5'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1093, 3, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1093, 4, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1093, 5, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1101, 6, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1101, 7, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1101, 8, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1070, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1070, 1, 'PM_RTCCLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1070, 2, 'CB4'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1094, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1094, 4, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1094, 5, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1102, 6, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1102, 7, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1102, 8, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1071, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1071, 1, 'PM_TA1CCR2A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1071, 2, 'CB3'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1095, 3, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1103, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1072, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1072, 1, 'PM_TA1CCR1A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1072, 2, 'CB2'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1096, 3, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1104, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1073, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1073, 1, 'PM_TA1CCR0A');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1073, 2, 'CB1'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1097, 3, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1105, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1074, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1074, 1, 'PM_CBOUT1'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1074, 2, 'PM_TA1CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1074, 3, 'CB0'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1098, 4, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (1106, 5, 'A0'         );

UPDATE orderable SET pinset_id = 83 WHERE name = 'CC430F6147IRGCR';
UPDATE orderable SET pinset_id = 83 WHERE name = 'CC430F6147IRGCT';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5143IRGZR';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5143IRGZT';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5145IRGZR';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5145IRGZT';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5147IRGZR';
UPDATE orderable SET pinset_id = 81 WHERE name = 'CC430F5147IRGZT';
UPDATE orderable SET pinset_id = 82 WHERE name = 'CC430F5123IRGZR';
UPDATE orderable SET pinset_id = 82 WHERE name = 'CC430F5123IRGZT';
UPDATE orderable SET pinset_id = 82 WHERE name = 'CC430F5125IRGZR';
UPDATE orderable SET pinset_id = 82 WHERE name = 'CC430F5125IRGZT';

COMMIT TRANSACTION;
