--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2532', 'SLAS942', 16,  8192, 1024, 15, 2, 0, 1, 1, 0, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2533', 'SLAS942', 16, 16384, 2048, 19, 2, 0, 1, 2, 0, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2632', 'SLAS942', 16,  8192, 2048, 15, 2, 0, 1, 2, 0, 4, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633', 'SLAS942', 16, 16384, 4096, 19, 2, 0, 1, 2, 0, 4, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2532', 'ADC_SAR10'   , '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2532', 'BSL_I2C'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2532', 'BSL_UART'    , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2532', 'IO_CAPTIVATE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2532', 'ADV_SENSE'   , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2533', 'ADC_SAR10'   , '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2533', 'BSL_I2C'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2533', 'BSL_UART'    , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2533', 'IO_CAPTIVATE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2533', 'ADV_SENSE'   , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2632', 'ADC_SAR10'   , '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2632', 'BSL_I2C'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2632', 'BSL_UART'    , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2632', 'IO_CAPTIVATE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2632', 'ADV_SENSE'   , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2633', 'ADC_SAR10'   , '8' , NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2633', 'BSL_I2C'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2633', 'BSL_UART'    , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2633', 'IO_CAPTIVATE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2633', 'ADV_SENSE'   , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2532IRGER', 'MSP430FR2532', 'RGE', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2532IRGET', 'MSP430FR2532', 'RGE', 24, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2533IDA'  , 'MSP430FR2533', 'DA' , 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2533IDAR' , 'MSP430FR2533', 'DA' , 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2533IRHBR', 'MSP430FR2533', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2533IRHBT', 'MSP430FR2533', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2632IRGER', 'MSP430FR2632', 'RGE', 24, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2632IRGET', 'MSP430FR2632', 'RGE', 24, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2632IYQWR', 'MSP430FR2632', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2632IYQWT', 'MSP430FR2632', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IDA'  , 'MSP430FR2633', 'DA' , 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IDAR' , 'MSP430FR2633', 'DA' , 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IRHBR', 'MSP430FR2633', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IRHBT', 'MSP430FR2633', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IYQWR', 'MSP430FR2633', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2633IYQWT', 'MSP430FR2633', 'YQW', 24, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, comment) VALUES (1, NULL, 32, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (2, NULL, 32, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (3, NULL, 24, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (4, NULL, 24, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 1, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 2, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 3, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 4, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 5, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 6, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 7, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 8, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES ( 9, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (10, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (11, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (12, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (13, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (14, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (15, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (16, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (17, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (18, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (19, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (20, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (21, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (22, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (23, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (24, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (25, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (26, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (27, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (28, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (29, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (30, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (31, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (32, NULL, 31);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  1, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  1, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  1, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  1, 'E' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  2, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  2, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  2, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  2, 'D' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  3, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  3, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  3, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  3, 'D' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  4, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  4, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  4, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  4, 'C' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  5, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  5, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  5, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  5, 'C' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  6, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  6, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  6, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  6, 'B' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  7, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  7, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  7, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  7, 'B' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  8, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  8, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  8, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  8, 'A' ,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1,  9, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2,  9, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3,  9, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4,  9, 'B' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 10, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 10, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 10, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 10, 'A' ,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 11, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 11, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 11, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 11, 'A' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 12, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 12, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 12, 'A' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 13, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 13, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 14, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 14, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 14, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 14, 'A' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 15, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 15, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 15, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 16, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 16, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 17, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 17, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 18, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 18, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 18, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 18, 'B' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 19, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 19, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 19, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 19, 'B' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 20, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 20, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 20, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 20, 'C' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 21, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 21, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 21, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 21, 'C' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 22, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 22, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 22, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 23, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 23, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 23, 'D' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 24, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 24, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 25, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 25, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 25, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 25, 'E' ,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 26, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 26, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 26, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 27, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 27, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 27, 'D' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 28, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 28, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 29, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 29, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 29, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 29, 'E' ,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 30, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 30, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 30, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 30, 'E' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 31, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 31, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 31, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 31, 'D' ,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (1, 32, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (2, 32, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (3, 32, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (4, 32, 'E' ,  2);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 1, 0, '~RST'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 1, 1, 'NMI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 1, 2, 'SBWTDIO'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 2, 0, 'TEST'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 2, 1, 'SBWTCK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 0, 'P1.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 1, 'UCA0TXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 2, 'UCA0SIMO' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 3, 'TA1.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 4, 'TCK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 5, 'A4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 3, 6, 'VREF+'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 0, 'P1.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 1, 'UCA0RXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 2, 'UCA0SOMI' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 3, 'TA1.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 4, 'TMS'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 4, 5, 'A5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 0, 'P1.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 1, 'UCA0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 2, 'TA1CLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 3, 'TDI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 4, 'TCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 5, 5, 'A6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 6, 0, 'P1.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 6, 1, 'UCA0STE'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 6, 2, 'SMCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 6, 3, 'TDO'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 6, 4, 'A7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 7, 0, 'P1.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 7, 1, 'UCB0STE'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 7, 2, 'TA0CLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 7, 3, 'A0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 7, 4, 'VEREF+'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 8, 0, 'P1.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 8, 1, 'UCB0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 8, 2, 'TA0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 8, 3, 'A1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 0, 'P1.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 1, 'UCB0SIMO' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 2, 'UCB0SDA'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 3, 'TA0.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 4, 'A2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES ( 9, 5, 'VEREF-'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (10, 0, 'P1.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (10, 1, 'UCB0SOMI' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (10, 2, 'UCB0SCL'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (10, 3, 'MCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (10, 4, 'A3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (11, 0, 'P2.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (11, 1, 'SYNC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (11, 2, 'ACLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (12, 0, 'P3.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (12, 1, 'CAP0.0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (13, 0, 'CAP0.1'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (14, 0, 'P2.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (14, 1, 'CAP0.2'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (15, 0, 'CAP0.3'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (16, 0, 'P3.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (16, 1, 'UCA1STE'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (16, 2, 'CAP1.0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (17, 0, 'P2.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (17, 1, 'UCA1CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (17, 2, 'CAP1.1'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (18, 0, 'P2.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (18, 1, 'UCA1RXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (18, 2, 'UCA1SOMI' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (18, 3, 'CAP1.2'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (19, 0, 'P2.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (19, 1, 'UCA1TXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (19, 2, 'UCA1SIMO' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (19, 3, 'CAP1.3'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (20, 0, 'VREG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (21, 0, 'CAP2.0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (22, 0, 'CAP2.1'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (23, 0, 'CAP2.2'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (24, 0, 'CAP2.3'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (25, 0, 'P2.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (25, 1, 'CAP3.0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (26, 0, 'CAP3.1'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (27, 0, 'P3.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (27, 1, 'CAP3.2'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (28, 0, 'CAP3.3'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (29, 0, 'P2.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (29, 1, 'XOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (30, 0, 'P2.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (30, 1, 'XIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (31, 0, 'DVSS'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (32, 0, 'DVCC'     );

UPDATE orderable SET pinset_id = 2 WHERE name = 'MSP430FR2533IDA'  ;
UPDATE orderable SET pinset_id = 2 WHERE name = 'MSP430FR2533IDAR' ;
UPDATE orderable SET pinset_id = 2 WHERE name = 'MSP430FR2633IDA'  ;
UPDATE orderable SET pinset_id = 2 WHERE name = 'MSP430FR2633IDAR' ;
UPDATE orderable SET pinset_id = 3 WHERE name = 'MSP430FR2532IRGER';
UPDATE orderable SET pinset_id = 3 WHERE name = 'MSP430FR2532IRGET';
UPDATE orderable SET pinset_id = 3 WHERE name = 'MSP430FR2632IRGER';
UPDATE orderable SET pinset_id = 3 WHERE name = 'MSP430FR2632IRGET';
UPDATE orderable SET pinset_id = 1 WHERE name = 'MSP430FR2533IRHBR';
UPDATE orderable SET pinset_id = 1 WHERE name = 'MSP430FR2533IRHBT';
UPDATE orderable SET pinset_id = 1 WHERE name = 'MSP430FR2633IRHBR';
UPDATE orderable SET pinset_id = 1 WHERE name = 'MSP430FR2633IRHBT';
UPDATE orderable SET pinset_id = 4 WHERE name = 'MSP430FR2632IYQWR';
UPDATE orderable SET pinset_id = 4 WHERE name = 'MSP430FR2632IYQWT';
UPDATE orderable SET pinset_id = 4 WHERE name = 'MSP430FR2633IYQWR';
UPDATE orderable SET pinset_id = 4 WHERE name = 'MSP430FR2633IYQWT';

COMMIT TRANSACTION;
