--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F133', 'SLAS272', 8, 8192, 256, 48, 1, 0, 0, 1, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F135', 'SLAS272', 8, 16384, 512, 48, 1, 0, 0, 1, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147', 'SLAS272', 8, 32768, 1024, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1471', 'SLAS272', 8, 32768, 1024, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F148', 'SLAS272', 8, 49152, 2048, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1481', 'SLAS272', 8, 49152, 2048, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149', 'SLAS272', 8, 61440, 2048, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1491', 'SLAS272', 8, 61440, 2048, 48, 2, 0, 0, 2, 2, 2, -40, 85, 'TI EXPORT');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F133IPAG'    , 'MSP430F133', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F133IPM'     , 'MSP430F133', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F133IPMR'    , 'MSP430F133', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F135IPAG'    , 'MSP430F135', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F135IPM'     , 'MSP430F135', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F135IPMR'    , 'MSP430F135', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1471IPM'    , 'MSP430F1471', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1471IPMR'   , 'MSP430F1471', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147IPAG'    , 'MSP430F147', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147IPM'     , 'MSP430F147', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147IPMR'    , 'MSP430F147', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147IPMR-KAM', 'MSP430F147', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F147IPMRG4'  , 'MSP430F147', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1481IPM'    , 'MSP430F1481', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1481IPMR'   , 'MSP430F1481', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F148IPAG'    , 'MSP430F148', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F148IPM'     , 'MSP430F148', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F148IPMR'    , 'MSP430F148', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1491IPM'    , 'MSP430F1491', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F1491IPMR'   , 'MSP430F1491', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPAG'    , 'MSP430F149', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPAGR'   , 'MSP430F149', 'PAG',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPM'     , 'MSP430F149', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPMG4'   , 'MSP430F149', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPMR'    , 'MSP430F149', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430F149IPMRG4'  , 'MSP430F149', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   93,  NULL,   0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   94,  NULL,   1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   95,  NULL,   2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   96,  NULL,   3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   97,  NULL,   4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   98,  NULL,   5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (   99,  NULL,   6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  100,  NULL,   7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  101,  NULL,   8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  102,  NULL,   9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  103,  NULL,  10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  104,  NULL,  11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  105,  NULL,  12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  106,  NULL,  13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  107,  NULL,  14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  108,  NULL,  15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  109,  NULL,  16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  110,  NULL,  17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  111,  NULL,  18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  168,   111,  18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  112,  NULL,  19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  113,  NULL,  20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  114,  NULL,  21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  115,  NULL,  22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  116,  NULL,  23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  117,  NULL,  24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  118,  NULL,  25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  119,  NULL,  26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  157,   119,  26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  120,  NULL,  27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  158,   120,  27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  121,  NULL,  28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  122,  NULL,  29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  123,  NULL,  30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  124,  NULL,  31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  159,   124,  31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  125,  NULL,  32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  160,   125,  32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  126,  NULL,  33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  161,   126,  33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  127,  NULL,  34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  162,   127,  34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  128,  NULL,  35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  129,  NULL,  36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  163,   129,  36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  130,  NULL,  37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  164,   130,  37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  131,  NULL,  38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  165,   131,  38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  132,  NULL,  39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  166,   132,  39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  133,  NULL,  40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  134,  NULL,  41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  135,  NULL,  42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  136,  NULL,  43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  137,  NULL,  44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  167,   137,  44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  138,  NULL,  45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  169,   138,  45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  139,  NULL,  46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  170,   139,  46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  140,  NULL,  47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  171,   140,  47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  141,  NULL,  48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  172,   141,  48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  142,  NULL,  49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  173,   142,  49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  143,  NULL,  50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  174,   143,  50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  144,  NULL,  51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  175,   144,  51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  145,  NULL,  52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  146,  NULL,  53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  147,  NULL,  54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  148,  NULL,  55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  149,  NULL,  56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  150,  NULL,  57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  151,  NULL,  58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  152,  NULL,  59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  153,  NULL,  60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  154,  NULL,  61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  155,  NULL,  62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  156,  NULL,  63);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   93, 0, 'AVCC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   94, 0, 'AVSS'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   95, 0, 'DVCC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   96, 0, 'DVSS'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   97, 0, 'P1.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   97, 1, 'TACLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   98, 0, 'P1.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   98, 1, 'TA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   99, 0, 'P1.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (   99, 1, 'TA1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  100, 0, 'P1.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  100, 1, 'TA2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  101, 0, 'P1.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  101, 1, 'SMCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  102, 0, 'P1.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  102, 1, 'TA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  103, 0, 'P1.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  103, 1, 'TA1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  104, 0, 'P1.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  104, 1, 'TA2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  105, 0, 'P2.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  105, 1, 'ACLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  106, 0, 'P2.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  106, 1, 'TAINCLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  107, 0, 'P2.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  107, 1, 'CAOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  107, 2, 'TA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  108, 0, 'P2.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  108, 1, 'CA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  108, 2, 'TA1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  109, 0, 'P2.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  109, 1, 'CA1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  109, 2, 'TA2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  110, 0, 'P2.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  110, 1, 'ROSC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  111, 0, 'P2.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  168, 1, 'ADC12CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  112, 0, 'P2.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  112, 1, 'TA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  113, 0, 'P3.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  113, 1, 'STE0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  114, 0, 'P3.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  114, 1, 'SIMO0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  115, 0, 'P3.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  115, 1, 'SOMI0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  116, 0, 'P3.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  116, 1, 'UCLK0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  117, 0, 'P3.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  117, 1, 'UTXD0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  118, 0, 'P3.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  118, 1, 'URXD0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  119, 0, 'P3.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  157, 1, 'UTXD1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  120, 0, 'P3.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  158, 1, 'URXD1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  121, 0, 'P4.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  121, 1, 'TB0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  122, 0, 'P4.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  122, 1, 'TB1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  123, 0, 'P4.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  123, 1, 'TB2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  124, 0, 'P4.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  159, 1, 'TB3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  125, 0, 'P4.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  160, 1, 'TB4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  126, 0, 'P4.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  161, 1, 'TB5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  127, 0, 'P4.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  162, 1, 'TB6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  128, 0, 'P4.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  128, 1, 'TBCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  129, 0, 'P5.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  163, 1, 'STE1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  130, 0, 'P5.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  164, 1, 'SIMO1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  131, 0, 'P5.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  165, 1, 'SOMI1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  132, 0, 'P5.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  166, 1, 'UCLK1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  133, 0, 'P5.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  133, 1, 'MCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  134, 0, 'P5.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  134, 1, 'SMCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  135, 0, 'P5.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  135, 1, 'ACLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  136, 0, 'P5.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  136, 1, 'TBOUTH'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  137, 0, 'P6.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  167, 1, 'A0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  138, 0, 'P6.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  169, 1, 'A1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  139, 0, 'P6.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  170, 1, 'A2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  140, 0, 'P6.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  171, 1, 'A3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  141, 0, 'P6.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  172, 1, 'A4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  142, 0, 'P6.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  173, 1, 'A5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  143, 0, 'P6.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  174, 1, 'A6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  144, 0, 'P6.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  175, 1, 'A7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  145, 0, '~RST'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  145, 1, 'NMI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  146, 0, 'TCK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  147, 0, 'TDI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  147, 1, 'TCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  148, 0, 'TDO'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  148, 1, 'TDI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  149, 0, 'TMS'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  150, 0, 'VEREF+'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  151, 0, 'VREF+'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  152, 0, 'VREF-'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  152, 1, 'VEREF-'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  153, 0, 'XIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  154, 0, 'XOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  155, 0, 'XT2IN'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  156, 0, 'XT2OUT'   );

INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  13, NULL,  64, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  14,   13,   9, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (  15,   14,  10, NULL);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    93, NULL,  64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    94, NULL,  62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    95, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    96, NULL,  63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    97, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    98, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,    99, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   100, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   101, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   102, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   103, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   104, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   105, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   106, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   107, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   108, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   109, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   110, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   111, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   168, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   112, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   113, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   114, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   115, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   116, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   117, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   118, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   119, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   157, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   120, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   158, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   121, NULL,  36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   122, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   123, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   124, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   159, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   125, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   160, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   126, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   161, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   127, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   162, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   128, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   129, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   163, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   130, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   164, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   131, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   165, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   132, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  15,   166, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   133, NULL,  48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   134, NULL,  49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   135, NULL,  50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   136, NULL,  51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   137, NULL,  59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   167, NULL,  59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   138, NULL,  60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   169, NULL,  60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   139, NULL,  61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   170, NULL,  61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   140, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   171, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   141, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   172, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   142, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   173, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   143, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   174, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   144, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  14,   175, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   145, NULL,  58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   146, NULL,  57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   147, NULL,  55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   148, NULL,  54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   149, NULL,  56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   150, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   151, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   152, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   153, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   154, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   155, NULL,  53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  13,   156, NULL,  52);

UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F133IPAG';
UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F135IPAG';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F147IPAG';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F148IPAG';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPAG';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPAGR';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1471IPM';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1471IPMR';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1481IPM';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1481IPMR';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1491IPM';
UPDATE orderable SET pinset_id =   13 WHERE name = 'MSP430F1491IPMR';
UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F133IPM';
UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F133IPMR';
UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F135IPM';
UPDATE orderable SET pinset_id =   14 WHERE name = 'MSP430F135IPMR';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F147IPM';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F147IPMR';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F147IPMR-KAM';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F147IPMRG4';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F148IPM';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F148IPMR';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPM';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPMG4';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPMR';
UPDATE orderable SET pinset_id =   15 WHERE name = 'MSP430F149IPMRG4';

COMMIT TRANSACTION;
