--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475', 'SLASEO7', 16, 32768, 6144, 43, 2, 0, 2, 4, 4, 5, -40, 105, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476', 'SLASEO7', 16, 65536, 8192, 43, 2, 0, 2, 4, 4, 5, -40, 105, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2475', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2475', 'BSL_I2C', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2476', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR2476', 'BSL_I2C', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TPT'   , 'MSP430FR2475', 'PT' ,  48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TPTR'  , 'MSP430FR2475', 'PT' ,  48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TRHAR' , 'MSP430FR2475', 'RHA',  40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TRHAT' , 'MSP430FR2475', 'RHA',  40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TRHBR' , 'MSP430FR2475', 'RHB',  32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2475TRHBT' , 'MSP430FR2475', 'RHB',  32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TPT'   , 'MSP430FR2476', 'PT' ,  48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TPTR'  , 'MSP430FR2476', 'PT' ,  48, 'ACTIVE', 3, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TRHAR' , 'MSP430FR2476', 'RHA',  40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TRHAT' , 'MSP430FR2476', 'RHA',  40, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TRHBR' , 'MSP430FR2476', 'RHB',  32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR2476TRHBT' , 'MSP430FR2476', 'RHB',  32, 'ACTIVE', 1, -40, 105, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, idx, pins, comment) VALUES (  47, NULL, 0,  48, NULL);
INSERT INTO pinset (id, parent_id, idx, pins, comment) VALUES (  48, NULL, 0,  40, NULL);
INSERT INTO pinset (id, parent_id, idx, pins, comment) VALUES (  49, NULL, 0,  32, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  460,  NULL,   0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  461,  NULL,   1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  462,  NULL,   2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  463,  NULL,   3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  464,  NULL,   4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  465,  NULL,   5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  466,  NULL,   6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  467,  NULL,   7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  468,  NULL,   8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  469,  NULL,   9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  470,  NULL,  10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  471,  NULL,  11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  472,  NULL,  12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  473,  NULL,  13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  474,  NULL,  14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  475,  NULL,  15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  476,  NULL,  16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  477,  NULL,  17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  478,  NULL,  18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  479,  NULL,  19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  480,  NULL,  20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  481,  NULL,  21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  482,  NULL,  22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  483,  NULL,  23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  484,  NULL,  24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  485,  NULL,  25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  486,  NULL,  26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  487,  NULL,  27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  488,  NULL,  28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  489,  NULL,  29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  490,  NULL,  30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  491,  NULL,  31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  492,  NULL,  32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  493,  NULL,  33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  494,  NULL,  34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  495,  NULL,  35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  496,  NULL,  36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  497,  NULL,  37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  498,  NULL,  38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  499,  NULL,  39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  500,  NULL,  40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  501,  NULL,  41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  502,  NULL,  42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  503,  NULL,  43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  504,  NULL,  44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  505,  NULL,  45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  506,  NULL,  46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (  507,  NULL,  47);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   460, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   460, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   460, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   461, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   461, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   461, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   462, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   462, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   462, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   463, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   463, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   463, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   464, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   464, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   464, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   465, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   465, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   465, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   466, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   466, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   466, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   467, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   467, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   468, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   468, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   469, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   470, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   471, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   471, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   471, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   472, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   472, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   472, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   473, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   473, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   473, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   474, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   474, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   474, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   475, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   475, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   475, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   476, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   476, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   477, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   477, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   478, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   479, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   480, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   481, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   482, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   482, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   482, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   483, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   483, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   483, NULL,  13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   484, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   484, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   484, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   485, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   485, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   485, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   486, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   486, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   486, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   487, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   487, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   487, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   488, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   488, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   488, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   489, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   489, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   489, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   490, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   490, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   490, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   491, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   491, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   491, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   492, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   492, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   492, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   493, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   493, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   493, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   494, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   494, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   494, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   495, NULL,  36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   495, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   495, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   496, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   496, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   496, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   497, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   497, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   497, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   498, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   498, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   498, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   499, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   500, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   501, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   501, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   502, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   502, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   503, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   503, NULL,  36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   504, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   504, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   505, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   505, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   505, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   506, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   506, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   506, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  47,   507, NULL,  48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  48,   507, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (  49,   507, NULL,  31);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  460, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  461, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  461, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  461, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  462, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  462, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 3, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 4, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 5, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  463, 6, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 3, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 4, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  464, 5, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 3, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 4, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  465, 5, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  466, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  466, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  466, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  466, 3, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  466, 4, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  467, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  467, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  467, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  467, 3, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  467, 4, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  468, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  468, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  468, 2, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  468, 3, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  468, 4, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  469, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  469, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  469, 2, 'TA3.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  469, 3, 'A10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  470, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  470, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  470, 2, 'TA3CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  470, 3, 'A11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  471, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  471, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  471, 2, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  471, 3, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  471, 4, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  472, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  472, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  472, 2, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  472, 3, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  472, 4, 'COMP0.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 3, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  473, 5, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  474, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  474, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  474, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  474, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  474, 4, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  475, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  475, 1, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  475, 2, 'COMP0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  476, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  476, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  476, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  476, 3, 'TA3.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  477, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  477, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  477, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  477, 3, 'TA3.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  478, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  478, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  478, 2, 'TA2CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  479, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  479, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  479, 2, 'TA2.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  480, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  480, 1, 'TA2.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  480, 2, 'COMP0.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  481, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  481, 1, 'TA2.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  481, 2, 'COMP0.3'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  482, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  482, 1, 'TA2.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  483, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  483, 1, 'TA2.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  484, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  484, 1, 'TA2.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  485, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  485, 1, 'TA2CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  485, 2, 'COMP0OUT'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  486, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  486, 1, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  487, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  487, 1, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  488, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  488, 1, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  488, 2, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  489, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  489, 1, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  489, 2, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  490, 0, 'DNC'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  491, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  491, 1, 'TA3.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  492, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  492, 1, 'TA3.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  493, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  493, 1, 'TA3.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  494, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  494, 1, 'TA3CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  495, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  495, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  496, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  496, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  496, 2, 'TB0TRG'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  497, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  497, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  497, 2, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  498, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  498, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  498, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  499, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  499, 1, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  500, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  500, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  501, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  501, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  501, 2, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  502, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  502, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  502, 2, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  503, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  503, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  503, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  503, 3, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  504, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  504, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  504, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  504, 3, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  505, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  505, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  506, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  506, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (  507, 0, 'DVSS'       );

UPDATE orderable SET pinset_id =   47 WHERE name = 'MSP430FR2475TPT';
UPDATE orderable SET pinset_id =   47 WHERE name = 'MSP430FR2475TPTR';
UPDATE orderable SET pinset_id =   47 WHERE name = 'MSP430FR2476TPT';
UPDATE orderable SET pinset_id =   47 WHERE name = 'MSP430FR2476TPTR';
UPDATE orderable SET pinset_id =   48 WHERE name = 'MSP430FR2475TRHAR';
UPDATE orderable SET pinset_id =   48 WHERE name = 'MSP430FR2475TRHAT';
UPDATE orderable SET pinset_id =   48 WHERE name = 'MSP430FR2476TRHAR';
UPDATE orderable SET pinset_id =   48 WHERE name = 'MSP430FR2476TRHAT';
UPDATE orderable SET pinset_id =   49 WHERE name = 'MSP430FR2475TRHBR';
UPDATE orderable SET pinset_id =   49 WHERE name = 'MSP430FR2475TRHBT';
UPDATE orderable SET pinset_id =   49 WHERE name = 'MSP430FR2476TRHBR';
UPDATE orderable SET pinset_id =   49 WHERE name = 'MSP430FR2476TRHBT';

COMMIT TRANSACTION;
