--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131', 'SLAS865', 16,  4096,  512, 60, 1, 0, 1, 2, 0, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132', 'SLAS865', 16,  8192, 1024, 60, 1, 0, 1, 2, 0, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133', 'SLAS865', 16, 16384, 2048, 60, 1, 0, 1, 2, 0, 2, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4131', 'ADC_SAR10', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4131', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4131', 'IRML'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4132', 'ADC_SAR10', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4132', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4132', 'IRML'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4133', 'ADC_SAR10', '10', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4133', 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR4133', 'IRML'     , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131IG48' , 'MSP430FR4131', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131IG48R', 'MSP430FR4131', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131IG56' , 'MSP430FR4131', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131IG56R', 'MSP430FR4131', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4131IPMR' , 'MSP430FR4131', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132IG48' , 'MSP430FR4132', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132IG48R', 'MSP430FR4132', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132IG56' , 'MSP430FR4132', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132IG56R', 'MSP430FR4132', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4132IPMR' , 'MSP430FR4132', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IG48' , 'MSP430FR4133', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IG48R', 'MSP430FR4133', 'DGG', 48, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IG56' , 'MSP430FR4133', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IG56R', 'MSP430FR4133', 'DGG', 56, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IPM'  , 'MSP430FR4133', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR4133IPMR' , 'MSP430FR4133', 'PM' , 64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (38, NULL, 48, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (39, NULL, 56, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (40, NULL, 64, 0, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (374, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (375, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (376, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (377, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (378, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (379, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (380, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (381, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (382, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (383, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (384, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (385, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (386, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (387, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (388, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (389, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (390, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (391, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (392, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (393, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (394, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (395, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (396, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (397, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (398, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (399, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (400, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (401, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (402, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (403, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (404, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (405, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (406, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (407, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (408, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (409, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (410, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (411, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (412, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (413, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (414, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (415, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (416, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (417, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (418, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (419, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (420, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (421, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (422, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (423, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (424, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (425, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (426, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (427, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (428, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (429, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (430, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (431, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (432, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (433, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (434, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (435, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (436, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (437, NULL, 63);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 374, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 374, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 374, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 375, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 375, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 375, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 376, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 376, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 376, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 377, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 377, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 377, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 378, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 378, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 378, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 379, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 379, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 379, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 380, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 380, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 380, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 381, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 381, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 381, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 382, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 382, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 382, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 383, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 383, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 383, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 384, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 384, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 384, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 385, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 385, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 385, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 386, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 386, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 387, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 387, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 388, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 389, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 390, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 390, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 390, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 391, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 391, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 391, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 392, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 392, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 392, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 393, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 393, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 393, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 394, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 394, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 394, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 395, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 395, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 395, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 396, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 396, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 396, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 397, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 397, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 397, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 398, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 399, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 400, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 400, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 401, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 401, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 402, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 402, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 402, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 403, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 403, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 403, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 404, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 404, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 404, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 405, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 405, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 405, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 406, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 406, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 406, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 407, NULL, 32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 407, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 407, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 408, NULL, 33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 408, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 408, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 409, NULL, 34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 409, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 409, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 410, NULL, 35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 410, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 410, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 411, NULL, 36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 411, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 411, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 412, NULL, 37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 412, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 412, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 413, NULL, 38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 413, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 413, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 414, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 415, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 416, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 416, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 417, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 417, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 418, NULL, 39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 418, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 418, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 419, NULL, 40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 419, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 419, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 420, NULL, 41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 420, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 420, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 421, NULL, 42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 421, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 421, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 422, NULL, 43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 422, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 422, NULL, 49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 423, NULL, 44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 423, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 423, NULL, 50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 424, NULL, 45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 424, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 424, NULL, 51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 425, NULL, 46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 425, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 425, NULL, 52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 426, NULL, 47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 426, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 426, NULL, 53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 427, NULL, 48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 427, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 427, NULL, 54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 428, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 428, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 428, NULL, 55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 429, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 429, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 429, NULL, 56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 430, NULL, 57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 431, NULL, 58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 432, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 432, NULL, 59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 433, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 433, NULL, 60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 434, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 434, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 434, NULL, 61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 435, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 435, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 435, NULL, 62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 436, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 436, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 436, NULL, 63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (38, 437, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (39, 437, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (40, 437, NULL, 64);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (374, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (374, 1, 'R13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (375, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (375, 1, 'R23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (376, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (376, 1, 'R33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (377, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (377, 1, 'LCDCAP1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (378, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (378, 1, 'LCDCAP0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (379, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (379, 1, 'XOUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (380, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (380, 1, 'XIN'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (381, 0, 'DVSS'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (382, 0, 'DVCC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (383, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (383, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (383, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (384, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (384, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (385, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (385, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (386, 0, 'P8.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (386, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (387, 0, 'P8.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (387, 1, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (388, 0, 'P8.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (388, 1, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (388, 2, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (389, 0, 'P8.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (389, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (389, 2, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (390, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (390, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (390, 2, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (390, 3, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (391, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (391, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (391, 2, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (391, 3, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (391, 4, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (392, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (392, 1, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (392, 2, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (392, 3, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (393, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (393, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (393, 2, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (393, 3, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (393, 4, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (394, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (394, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (394, 2, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (395, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (395, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (395, 2, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 1, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 2, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 3, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 4, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (396, 5, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 1, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 2, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 3, 'A0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 4, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (397, 5, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (398, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (398, 1, 'L39'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (399, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (399, 1, 'L38'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (400, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (400, 1, 'L37'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (401, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (401, 1, 'L36'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (402, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (402, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (402, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (402, 3, 'L35'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (403, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (403, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (403, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (403, 3, 'L34'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (404, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (404, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (404, 2, 'L33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (405, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (405, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (405, 2, 'L32'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (406, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (406, 1, 'L31'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (407, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (407, 1, 'L30'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (408, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (408, 1, 'L29'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (409, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (409, 1, 'L28'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (410, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (410, 1, 'L27'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (411, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (411, 1, 'L26'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (412, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (412, 1, 'L25'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (413, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (413, 1, 'L24'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (414, 0, 'P6.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (414, 1, 'L23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (415, 0, 'P6.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (415, 1, 'L22'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (416, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (416, 1, 'L21'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (417, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (417, 1, 'L20'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (418, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (418, 1, 'L19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (419, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (419, 1, 'L18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (420, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (420, 1, 'L17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (421, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (421, 1, 'L16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (422, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (422, 1, 'L15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (423, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (423, 1, 'L14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (424, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (424, 1, 'L13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (425, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (425, 1, 'L12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (426, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (426, 1, 'L11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (427, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (427, 1, 'L10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (428, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (428, 1, 'L9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (429, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (429, 1, 'L8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (430, 0, 'P7.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (430, 1, 'L7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (431, 0, 'P7.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (431, 1, 'L7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (432, 0, 'P7.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (432, 1, 'L5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (433, 0, 'P7.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (433, 1, 'L4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (434, 0, 'P7.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (434, 1, 'L3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (435, 0, 'P7.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (435, 1, 'L2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (436, 0, 'P7.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (436, 1, 'L1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (437, 0, 'P7.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (437, 1, 'L0'         );

UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4131IG48' ;
UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4131IG48R';
UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4132IG48' ;
UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4132IG48R';
UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4133IG48' ;
UPDATE orderable SET pinset_id = 38 WHERE name = 'MSP430FR4133IG48R';
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4131IG56' ;
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4131IG56R';
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4132IG56' ;
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4132IG56R';
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4133IG56' ;
UPDATE orderable SET pinset_id = 39 WHERE name = 'MSP430FR4133IG56R';
UPDATE orderable SET pinset_id = 40 WHERE name = 'MSP430FR4131IPMR' ;
UPDATE orderable SET pinset_id = 40 WHERE name = 'MSP430FR4132IPMR' ;
UPDATE orderable SET pinset_id = 40 WHERE name = 'MSP430FR4133IPM'  ;
UPDATE orderable SET pinset_id = 40 WHERE name = 'MSP430FR4133IPMR' ;

COMMIT TRANSACTION;
