--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153', 'SLAS735', 16,  1024, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213', 'SLAS735', 16,  2048, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253', 'SLAS735', 16,  2048, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313', 'SLAS735', 16,  4096, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353', 'SLAS735', 16,  4096, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413', 'SLAS735', 16,  8192, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453', 'SLAS735', 16,  8192, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513', 'SLAS735', 16, 16384, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553', 'SLAS735', 16, 16384, 512, 24, 1, 0, 1, 2, 8, 2, -40, 85, 'TI EXPORT');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IN20'   , 'MSP430G2153', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW20'  , 'MSP430G2153', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW20R' , 'MSP430G2153', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW28'  , 'MSP430G2153', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW28R' , 'MSP430G2153', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IRHB32R', 'MSP430G2153', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IRHB32T', 'MSP430G2153', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IN20'   , 'MSP430G2213', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW20'  , 'MSP430G2213', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW20R' , 'MSP430G2213', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW28'  , 'MSP430G2213', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IRHB32R', 'MSP430G2213', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IRHB32T', 'MSP430G2213', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IN20'   , 'MSP430G2253', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW20'  , 'MSP430G2253', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW20R' , 'MSP430G2253', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW28'  , 'MSP430G2253', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW28R' , 'MSP430G2253', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IRHB32R', 'MSP430G2253', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IRHB32T', 'MSP430G2253', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IN20'   , 'MSP430G2313', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW20'  , 'MSP430G2313', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW20R' , 'MSP430G2313', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW28'  , 'MSP430G2313', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IRHB32R', 'MSP430G2313', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IRHB32T', 'MSP430G2313', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IN20'   , 'MSP430G2353', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW20'  , 'MSP430G2353', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW20R' , 'MSP430G2353', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW28'  , 'MSP430G2353', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW28R' , 'MSP430G2353', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IRHB32R', 'MSP430G2353', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IRHB32T', 'MSP430G2353', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IN20'   , 'MSP430G2413', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW20'  , 'MSP430G2413', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW20R' , 'MSP430G2413', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW28'  , 'MSP430G2413', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW28R' , 'MSP430G2413', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IRHB32R', 'MSP430G2413', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IRHB32T', 'MSP430G2413', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IN20'   , 'MSP430G2453', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW20'  , 'MSP430G2453', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW20R' , 'MSP430G2453', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW28'  , 'MSP430G2453', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW28R' , 'MSP430G2453', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IRHB32R', 'MSP430G2453', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IRHB32T', 'MSP430G2453', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IN20'   , 'MSP430G2513', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW20'  , 'MSP430G2513', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW20R' , 'MSP430G2513', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW28'  , 'MSP430G2513', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW28R' , 'MSP430G2513', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IRHB32R', 'MSP430G2513', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IRHB32T', 'MSP430G2513', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IN20'   , 'MSP430G2553', 'N'  , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW20'  , 'MSP430G2553', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW20R' , 'MSP430G2553', 'PW' , 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW28'  , 'MSP430G2553', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW28R' , 'MSP430G2553', 'PW' , 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IRHB32R', 'MSP430G2553', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IRHB32T', 'MSP430G2553', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, comment) VALUES ( 5, NULL, 20, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES ( 6, NULL, 20, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES ( 7, NULL, 28, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES ( 8, NULL, 32, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES ( 9,    5,  8, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (10,    6,  8, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (11,    7,  8, NULL);
INSERT INTO pinset (id, parent_id, pins, comment) VALUES (12,    8,  8, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (33, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (39,   33,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (34, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (40,   34,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (35, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (41,   35,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (36, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (42,   36,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (37, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (43,   37,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (38, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (44,   38,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (45, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (52,   45,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (46, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (53,   46,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (47, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (48, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (49, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (50, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (51, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (54, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (55, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (56, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (57, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (58, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (59, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (60, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (61, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (62, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (63, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (64, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (65, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (66, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (67, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (68, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (69, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (70, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (71, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (72, NULL, 31);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 33, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 33, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 33, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 33, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 39, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 39, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 39, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 39, NULL, 31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 34, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 34, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 34, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 34, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 40, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 40, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 40, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 40, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 35, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 35, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 35, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 35, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 41, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 41, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 41, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 41, NULL,  2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 36, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 36, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 36, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 36, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 42, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 42, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 42, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 42, NULL,  3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 37, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 37, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 37, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 37, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 43, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 43, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 43, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 43, NULL,  4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 38, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 38, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 38, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 38, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 44, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 44, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 44, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 44, NULL,  5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 45, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 45, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 45, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 45, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 52, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 52, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 52, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 52, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 46, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 46, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 46, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 46, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 9, 53, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (10, 53, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (11, 53, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (12, 53, NULL, 22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 47, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 47, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 47, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 47, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 48, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 48, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 48, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 48, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 49, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 49, NULL, 10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 49, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 49, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 50, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 50, NULL, 11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 50, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 50, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 51, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 51, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 51, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 51, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 54, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 54, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 54, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 54, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 55, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 55, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 55, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 55, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 56, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 56, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 56, NULL, 26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 56, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 57, NULL,  9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 57, NULL,  7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 58, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 58, NULL,  6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 59, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 59, NULL, 12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 60, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 60, NULL, 13);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 61, NULL, 15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 61, NULL, 14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 62, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 62, NULL, 18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 63, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 63, NULL, 19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 64, NULL, 21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 64, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 65, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 65, NULL, 16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 65, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 65, NULL, 23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 66, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 66, NULL, 17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 66, NULL, 25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 66, NULL, 24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 67, NULL, 29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 68, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 68, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 68, NULL,  1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 68, NULL, 30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 5, 69, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 6, 69, NULL, 20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 7, 69, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 69, NULL, 27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 70, NULL, 28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 71, NULL,  8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES ( 8, 72, NULL, 32);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 0, 'P1.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 1, 'TA0CLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 2, 'ACLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (39, 3, 'A0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 4, 'CA0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 0, 'P1.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 1, 'TA0.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 2, 'UCA0RXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 3, 'UCA0SOMI' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (40, 4, 'A1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 5, 'CA1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 6, 'BSLTX'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 0, 'P1.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 1, 'TA0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 2, 'UCA0TXD'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 3, 'UCA0SIMO' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (41, 4, 'A2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 5, 'CA2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 0, 'P1.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (42, 1, 'ADC10CLK' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (42, 2, 'A3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (42, 3, 'VREF-'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (42, 4, 'VEREF-'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 5, 'CA3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 6, 'CAOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 0, 'P1.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 1, 'SMCLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 2, 'UCB0STE'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 3, 'UCA0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (43, 4, 'A4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (43, 5, 'VREF+'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (43, 6, 'VEREF+'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 7, 'CA4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 8, 'TCK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 0, 'P1.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 1, 'TA0.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 2, 'UCB0CLK'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 3, 'UCA0STE'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (44, 4, 'A5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 5, 'CA5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 6, 'TMS'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 0, 'P1.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 1, 'TA0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (52, 2, 'A6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 3, 'CA6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 4, 'UCB0SOMI' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 5, 'UCB0SCL'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 6, 'TDI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (45, 7, 'TCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 0, 'P1.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (53, 1, 'A7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 2, 'CA7'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 3, 'CAOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 4, 'UCB0SIMO' );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 5, 'UCB0SDA'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 6, 'TDO'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (46, 7, 'TDI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (47, 0, 'P2.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (47, 1, 'TA1.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (48, 0, 'P2.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (48, 1, 'TA1.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (49, 0, 'P2.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (49, 1, 'TA1.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (50, 0, 'P2.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (50, 1, 'TA1.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (51, 0, 'P2.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (51, 1, 'TA1.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (54, 0, 'P2.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (54, 1, 'TA1.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (55, 0, 'XIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (55, 1, 'P2.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (55, 2, 'TA0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (56, 0, 'XOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (56, 1, 'P2.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (57, 0, 'P3.0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (57, 1, 'TA0.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (58, 0, 'P3.1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (58, 1, 'TA1.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (59, 0, 'P3.2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (59, 1, 'TA1.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (60, 0, 'P3.3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (60, 1, 'TA1.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (61, 0, 'P3.4'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (61, 1, 'TA0.0'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (62, 0, 'P3.5'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (62, 1, 'TA0.1'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (63, 0, 'P3.6'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (63, 1, 'TA0.2'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (64, 0, 'P3.7'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (64, 1, 'TA1CLK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (64, 2, 'CAOUT'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (65, 0, '~RST'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (65, 1, 'NMI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (65, 2, 'SBWTDIO'  );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (66, 0, 'TEST'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (66, 1, 'SBWTCK'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (67, 0, 'AVCC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (68, 0, 'DVCC'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (69, 0, 'DVSS'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (70, 0, 'DVSS'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (71, 0, 'NC'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (72, 0, 'NC'       );

UPDATE orderable SET pinset_id =  5 WHERE name = 'MSP430G2213IN20'   ;
UPDATE orderable SET pinset_id =  5 WHERE name = 'MSP430G2313IN20'   ;
UPDATE orderable SET pinset_id =  5 WHERE name = 'MSP430G2413IN20'   ;
UPDATE orderable SET pinset_id =  5 WHERE name = 'MSP430G2513IN20'   ;
UPDATE orderable SET pinset_id =  9 WHERE name = 'MSP430G2153IN20'   ;
UPDATE orderable SET pinset_id =  9 WHERE name = 'MSP430G2253IN20'   ;
UPDATE orderable SET pinset_id =  9 WHERE name = 'MSP430G2353IN20'   ;
UPDATE orderable SET pinset_id =  9 WHERE name = 'MSP430G2453IN20'   ;
UPDATE orderable SET pinset_id =  9 WHERE name = 'MSP430G2553IN20'   ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2213IPW20'  ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2213IPW20R' ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2313IPW20'  ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2313IPW20R' ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2413IPW20'  ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2413IPW20R' ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2513IPW20'  ;
UPDATE orderable SET pinset_id =  6 WHERE name = 'MSP430G2513IPW20R' ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2153IPW20'  ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2153IPW20R' ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2253IPW20'  ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2253IPW20R' ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2353IPW20'  ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2353IPW20R' ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2453IPW20'  ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2453IPW20R' ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2553IPW20'  ;
UPDATE orderable SET pinset_id = 10 WHERE name = 'MSP430G2553IPW20R' ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2213IPW28'  ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2313IPW28'  ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2413IPW28'  ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2413IPW28R' ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2513IPW28'  ;
UPDATE orderable SET pinset_id =  7 WHERE name = 'MSP430G2513IPW28R' ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2153IPW28'  ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2153IPW28R' ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2253IPW28'  ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2253IPW28R' ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2353IPW28'  ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2353IPW28R' ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2453IPW28'  ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2453IPW28R' ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2553IPW28'  ;
UPDATE orderable SET pinset_id = 11 WHERE name = 'MSP430G2553IPW28R' ;
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2213IRHB32R';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2213IRHB32T';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2313IRHB32R';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2313IRHB32T';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2413IRHB32R';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2413IRHB32T';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2513IRHB32R';
UPDATE orderable SET pinset_id =  8 WHERE name = 'MSP430G2513IRHB32T';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2153IRHB32R';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2153IRHB32T';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2253IRHB32R';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2253IRHB32T';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2353IRHB32R';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2353IRHB32T';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2453IRHB32R';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2453IRHB32T';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2553IRHB32R';
UPDATE orderable SET pinset_id = 12 WHERE name = 'MSP430G2553IRHB32T';

COMMIT TRANSACTION;
