--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5986' , 'SLAS789', 16,  49152, 2048, 48, 2, 0, 2, 4, 12, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5987' , 'SLAS789', 16,  65536, 2048, 48, 2, 0, 2, 4, 12, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5988' , 'SLAS789', 16,  98304, 2048, 48, 2, 0, 2, 4, 12, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5989' , 'SLAS789', 16, 131072, 2048, 48, 2, 0, 2, 4, 12, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59891', 'SLAS789', 16, 131072, 2048, 48, 2, 0, 2, 4, 12, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6987' , 'SLAS789', 16,  65536, 2048, 83, 2, 0, 2, 4, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6988' , 'SLAS789', 16,  98304, 2048, 83, 2, 0, 2, 4, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6989' , 'SLAS789', 16, 131072, 2048, 83, 2, 0, 2, 4, 16, 5, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR69891', 'SLAS789', 16, 131072, 2048, 83, 2, 0, 2, 4, 16, 5, -40, 85, 'TI EXPORT');

INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5986' , 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5986' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5986' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5987' , 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5987' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5987' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5988' , 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5988' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5988' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5989' , 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5989' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR5989' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59891', 'ADC_SAR12', '12', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59891', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR59891', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6987' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6987' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6987' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6988' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6988' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6988' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6989' , 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6989' , 'BSL_UART' , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR6989' , 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR69891', 'ADC_SAR12', '16', NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR69891', 'BSL_I2C'  , NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');
INSERT INTO device_feature (device_id, feature_id, param1, param2, param3, comment) VALUES ('MSP430FR69891', 'ADV_SENSE', NULL, NULL, NULL, 'AUTOMATIC RESOLUTION');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5986IPM'   , 'MSP430FR5986' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5986IPMR'  , 'MSP430FR5986' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5987IPM'   , 'MSP430FR5987' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5987IPMR'  , 'MSP430FR5987' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5987IRGCR' , 'MSP430FR5987' , 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5987IRGCT' , 'MSP430FR5987' , 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5988IPM'   , 'MSP430FR5988' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5988IRGCT' , 'MSP430FR5988' , 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59891IPM'  , 'MSP430FR59891', 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR59891IRGCT', 'MSP430FR59891', 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5989IPM'   , 'MSP430FR5989' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5989IPMR'  , 'MSP430FR5989' , 'PM' ,  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5989IRGCR' , 'MSP430FR5989' , 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR5989IRGCT' , 'MSP430FR5989' , 'RGC',  64, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6987IPN'   , 'MSP430FR6987' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6987IPNR'  , 'MSP430FR6987' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6987IPZ'   , 'MSP430FR6987' , 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6988IPN'   , 'MSP430FR6988' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6988IPNR'  , 'MSP430FR6988' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6988IPZ'   , 'MSP430FR6988' , 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR69891IPN'  , 'MSP430FR69891', 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR69891IPZ'  , 'MSP430FR69891', 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR69891IPZR' , 'MSP430FR69891', 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6989IPN'   , 'MSP430FR6989' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6989IPNR'  , 'MSP430FR6989' , 'PN' ,  80, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6989IPZ'   , 'MSP430FR6989' , 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430FR6989IPZR'  , 'MSP430FR6989' , 'PZ' , 100, 'ACTIVE', 3, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (70, NULL,  0, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (71, NULL,  0, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (72, NULL, 78, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (73, NULL, 98, 0, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (74,   72,  4, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (75,   73,  4, 1, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (76,   75, 43, 2, NULL);
INSERT INTO pinset (id, parent_id, pins, group_idx, comment) VALUES (77,   74, 36, 3, NULL);

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (752, NULL,  0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (753, NULL,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (754,  753,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (755,  754,  1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (756, NULL,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (760,  756,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (761,  760,  2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (757, NULL,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (762,  757,  3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (758, NULL,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (763,  758,  4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (759, NULL,  5);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (764, NULL,  6);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (765, NULL,  7);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (766, NULL,  8);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (767, NULL,  9);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (768, NULL, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (902,  768, 10);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (769, NULL, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (903,  769, 11);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (770, NULL, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (857,  770, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (861,  857, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (904,  861, 12);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (771, NULL, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (858,  771, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (862,  858, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (905,  862, 13);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (772, NULL, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (859,  772, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (863,  859, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (906,  863, 14);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (773, NULL, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (860,  773, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (864,  860, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (907,  864, 15);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (774, NULL, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (865,  774, 16);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (775, NULL, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (866,  775, 17);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (776, NULL, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (867,  776, 18);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (777, NULL, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (868,  777, 19);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (778, NULL, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (869,  778, 20);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (779, NULL, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (870,  779, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (908,  870, 21);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (780, NULL, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (871,  780, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (909,  871, 22);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (781, NULL, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (872,  781, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (910,  872, 23);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (782, NULL, 24);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (783, NULL, 25);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (784, NULL, 26);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (785, NULL, 27);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (786, NULL, 28);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (787, NULL, 29);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (788, NULL, 30);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (789, NULL, 31);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (790, NULL, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (873,  790, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (911,  873, 32);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (791, NULL, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (874,  791, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (912,  874, 33);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (792, NULL, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (913,  792, 34);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (793, NULL, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (875,  793, 35);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (794, NULL, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (876,  794, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (914,  876, 36);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (795, NULL, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (877,  795, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (915,  877, 37);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (796, NULL, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (878,  796, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (916,  878, 38);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (797, NULL, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (879,  797, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (917,  879, 39);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (798, NULL, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (880,  798, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (918,  880, 40);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (799, NULL, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (881,  799, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (919,  881, 41);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (800, NULL, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (882,  800, 42);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (801, NULL, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (883,  801, 43);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (802, NULL, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (884,  802, 44);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (803, NULL, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (885,  803, 45);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (804, NULL, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (920,  804, 46);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (805, NULL, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (921,  805, 47);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (806, NULL, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (922,  806, 48);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (807, NULL, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (923,  807, 49);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (808, NULL, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (886,  808, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (924,  886, 50);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (809, NULL, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (887,  809, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (925,  887, 51);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (810, NULL, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (888,  810, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (926,  888, 52);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (811, NULL, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (889,  811, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (927,  889, 53);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (812, NULL, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (890,  812, 54);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (813, NULL, 55);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (814, NULL, 56);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (815, NULL, 57);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (816, NULL, 58);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (817, NULL, 59);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (818, NULL, 60);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (819, NULL, 61);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (820, NULL, 62);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (821, NULL, 63);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (822, NULL, 64);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (823, NULL, 65);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (824, NULL, 66);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (825, NULL, 67);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (826, NULL, 68);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (827, NULL, 69);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (828, NULL, 70);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (829, NULL, 71);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (830, NULL, 72);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (831, NULL, 73);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (832, NULL, 74);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (833, NULL, 75);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (834, NULL, 76);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (835, NULL, 77);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (836, NULL, 78);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (837, NULL, 79);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (838, NULL, 80);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (839, NULL, 81);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (840, NULL, 82);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (841, NULL, 83);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (842, NULL, 84);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (843, NULL, 85);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (891,  843, 85);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (844, NULL, 86);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (892,  844, 86);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (845, NULL, 87);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (893,  845, 87);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (846, NULL, 88);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (894,  846, 88);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (847, NULL, 89);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (895,  847, 89);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (928,  895, 89);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (848, NULL, 90);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (896,  848, 90);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (929,  896, 90);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (849, NULL, 91);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (897,  849, 91);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (930,  897, 91);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (850, NULL, 92);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (898,  850, 92);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (931,  898, 92);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (851, NULL, 93);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (899,  851, 93);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (852, NULL, 94);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (900,  852, 94);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (932,  900, 94);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (853, NULL, 95);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (901,  853, 95);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (933,  901, 95);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (854, NULL, 96);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (855, NULL, 97);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (856, NULL, 98);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 752, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 752, NULL,   1);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 753, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 753, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 754, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 755, NULL,   2);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 756, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 756, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 760, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 761, NULL,   3);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 757, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 757, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 762, NULL,   4);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 758, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 758, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 763, NULL,   5);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 759, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 759, NULL,   6);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 764, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 764, NULL,   7);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 765, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 765, NULL,   8);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 766, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 766, NULL,   9);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 767, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 767, NULL,  10);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 768, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 768, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 902, NULL,  11);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 769, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 769, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 903, NULL,  12);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 770, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 770, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (74, 857, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (75, 857, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 861, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 904, NULL,  14);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 771, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 771, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (74, 858, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (75, 858, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 862, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 905, NULL,  15);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 772, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 772, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (74, 859, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (75, 859, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 863, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 906, NULL,  16);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 773, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 773, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (74, 860, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (75, 860, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 864, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 907, NULL,  17);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 774, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 865, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 775, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 866, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 776, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 867, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 777, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 868, NULL,  21);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 778, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 869, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 779, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 779, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 870, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 908, NULL,  18);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 780, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 780, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 871, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 909, NULL,  19);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 781, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 781, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 872, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 910, NULL,  20);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 782, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 783, NULL,  22);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 783, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 784, NULL,  23);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 784, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 785, NULL,  24);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 785, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 786, NULL,  25);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 786, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 787, NULL,  26);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 787, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 788, NULL,  27);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 788, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 789, NULL,  28);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 789, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 790, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 790, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 873, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 911, NULL,  29);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 791, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 791, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 874, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 912, NULL,  30);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 792, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 913, NULL,  31);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 793, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 875, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 794, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 794, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 876, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 914, NULL,  32);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 795, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 795, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 877, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 915, NULL,  33);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 796, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 796, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 878, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 916, NULL,  34);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 797, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 797, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 879, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 917, NULL,  35);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 798, NULL,  36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 798, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 880, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 918, NULL,  36);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 799, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 799, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 881, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 919, NULL,  37);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 800, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 882, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 801, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 883, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 802, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 884, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 803, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 885, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 804, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 804, NULL,  48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 920, NULL,  38);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 805, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 805, NULL,  49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 921, NULL,  39);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 806, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 806, NULL,  50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 922, NULL,  40);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 807, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 807, NULL,  51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 923, NULL,  41);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 808, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 808, NULL,  52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 886, NULL,  52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 924, NULL,  42);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 809, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 809, NULL,  53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 887, NULL,  53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 925, NULL,  43);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 810, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 810, NULL,  54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 888, NULL,  54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 926, NULL,  44);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 811, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 811, NULL,  55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 889, NULL,  55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 927, NULL,  45);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 812, NULL,  56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 890, NULL,  56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 813, NULL,  46);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 813, NULL,  57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 814, NULL,  47);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 814, NULL,  58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 815, NULL,  59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 816, NULL,  60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 817, NULL,  61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 818, NULL,  62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 819, NULL,  48);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 819, NULL,  63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 820, NULL,  49);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 820, NULL,  64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 821, NULL,  50);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 821, NULL,  65);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 822, NULL,  51);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 822, NULL,  66);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 823, NULL,  52);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 823, NULL,  67);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 824, NULL,  53);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 824, NULL,  68);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 825, NULL,  54);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 825, NULL,  69);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 826, NULL,  55);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 826, NULL,  70);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 827, NULL,  56);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 827, NULL,  71);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 828, NULL,  57);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 828, NULL,  72);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 829, NULL,  58);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 829, NULL,  73);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 830, NULL,  59);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 830, NULL,  74);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 831, NULL,  60);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 831, NULL,  75);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 832, NULL,  61);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 832, NULL,  76);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 833, NULL,  62);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 833, NULL,  77);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 834, NULL,  63);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 834, NULL,  78);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 835, NULL,  64);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 835, NULL,  79);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 836, NULL,  65);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 836, NULL,  80);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 837, NULL,  66);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 837, NULL,  81);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 838, NULL,  67);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 838, NULL,  82);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 839, NULL,  68);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 839, NULL,  83);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 840, NULL,  69);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 840, NULL,  84);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 841, NULL,  70);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 841, NULL,  85);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 842, NULL,  71);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 842, NULL,  86);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 843, NULL,  87);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 891, NULL,  87);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 844, NULL,  88);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 892, NULL,  88);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 845, NULL,  89);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 893, NULL,  89);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 846, NULL,  90);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 894, NULL,  90);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 847, NULL,  72);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 847, NULL,  91);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 895, NULL,  91);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 928, NULL,  72);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 848, NULL,  73);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 848, NULL,  92);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 896, NULL,  92);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 929, NULL,  73);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 849, NULL,  74);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 849, NULL,  93);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 897, NULL,  93);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 930, NULL,  74);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 850, NULL,  75);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 850, NULL,  94);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 898, NULL,  94);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 931, NULL,  75);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 851, NULL,  95);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 899, NULL,  95);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 852, NULL,  76);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 852, NULL,  96);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 900, NULL,  96);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 932, NULL,  76);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 853, NULL,  77);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 853, NULL,  97);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (76, 901, NULL,  97);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (77, 933, NULL,  77);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 854, NULL,  78);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 854, NULL,  98);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 855, NULL,  79);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 855, NULL,  99);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (72, 856, NULL,  80);
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (73, 856, NULL, 100);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (752, 0, 'P4.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (752, 1, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (752, 2, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (752, 3, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (753, 0, 'P1.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (753, 1, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (753, 2, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (753, 3, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (754, 4, 'S1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (755, 5, 'S3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (756, 0, 'P1.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (756, 1, 'UCB0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (756, 2, 'UCB0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (756, 3, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (760, 4, 'S0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (761, 5, 'S2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (757, 0, 'P1.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (757, 1, 'UCB0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (757, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (757, 3, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (757, 4, 'BSLSDA'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (762, 5, 'S1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (758, 0, 'P1.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (758, 1, 'UCB0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (758, 2, 'UCB0SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (758, 3, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (758, 4, 'BSLSCL'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (763, 5, 'S0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (759, 0, 'R33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (759, 1, 'LCDCAP'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (764, 0, 'P6.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (764, 1, 'R23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (765, 0, 'P6.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (765, 1, 'R13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (765, 2, 'LCDREF'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (766, 0, 'P6.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (766, 1, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (766, 2, 'R03'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (767, 0, 'P6.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (767, 1, 'COM0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (768, 0, 'P6.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (768, 1, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (768, 2, 'COM1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (902, 3, 'S36'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (769, 0, 'P6.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (769, 1, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (769, 2, 'COM2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (903, 3, 'S34'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (770, 0, 'P2.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (770, 1, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (857, 2, 'COM4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (861, 3, 'S43'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (904, 4, 'S33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (771, 0, 'P2.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (771, 1, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (858, 2, 'COM5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (862, 3, 'S42'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (905, 4, 'S32'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (772, 0, 'P2.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (772, 1, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (772, 2, 'ESIC1OUT'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (859, 3, 'COM6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (863, 4, 'S41'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (906, 5, 'S31'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (773, 0, 'P2.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (773, 1, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (773, 2, 'ESIC2OUT'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (860, 3, 'COM7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (864, 4, 'S40'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (907, 5, 'S30'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (774, 0, 'P10.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (774, 1, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (774, 2, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (865, 3, 'S39'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (775, 0, 'P5.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (775, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (775, 2, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (866, 3, 'S38'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (776, 0, 'P5.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (776, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (867, 2, 'S37'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (777, 0, 'P5.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (777, 1, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (777, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (777, 3, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (868, 4, 'S36'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (778, 0, 'P5.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (778, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (869, 2, 'S35'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (779, 0, 'P3.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (779, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (870, 2, 'S34'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (908, 3, 'S29'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (780, 0, 'P3.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (780, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (780, 2, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (871, 3, 'S33'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (909, 4, 'S28'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (781, 0, 'P3.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (781, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (781, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (872, 3, 'S32'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (910, 4, 'S27'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (782, 0, 'DVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (783, 0, 'DVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (784, 0, 'TEST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (784, 1, 'SBWTCK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (785, 0, '~RST'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (785, 1, 'NMI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (785, 2, 'SBWTDIO'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (786, 0, 'PJ.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (786, 1, 'TDO'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (786, 2, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (786, 3, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (786, 4, 'SRSCG1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (787, 0, 'PJ.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (787, 1, 'TDI'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (787, 2, 'TCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (787, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (787, 4, 'SRSCG0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (788, 0, 'PJ.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (788, 1, 'TMS'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (788, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (788, 3, 'SROSCOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (789, 0, 'PJ.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (789, 1, 'TCK'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (789, 2, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (789, 3, 'SRCPUOFF'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (790, 0, 'P6.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (790, 1, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (873, 2, 'S31'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (911, 3, 'S26'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (791, 0, 'P7.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (791, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (874, 2, 'S30'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (912, 3, 'S25'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (792, 0, 'P7.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (792, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (913, 3, 'S24'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (793, 0, 'P10.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (793, 1, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (875, 2, 'S28'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (794, 0, 'P7.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (794, 1, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (794, 2, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (876, 3, 'S27'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (914, 4, 'S23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (795, 0, 'P3.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (795, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (795, 2, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (877, 3, 'S26'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (915, 4, 'S22'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (796, 0, 'P3.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (796, 1, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (796, 2, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (796, 3, 'TB0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (878, 4, 'S25'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (916, 5, 'S21'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (797, 0, 'P3.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (797, 1, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (797, 2, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (797, 3, 'TB0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (879, 4, 'S24'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (917, 5, 'S20'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (798, 0, 'P3.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (798, 1, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (798, 2, 'TB0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (880, 3, 'S23'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (918, 4, 'S19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (799, 0, 'P3.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (799, 1, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (799, 2, 'TB0.3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (881, 3, 'S22'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (919, 4, 'S18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (800, 0, 'P8.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (800, 1, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (882, 2, 'S21'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (801, 0, 'P8.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (801, 1, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (883, 2, 'S20'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (802, 0, 'P8.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (884, 1, 'S19'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (803, 0, 'P8.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (803, 1, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (885, 2, 'S18'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (804, 0, 'P2.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (804, 1, 'UCA0STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (804, 2, 'TB0OUTH'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (920, 3, 'S17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (805, 0, 'P2.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (805, 1, 'UCA0CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (805, 2, 'TB0.4'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (805, 3, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (921, 4, 'S16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 0, 'P2.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 1, 'UCA0SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 2, 'UCA0RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 3, 'TB0.5'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 4, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (806, 5, 'BSLTX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (922, 6, 'S15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 0, 'P2.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 1, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 2, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 3, 'TB0.6'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 4, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (807, 5, 'BSLRX'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (923, 6, 'S14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (808, 0, 'P7.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (808, 1, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (886, 2, 'S17'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (924, 3, 'S13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (809, 0, 'P7.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (809, 1, 'TA0.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (809, 2, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (887, 3, 'S16'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (925, 4, 'S12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (810, 0, 'P7.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (810, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (888, 2, 'S15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (926, 3, 'S11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (811, 0, 'P7.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (811, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (889, 2, 'S14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (927, 3, 'S10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (812, 0, 'P7.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (812, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (890, 2, 'S13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (813, 0, 'DVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (814, 0, 'DVCC2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (815, 0, 'P8.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (815, 1, 'A7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (815, 2, 'C7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (816, 0, 'P8.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (816, 1, 'A6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (816, 2, 'C6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (817, 0, 'P8.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (817, 1, 'A5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (817, 2, 'C5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (818, 0, 'P8.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (818, 1, 'A4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (818, 2, 'C4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (819, 0, 'P1.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (819, 1, 'ESITEST4'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (819, 2, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (819, 3, 'A3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (819, 4, 'C3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 0, 'P1.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 1, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 2, 'TA0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 4, 'A2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (820, 5, 'C2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 0, 'P1.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 1, 'TA0.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 3, 'COUT'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 4, 'A1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 5, 'C1'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 6, 'VREF+'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (821, 7, 'VEREF+'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 0, 'P1.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 1, 'TA0.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 2, 'DMAE0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 3, 'RTCCLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 4, 'C0'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 5, 'VREF-'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (822, 6, 'VEREF-'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (823, 0, 'P9.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (823, 1, 'ESICH0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (823, 2, 'ESITEST0'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (823, 3, 'A8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (823, 4, 'C8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (824, 0, 'P9.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (824, 1, 'ESICH1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (824, 2, 'ESITEST1'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (824, 3, 'A9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (824, 4, 'C9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (825, 0, 'P9.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (825, 1, 'ESICH2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (825, 2, 'ESITEST2'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (825, 3, 'A10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (825, 4, 'C10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (826, 0, 'P9.3'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (826, 1, 'ESICH3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (826, 2, 'ESITEST3'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (826, 3, 'A11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (826, 4, 'C11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (827, 0, 'P9.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (827, 1, 'ESICI0'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (827, 2, 'A12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (827, 3, 'C12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (828, 0, 'P9.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (828, 1, 'ESICI1'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (828, 2, 'A13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (828, 3, 'C13'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (829, 0, 'P9.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (829, 1, 'ESICI2'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (829, 2, 'A14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (829, 3, 'C14'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (830, 0, 'P9.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (830, 1, 'ESICI3'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (830, 2, 'A15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (830, 3, 'C15'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (831, 0, 'ESIDVCC'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (832, 0, 'ESIDVSS'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (833, 0, 'ESICI'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (834, 0, 'ESICOM'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (835, 0, 'AVCC1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (836, 0, 'AVSS3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (837, 0, 'PJ.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (837, 1, 'HFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (838, 0, 'PJ.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (838, 1, 'HFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (839, 0, 'AVSS1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (840, 0, 'PJ.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (840, 1, 'LFXIN'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (841, 0, 'PJ.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (841, 1, 'LFXOUT'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (842, 0, 'AVSS2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (843, 0, 'P5.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (843, 1, 'UCA1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (843, 2, 'UCA1TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (891, 3, 'S12'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (844, 0, 'P5.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (844, 1, 'UCA1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (844, 2, 'UCA1RXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (892, 3, 'S11'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (845, 0, 'P5.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (845, 1, 'UCA1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (893, 2, 'S10'        );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (846, 0, 'P5.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (846, 1, 'UCA1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (846, 2, 'TB0CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (894, 3, 'S9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (847, 0, 'P4.4'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (847, 1, 'UCB1STE'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (847, 2, 'TA1CLK'     );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (895, 3, 'S8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (928, 4, 'S9'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (848, 0, 'P4.5'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (848, 1, 'UCB1CLK'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (848, 2, 'TA1.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (896, 3, 'S7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (929, 4, 'S8'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (849, 0, 'P4.6'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (849, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (849, 2, 'UCB1SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (849, 3, 'TA1.1'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (897, 4, 'S6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (930, 5, 'S7'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (850, 0, 'P4.7'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (850, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (850, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (850, 3, 'TA1.2'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (898, 4, 'S5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (931, 5, 'S6'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (851, 0, 'P10.0'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (851, 1, 'SMCLK'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (899, 2, 'S4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (852, 0, 'P4.0'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (852, 1, 'UCB1SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (852, 2, 'UCB0SDA'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (852, 3, 'MCLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (900, 4, 'S3'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (932, 5, 'S5'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (853, 0, 'P4.1'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (853, 1, 'UCB1SOMI'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (853, 2, 'UCB1SCL'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (853, 3, 'ACLK'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (901, 4, 'S2'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (933, 5, 'S4'         );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (854, 0, 'DVSS3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (855, 0, 'DVCC3'      );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (856, 0, 'P4.2'       );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (856, 1, 'UCA0SIMO'   );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (856, 2, 'UCA0TXD'    );
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (856, 3, 'UCB1CLK'    );

UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5986IPM'   ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5986IPMR'  ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5987IPM'   ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5987IPMR'  ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5988IPM'   ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5989IPM'   ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR5989IPMR'  ;
UPDATE orderable SET pinset_id = 70 WHERE name = 'MSP430FR59891IPM'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6987IPN'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6987IPNR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6988IPN'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6988IPNR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6989IPN'   ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR6989IPNR'  ;
UPDATE orderable SET pinset_id = 77 WHERE name = 'MSP430FR69891IPN'  ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR6987IPZ'   ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR6988IPZ'   ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR6989IPZ'   ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR6989IPZR'  ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR69891IPZ'  ;
UPDATE orderable SET pinset_id = 76 WHERE name = 'MSP430FR69891IPZR' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR5987IRGCR' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR5987IRGCT' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR5988IRGCT' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR5989IRGCR' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR5989IRGCT' ;
UPDATE orderable SET pinset_id = 71 WHERE name = 'MSP430FR59891IRGCT';

COMMIT TRANSACTION;
