--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A0', 'Analog input A0');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A1', 'Analog input A1');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A2', 'Analog input A2');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A3', 'Analog input A3');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A4', 'Analog input A4');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A5', 'Analog input A5');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A6', 'Analog input A6');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'A7', 'Analog input A7');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'ACLK', 'ACLK output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'ADC10CLK', 'ADC10, conversion clock output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'BSL_TX', 'EXTRA SIGNAL: BSL transmit');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA0', 'Comparator_A+, CA0 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA1', 'Comparator_A+, CA1 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA2', 'Comparator_A+, CA2 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA3', 'Comparator_A+, CA3 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA4', 'Comparator_A+, CA4 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CA5', 'Comparator_A+, CA5 input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAOUT', 'Comparator_A+, output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP0.0', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP0.1', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP0.2', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP0.3', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP1.0', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP1.1', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP1.2', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP1.3', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP2.0', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP2.1', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP2.2', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP2.3', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP3.0', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP3.1', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP3.2', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'CAP3.3', 'CapTIvate channel');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'DVCC', 'Power supply');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'DVSS', 'Power ground');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'MCLK', 'MCLK output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'NMI', 'Nonmaskable interrupt input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.0', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.1', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.2', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.3', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.4', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.5', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.6', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P1.7', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.0', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.1', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.2', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.3', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.4', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.5', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.6', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P2.7', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P3.0', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P3.1', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'P3.2', 'General-purpose I/O');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'SBWTCK', 'Spy-Bi-Wire input clock');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'SBWTDIO', 'Spy-Bi-Wire data input/output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'SMCLK', 'SMCLK output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'SYNC', 'CapTIvate synchronous trigger input for processing and conversion');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA0.0', 'Timer0_A, capture: CCI0A input, compare: Out0 output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA0.1', 'Timer TA0 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA0.2', 'Timer TA0 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA0CLK', 'Timer clock input TACLK for TA0');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA1.1', 'Timer TA1 CCR1 capture: CCI1A input, compare: Out1 output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA1.2', 'Timer TA1 CCR2 capture: CCI2A input, compare: Out2 output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TA1CLK', 'Timer clock input TACLK for TA1');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TCK', 'Test clock');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TCLK', 'Test clock input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TDI', 'Test data input');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TDO', 'Test data output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TEST', 'Test Mode pin');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'TMS', 'Test mode select');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0CLK', 'eUSCI_A0 SPI clock input/output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0RXD', 'eUSCI_A0 UART receive data');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0SIMO', 'eUSCI_A0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0SOMI', 'eUSCI_A0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0STE', 'eUSCI_A0 SPI slave');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA0TXD', 'eUSCI_A0 UART transmit data');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1CLK', 'eUSCI_A1 SPI clock input/output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1RXD', 'eUSCI_A1 UART receive data');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1SIMO', 'eUSCI_A1 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1SOMI', 'eUSCI_A1 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1STE', 'eUSCI_A1 SPI slave');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCA1TXD', 'eUSCI_A1 UART transmit data');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0CLK', 'eUSCI_B0 clock input/output');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0SCL', 'eUSCI_B0 I2C clock');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0SDA', 'eUSCI_B0 I2C data');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0SIMO', 'eUSCI_B0 SPI slave in/master out');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0SOMI', 'eUSCI_B0 SPI slave out/master in');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'UCB0STE', 'eUSCI_B0 slave transmit enable');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'VREF+', 'Output of positive reference voltage with ground as reference');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'VREF+/VEREF+', 'ADC10 positive reference voltage');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'VREF-/VEREF-', 'ADC10 negative reference voltage');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'VREG', 'CapTIvate regulator external decoupling capacitor');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'Veref+', 'ADC positive reference');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'Veref-', 'ADC negative reference');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'XIN', 'Input terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, 'XOUT', 'Output terminal for crystal oscillator');
INSERT INTO signal (signalgroup, id, desc) VALUES (NULL, '~RST', 'Active-low reset input');

COMMIT TRANSACTION;
