--
-- File generated with one of the sjabloon 430 database tools.
-- Any alterations to this data will be kept by these tools, assuming the SQL is still valid.
-- DO NOT REFORMAT THIS FILE AND CHECK IN ONLY AFTER RE-EXPORTING WITH A SJABLOON 430 TOOL.
--
-- Text encoding used: UTF-8
--
BEGIN TRANSACTION;

INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153', 'SLAS735', 16, 1024, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213', 'SLAS735', 16, 2048, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253', 'SLAS735', 16, 2048, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313', 'SLAS735', 16, 4096, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353', 'SLAS735', 16, 4096, 256, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413', 'SLAS735', 16, 8192, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453', 'SLAS735', 16, 8192, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513', 'SLAS735', 16, 16384, 512, 24, 1, 0, 1, 1, 8, 2, -40, 85, 'TI EXPORT');
INSERT INTO device (model, datasheet_id, freq_max, storage_bytes, ram_bytes, gpio_count, uart_count, usb_count, i2c_count, spi_count, comp_count, timer_count, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553', 'SLAS735', 16, 16384, 512, 24, 1, 0, 1, 2, 8, 2, -40, 85, 'TI EXPORT');

INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2113IN20', 'MSP430G2153', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IN20', 'MSP430G2153', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW20', 'MSP430G2153', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW20R', 'MSP430G2153', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW28', 'MSP430G2153', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IPW28R', 'MSP430G2153', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IRHB32R', 'MSP430G2153', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2153IRHB32T', 'MSP430G2153', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IN20', 'MSP430G2213', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW20', 'MSP430G2213', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW20R', 'MSP430G2213', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IPW28', 'MSP430G2213', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IRHB32R', 'MSP430G2213', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2213IRHB32T', 'MSP430G2213', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IN20', 'MSP430G2253', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW20', 'MSP430G2253', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW20R', 'MSP430G2253', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW28', 'MSP430G2253', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IPW28R', 'MSP430G2253', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IRHB32R', 'MSP430G2253', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2253IRHB32T', 'MSP430G2253', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IN20', 'MSP430G2313', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW20', 'MSP430G2313', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW20R', 'MSP430G2313', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IPW28', 'MSP430G2313', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IRHB32R', 'MSP430G2313', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2313IRHB32T', 'MSP430G2313', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IN20', 'MSP430G2353', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW20', 'MSP430G2353', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW20R', 'MSP430G2353', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW28', 'MSP430G2353', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IPW28R', 'MSP430G2353', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IRHB32R', 'MSP430G2353', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2353IRHB32T', 'MSP430G2353', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IN20', 'MSP430G2413', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW20', 'MSP430G2413', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW20R', 'MSP430G2413', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW28', 'MSP430G2413', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IPW28R', 'MSP430G2413', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IRHB32R', 'MSP430G2413', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2413IRHB32T', 'MSP430G2413', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IN20', 'MSP430G2453', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW20', 'MSP430G2453', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW20R', 'MSP430G2453', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW28', 'MSP430G2453', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IPW28R', 'MSP430G2453', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IRHB32R', 'MSP430G2453', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2453IRHB32T', 'MSP430G2453', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IN20', 'MSP430G2513', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW20', 'MSP430G2513', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW20R', 'MSP430G2513', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW28', 'MSP430G2513', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IPW28R', 'MSP430G2513', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IRHB32R', 'MSP430G2513', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2513IRHB32T', 'MSP430G2513', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IN20', 'MSP430G2553', 'N', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW20', 'MSP430G2553', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW20R', 'MSP430G2553', 'PW', 20, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW28', 'MSP430G2553', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IPW28R', 'MSP430G2553', 'PW', 28, 'ACTIVE', 1, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IRHB32R', 'MSP430G2553', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');
INSERT INTO orderable (name, device_id, drawing, pins, status, msl_level, op_temp_min, op_temp_max, comment) VALUES ('MSP430G2553IRHB32T', 'MSP430G2553', 'RHB', 32, 'ACTIVE', 2, -40, 85, 'AUTOMATIC RESOLUTION');

INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (33, NULL, 0);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (34, NULL, 1);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (35, NULL, 2);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (36, NULL, 3);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (37, NULL, 4);
INSERT INTO signalset (id, parent_id, datasheet_idx) VALUES (38, NULL, 5);

INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 0, 'P1.0');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 1, 'TA0CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 2, 'ACLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 3, 'A0');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (33, 4, 'CA0');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 0, 'P1.1');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 1, 'TA0.0');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 2, 'UCA0RXD');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 3, 'UCA0SOMI');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 4, 'A1');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 5, 'CA1');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (34, 6, 'BSL_TX');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 0, 'P1.2');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 1, 'TA0.1');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 2, 'UCA0TXD');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 3, 'UCA0SIMO');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 4, 'A2');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (35, 5, 'CA2');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 0, 'P1.2');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 1, 'ADC10CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 2, 'A3');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 3, 'VREF-/VEREF-');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 4, 'CA3');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (36, 5, 'CAOUT');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 0, 'P1.4');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 1, 'SMCLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 2, 'UCB0STE');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 3, 'UCA0CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 4, 'A4');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 5, 'VREF+/VEREF+');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 6, 'CA4');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (37, 7, 'TCK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 0, 'P1.5');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 1, 'TA0.0');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 2, 'UCB0CLK');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 3, 'UCA0STE');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 4, 'A5');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 5, 'CA5');
INSERT INTO signalset_signal (signalset_id, idx, signal_id) VALUES (38, 6, 'TMS');

INSERT INTO pinset (id, pins, comment) VALUES (5, 6, NULL);
INSERT INTO pinset (id, pins, comment) VALUES (6, 6, NULL);
INSERT INTO pinset (id, pins, comment) VALUES (7, 6, NULL);
INSERT INTO pinset (id, pins, comment) VALUES (8, 6, NULL);

INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 33, NULL, '2');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 33, NULL, '2');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 33, NULL, '2');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 33, NULL, '31');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 34, NULL, '3');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 34, NULL, '3');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 34, NULL, '3');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 34, NULL, '1');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 35, NULL, '4');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 35, NULL, '4');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 35, NULL, '4');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 35, NULL, '2');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 36, NULL, '5');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 36, NULL, '5');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 36, NULL, '5');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 36, NULL, '3');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 37, NULL, '6');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 37, NULL, '6');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 37, NULL, '6');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 37, NULL, '4');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (5, 38, NULL, '7');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (6, 38, NULL, '7');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (7, 38, NULL, '7');
INSERT INTO pinset_signalset (pinset_id, signalset_id, pin_bga_row, pin_number) VALUES (8, 38, NULL, '5');

UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2113IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2153IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2213IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2253IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2313IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2353IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2413IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2453IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2513IN20';
UPDATE orderable SET pinset_id = 5 WHERE name = 'MSP430G2553IN20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2153IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2153IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2213IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2213IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2253IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2253IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2313IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2313IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2353IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2353IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2413IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2413IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2453IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2453IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2513IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2513IPW20R';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2553IPW20';
UPDATE orderable SET pinset_id = 6 WHERE name = 'MSP430G2553IPW20R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2153IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2153IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2213IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2253IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2253IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2313IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2353IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2353IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2413IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2413IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2453IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2453IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2513IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2513IPW28R';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2553IPW28';
UPDATE orderable SET pinset_id = 7 WHERE name = 'MSP430G2553IPW28R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2153IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2153IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2213IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2213IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2253IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2253IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2313IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2313IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2353IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2353IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2413IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2413IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2453IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2453IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2513IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2513IRHB32T';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2553IRHB32R';
UPDATE orderable SET pinset_id = 8 WHERE name = 'MSP430G2553IRHB32T';

COMMIT TRANSACTION;
